A4-Soccer: game.Field Class Reference
game.Field Class Reference
Public Member Functions
Field ()
boolean outOfBounds (Player player)
double getLength ()
double getWidth ()
Player getA1 ()
Player getD1 ()
Player getA2 ()
Player getD2 ()
Player getPlayerWithBall ()
void givePossession (String playerName)
Player getActionPlayer ()
void resetField ()
void setOnesTurn (boolean onesTurn)
boolean getOnesTurn ()
void setisStriker (boolean isStriker)
boolean getisStriker ()
Private Attributes
double length
double width
Player A1
Player D1
Player A2
Player D2
boolean onesTurn
boolean isStriker
Detailed Description
Definition at line 3 of file Field.java.
Constructor & Destructor Documentation
Field()
game.Field.Field ()
Definition at line 5 of file Field.java.
                   {
        length = 17;
        width = 11;
        A1 = Player.makeStriker("1");
        D1 = Player.makeDefender("1");
        A2 = Player.makeStriker("2");
        D2 = Player.makeDefender("2");
    }
References game.Field.A1, game.Field.A2, game.Field.D1, game.Field.D2, game.Field.length, game.Player.makeDefender(), game.Player.makeStriker(), and game.Field.width.
Member Function Documentation
getA1()
Player game.Field.getA1 ()
Definition at line 34 of file Field.java.
{
        return A1;
    }
References game.Field.A1.
Referenced by game.Probability.getShotProbability(), and game.FieldPanel.setPlayers().
getA2()
Player game.Field.getA2 ()
Definition at line 42 of file Field.java.
{
        return A2;
    }
References game.Field.A2.
Referenced by game.Probability.getShotProbability(), and game.FieldPanel.setPlayers().
getActionPlayer()
Player game.Field.getActionPlayer ()
Definition at line 94 of file Field.java.
{
        if (onesTurn) {
            if (isStriker) {
                return A1;
            } else {
                return D1;
            }
        } else {
            if (isStriker) {
                return A2;
            } else {
                return D2;
            }
        }
    }
References game.Field.A1, game.Field.A2, game.Field.D1, game.Field.D2, game.Field.isStriker, and game.Field.onesTurn.
Referenced by game.Probability.getShotProbability(), game.FieldPanel.paintComponent(), and game.GameManager.setButtonActions().
getD1()
Player game.Field.getD1 ()
Definition at line 38 of file Field.java.
{
        return D1;
    }
References game.Field.D1.
Referenced by game.Probability.getShotProbability(), and game.FieldPanel.setPlayers().
getD2()
Player game.Field.getD2 ()
Definition at line 46 of file Field.java.
{
        return D2;
    }
References game.Field.D2.
Referenced by game.Probability.getShotProbability(), and game.FieldPanel.setPlayers().
getisStriker()
boolean game.Field.getisStriker ()
Definition at line 135 of file Field.java.
{
        return isStriker;
    }
References game.Field.isStriker.
Referenced by game.AbstractPlayer.pass().
getLength()
double game.Field.getLength ()
Definition at line 26 of file Field.java.
{
        return length;
    }
References game.Field.length.
getOnesTurn()
boolean game.Field.getOnesTurn ()
Definition at line 127 of file Field.java.
{
        return onesTurn;
    }
References game.Field.onesTurn.
Referenced by game.AbstractPlayer.pass().
getPlayerWithBall()
Player game.Field.getPlayerWithBall ()
Definition at line 50 of file Field.java.
{
        if (A1.getBall()) {
            return A1;
        } else if (D1.getBall()) {
            return D1;
        } else if (A2.getBall()) {
            return A2;
        } else {
            return D2;
        }
    }
References game.Field.A1, game.Field.A2, game.Field.D1, game.Field.D2, and game.Player.getBall().
Referenced by game.FieldPanel.paintComponent(), game.Field.resetField(), and game.GameManager.setButtonActions().
getWidth()
double game.Field.getWidth ()
Definition at line 30 of file Field.java.
{
        return width;
    }
References game.Field.width.
givePossession()
void game.Field.givePossession (String playerName)
Definition at line 62 of file Field.java.
{
        if (playerName == "A1") {
            A1.setBall(true);
            D1.setBall(false);
            A2.setBall(false);
            D2.setBall(false);
            System.out.println("A1 Has Ball");
        } else if (playerName == "D1") {
            A1.setBall(false);
            D1.setBall(true);
            A2.setBall(false);
            D2.setBall(false);
            System.out.println("D1 Has Ball");
        } else if (playerName == "A2") {
            A1.setBall(false);
            D1.setBall(false);
            A2.setBall(true);
            D2.setBall(false);
            System.out.println("A2 Has Ball");
        } else if (playerName == "D2") {
            A1.setBall(false);
            D1.setBall(false);
            A2.setBall(false);
            D2.setBall(true);
            System.out.println("D2 Has Ball");
        } else {
            System.out.println("Error: Wrong Entry Made For Team Name");
        }
    }
References game.Field.A1, game.Field.A2, game.Field.D1, game.Field.D2, and game.Player.setBall().
Referenced by game.AbstractPlayer.pass(), game.Field.resetField(), and game.GameManager.setButtonActions().
outOfBounds()
boolean game.Field.outOfBounds (Player player)
Definition at line 16 of file Field.java.
{
        int[] position = player.getPosition();
        if (position[0] > length || position[0] < 0 || position[1] > width + 1 || position[1] < 0) {
            return true;
        } else {
            return false;
        }
    }
References game.Player.getPosition(), game.Field.length, and game.Field.width.
resetField()
void game.Field.resetField ()
Definition at line 110 of file Field.java.
{
        A1.setPosition(7, 6);
        A2.setPosition(10, 6);
        D1.setPosition(2, 6);
        D2.setPosition(15, 6);
        if (getPlayerWithBall().getTeam().equals("1")) {
            givePossession("A2");
        } else {
            givePossession("A1");
        }
    }
References game.Field.A1, game.Field.A2, game.Field.D1, game.Field.D2, game.Field.getPlayerWithBall(), game.Field.givePossession(), and game.Player.setPosition().
setisStriker()
void game.Field.setisStriker (boolean isStriker)
Definition at line 131 of file Field.java.
{
        this.isStriker = isStriker;
    }
References game.Field.isStriker.
Referenced by game.GameManager.setButtonActions().
setOnesTurn()
void game.Field.setOnesTurn (boolean onesTurn)
Definition at line 123 of file Field.java.
{
        this.onesTurn = onesTurn;
    }
References game.Field.onesTurn.
Referenced by game.GameManager.setButtonActions().
Member Data Documentation
A1
Player game.Field.A1 private
Definition at line 142 of file Field.java.
Referenced by game.Field.Field(), game.Field.getA1(), game.Field.getActionPlayer(), game.Field.getPlayerWithBall(), game.Field.givePossession(), and game.Field.resetField().
A2
Player game.Field.A2 private
Definition at line 144 of file Field.java.
Referenced by game.Field.Field(), game.Field.getA2(), game.Field.getActionPlayer(), game.Field.getPlayerWithBall(), game.Field.givePossession(), and game.Field.resetField().
D1
Player game.Field.D1 private
Definition at line 143 of file Field.java.
Referenced by game.Field.Field(), game.Field.getActionPlayer(), game.Field.getD1(), game.Field.getPlayerWithBall(), game.Field.givePossession(), and game.Field.resetField().
D2
Player game.Field.D2 private
Definition at line 145 of file Field.java.
Referenced by game.Field.Field(), game.Field.getActionPlayer(), game.Field.getD2(), game.Field.getPlayerWithBall(), game.Field.givePossession(), and game.Field.resetField().
isStriker
boolean game.Field.isStriker private
Definition at line 148 of file Field.java.
Referenced by game.Field.getActionPlayer(), game.Field.getisStriker(), and game.Field.setisStriker().
length
double game.Field.length private
Definition at line 139 of file Field.java.
Referenced by game.Field.Field(), game.Field.getLength(), and game.Field.outOfBounds().
onesTurn
boolean game.Field.onesTurn private
Definition at line 147 of file Field.java.
Referenced by game.Field.getActionPlayer(), game.Field.getOnesTurn(), and game.Field.setOnesTurn().
width
double game.Field.width private
Definition at line 140 of file Field.java.
Referenced by game.Field.Field(), game.Field.getWidth(), and game.Field.outOfBounds().
The documentation for this class was generated from the following file:
src/game/Field.java