A4-Soccer: game.Probability Class Reference
game.Probability Class Reference
Public Member Functions
Probability (Field field, Player player)
Static Public Member Functions
static double getSlopeToGoal (Player player)
static double getSlopeToPlayer (Player shooter, Player defender)
static boolean getShotProbability (Field field)
Detailed Description
Definition at line 5 of file Probability.java.
Constructor & Destructor Documentation
Probability()
game.Probability.Probability (Field field, Player player)
Definition at line 7 of file Probability.java.
{
    }
Member Function Documentation
getShotProbability()
static boolean game.Probability.getShotProbability (Field field) static
Definition at line 41 of file Probability.java.
{
        System.out.println("=======Retrieving Shot Probability======");
        Player player = field.getActionPlayer();
        // Getting posistion of player
        int x = player.getPosition()[0];
        int y = player.getPosition()[1];
        System.out.println("Player is located at (" + x + "," + y + ")");
        // Checking team to set Goal values
        int goalX;
        int goalY = 6;
        if (player.getTeam() == "1") {
            goalX = 17;
        } else {
            goalX = 0;
        }
        System.out.println("Goal is located at (" + goalX + "," + goalY + ")");
        // Calculating Distance from player to goal
        double d = Math.sqrt(((x - goalX) * (x - goalX)) + ((y - goalY) * (y - goalY)));
        System.out.println("Distance = " + d);
        int intD = (int) Math.round(d);
        System.out.println("intD = " + intD);
        // Retrieving player Stats
        int shotA = player.getShotA();
        System.out.println("ShotA = " + shotA);
        // Defenders
        // Retrieving Defenders Slope
        int blockA = 0;
        int xStandard = player.getPosition()[0];
        double slope = getSlopeToGoal(player);
        if (player.getTeam().equals("1")) {
            // Look at team 2 players
            if (field.getA2().getPosition()[0] > xStandard) {
                double s1 = getSlopeToPlayer(player, field.getA2());
                double diff = slope - s1;
                if (diff > -0.05 && diff < 0.05) {
                    blockA += field.getA2().getBlockA();
                }
            }
            if (field.getD2().getPosition()[0] > xStandard) {
                double s1 = getSlopeToPlayer(player, field.getD2());
                double diff = slope - s1;
                if (diff > -0.05 && diff < 0.05) {
                    blockA += field.getD2().getBlockA();
                }
            }
        } else {
            // Look at Team 1 players
            if (field.getA1().getPosition()[0] < xStandard) {
                double s1 = getSlopeToPlayer(player, field.getA1());
                double diff = slope - s1;
                if (diff > -0.05 && diff < 0.05) {
                    blockA += field.getA1().getBlockA();
                }
            }
            if (field.getD1().getPosition()[0] < xStandard) {
                double s1 = getSlopeToPlayer(player, field.getD1());
                double diff = slope - s1;
                if (diff > -0.05 && diff < 0.05) {
                    blockA += field.getD1().getBlockA();
                }
            }
        }
        System.out.println("BlockA = " + blockA);
        // Calculating Final Prob
        int finalProb = intD - shotA + blockA;
        System.out.println("finalProb = " + finalProb);
        // Finding Result using Random numbers
        if (finalProb <= 0) {
            return true;
        } else {
            Random rand = new Random();
            double r = rand.nextInt(finalProb);
            System.out.println("r = " + r);
            if (r == 0) {
                return true;
            } else {
                return false;
            }
        }
    }
References game.Field.getA1(), game.Field.getA2(), game.Field.getActionPlayer(), game.Player.getBlockA(), game.Field.getD1(), game.Field.getD2(), game.Player.getPosition(), game.Player.getShotA(), game.Probability.getSlopeToGoal(), game.Probability.getSlopeToPlayer(), and game.Player.getTeam().
Referenced by game.AbstractPlayer.shoot().
getSlopeToGoal()
static double game.Probability.getSlopeToGoal (Player player) static
Definition at line 11 of file Probability.java.
{
        int x = player.getPosition()[0];
        int y = player.getPosition()[1];
        int goalX;
        int goalY = 6;
        if (player.getTeam() == "1") {
            goalX = 17;
        } else {
            goalX = 0;
        }
        // Calculate Slope
        double slope = (double) (goalY - y) / (double) (goalX - x);
        System.out.println("Slope From Shooter to Goal = " + slope);
        return slope;
    }
References game.Player.getPosition(), and game.Player.getTeam().
Referenced by game.Probability.getShotProbability().
getSlopeToPlayer()
static double game.Probability.getSlopeToPlayer (Player shooter, Player defender) static
Definition at line 30 of file Probability.java.
{
        int x = shooter.getPosition()[0];
        int y = shooter.getPosition()[1];
        int x2 = defender.getPosition()[0];
        int y2 = defender.getPosition()[1];
        double slope = (double) (y2 - y) / (double) (x2 - x);
        System.out.println("Slope From Shooter to Defender = " + slope);
        return slope;
    }
References game.Player.getPosition().
Referenced by game.Probability.getShotProbability().
The documentation for this class was generated from the following file:
src/game/Probability.java