A4-Soccer: game.FieldPanel Class Reference
game.FieldPanel Class Reference
Public Member Functions
FieldPanel (Field field)
void paintComponent (Graphics g)
void setPlayers ()
void launchGame ()
void run ()
void draw (Graphics2D g2)
void setPlayers (Field field)
boolean getStart ()
void setStart (boolean start)
Static Public Member Functions
static int getTileSize ()
Static Public Attributes
static final int tileSize = originalTileSize * scale
static ArrayList< Player > players = new ArrayList<>()
Private Member Functions
void update ()
Private Attributes
final int maxScreenCol = 18
final int maxScreenRow = 13
final int screenWidth = tileSize * maxScreenCol
final int screenHeight = tileSize * maxScreenRow
final int FPS = 60
Thread gameThread
Field field
boolean start = false
Static Private Attributes
static final int originalTileSize = 16
Detailed Description
Definition at line 10 of file FieldPanel.java.
Constructor & Destructor Documentation
FieldPanel()
game.FieldPanel.FieldPanel (Field field)
Definition at line 12 of file FieldPanel.java.
{
        this.field = field;
        setPlayers(field);
        this.setPreferredSize(new Dimension(screenWidth, screenHeight));
        this.setBackground(Color.GREEN);
        this.setDoubleBuffered(true);
    }
References game.FieldPanel.field, game.FieldPanel.screenHeight, game.FieldPanel.screenWidth, and game.FieldPanel.setPlayers().
Member Function Documentation
draw()
void game.FieldPanel.draw (Graphics2D g2)
Definition at line 84 of file FieldPanel.java.
{
        // Creating CheckerBoard Patter
        int c = 1;
        for (int row = 0; row < maxScreenRow; row++) {
            for (int col = 0; col < maxScreenCol; col++) {
                if (c == 0) {
                    g2.setColor(new Color(76, 133, 39));
                    c = 1;
                } else {
                    g2.setColor(new Color(154, 173, 85));
                    c = 0;
                }
                g2.fillRect(col * tileSize, row * tileSize, tileSize, tileSize);
            }
            if (c == 0) {
                c = 1;
            } else {
                c = 0;
            }
        }
        // Creating Field LInes
        for (int row = 0; row < screenHeight; row++) {
            g2.setColor(Color.white);
            g2.fillRect(9 * tileSize, row, 3, 3);
        }
        // Creating Goals
        g2.fillRect(16, 5 * tileSize, 3, tileSize * 3);
        g2.fillRect(screenWidth - 16, 5 * tileSize, 3, tileSize * 3);
    }
References game.FieldPanel.maxScreenCol, game.FieldPanel.maxScreenRow, game.FieldPanel.screenHeight, game.FieldPanel.screenWidth, and game.FieldPanel.tileSize.
Referenced by game.FieldPanel.paintComponent().
getStart()
boolean game.FieldPanel.getStart ()
Definition at line 128 of file FieldPanel.java.
{
        return start;
    }
References game.FieldPanel.start.
getTileSize()
static int game.FieldPanel.getTileSize () static
Definition at line 124 of file FieldPanel.java.
{
        return tileSize;
    }
References game.FieldPanel.tileSize.
launchGame()
void game.FieldPanel.launchGame ()
Definition at line 59 of file FieldPanel.java.
{
        gameThread = new Thread(this);
        gameThread.start();
    }
References game.FieldPanel.gameThread.
Referenced by game.GameManager.GameManager().
paintComponent()
void game.FieldPanel.paintComponent (Graphics g)
Definition at line 26 of file FieldPanel.java.
{
        super.paintComponent(g);
        Graphics2D g2 = (Graphics2D) g;
        // Field
        draw(g2);
        if (start) {
            // Players
            for (Player p : players) {
                p.draw(g2);
            }
            // Ball
            Player playerWB = field.getPlayerWithBall();
            playerWB.drawBall(g2);
            // Turn
            Player playerWithTurn = field.getActionPlayer();
            playerWithTurn.drawTurn(g2);
            // Position
            for (Player p : players) {
                p.drawType(g2);
            }
        }
    }
References game.FieldPanel.draw(), game.Player.drawBall(), game.Player.drawTurn(), game.FieldPanel.field, game.Field.getActionPlayer(), game.Field.getPlayerWithBall(), game.FieldPanel.players, and game.FieldPanel.start.
run()
void game.FieldPanel.run ()
Definition at line 65 of file FieldPanel.java.
                      {
        double drawInterval = 1000000000 / FPS;
        double delta = 0;
        long lastTime = System.nanoTime();
        long currentTime;
        while (gameThread != null) {
            currentTime = System.nanoTime();
            delta += (currentTime = lastTime) / drawInterval;
            lastTime = currentTime;
            if (delta >= 1) {
                update();
                repaint();
                delta--;
            }
        }
    }
References game.FieldPanel.FPS, game.FieldPanel.gameThread, and game.FieldPanel.update().
setPlayers() [1/2]
void game.FieldPanel.setPlayers ()
Definition at line 55 of file FieldPanel.java.
{
    }
Referenced by game.FieldPanel.FieldPanel().
setPlayers() [2/2]
void game.FieldPanel.setPlayers (Field field)
Definition at line 117 of file FieldPanel.java.
{
        players.add(field.getA1());
        players.add(field.getD1());
        players.add(field.getA2());
        players.add(field.getD2());
    }
References game.FieldPanel.field, game.Field.getA1(), game.Field.getA2(), game.Field.getD1(), game.Field.getD2(), and game.FieldPanel.players.
setStart()
void game.FieldPanel.setStart (boolean start)
Definition at line 132 of file FieldPanel.java.
{
        this.start = start;
    }
References game.FieldPanel.start.
Referenced by game.GameManager.setButtonActions().
update()
void game.FieldPanel.update () private
Definition at line 22 of file FieldPanel.java.
{
    }
Referenced by game.FieldPanel.run().
Member Data Documentation
field
Field game.FieldPanel.field private
Definition at line 147 of file FieldPanel.java.
Referenced by game.FieldPanel.FieldPanel(), game.FieldPanel.paintComponent(), and game.FieldPanel.setPlayers().
FPS
final int game.FieldPanel.FPS = 60 private
Definition at line 144 of file FieldPanel.java.
Referenced by game.FieldPanel.run().
gameThread
Thread game.FieldPanel.gameThread private
Definition at line 146 of file FieldPanel.java.
Referenced by game.FieldPanel.launchGame(), and game.FieldPanel.run().
maxScreenCol
final int game.FieldPanel.maxScreenCol = 18 private
Definition at line 140 of file FieldPanel.java.
Referenced by game.FieldPanel.draw().
maxScreenRow
final int game.FieldPanel.maxScreenRow = 13 private
Definition at line 141 of file FieldPanel.java.
Referenced by game.FieldPanel.draw().
originalTileSize
final int game.FieldPanel.originalTileSize = 16 static private
Definition at line 136 of file FieldPanel.java.
players
ArrayList<Player> game.FieldPanel.players = new ArrayList<>() static
Definition at line 151 of file FieldPanel.java.
Referenced by game.FieldPanel.paintComponent(), and game.FieldPanel.setPlayers().
screenHeight
final int game.FieldPanel.screenHeight = tileSize * maxScreenRow private
Definition at line 143 of file FieldPanel.java.
Referenced by game.FieldPanel.draw(), and game.FieldPanel.FieldPanel().
screenWidth
final int game.FieldPanel.screenWidth = tileSize * maxScreenCol private
Definition at line 142 of file FieldPanel.java.
Referenced by game.FieldPanel.draw(), and game.FieldPanel.FieldPanel().
start
boolean game.FieldPanel.start = false private
Definition at line 148 of file FieldPanel.java.
Referenced by game.FieldPanel.getStart(), game.FieldPanel.paintComponent(), and game.FieldPanel.setStart().
tileSize
final int game.FieldPanel.tileSize = originalTileSize * scale static
Definition at line 139 of file FieldPanel.java.
Referenced by game.AbstractPlayer.draw(), game.FieldPanel.draw(), game.AbstractPlayer.drawBall(), game.AbstractPlayer.drawTurn(), game.AbstractPlayer.drawType(), and game.FieldPanel.getTileSize().
The documentation for this class was generated from the following file:
src/game/FieldPanel.java