A4-Soccer: game.AbstractPlayer Class Reference
game.AbstractPlayer Class Reference abstract
Public Member Functions
String toString ()
void pass (Field field)
void move (int dx, int dy)
boolean shoot (Field field)
int[] getPosition ()
void setPosition (int x, int y)
int getShotA ()
int getSpeedA ()
int getBlockA ()
int getStealA ()
String getName ()
String getTeam ()
boolean getBall ()
void setShotA (int newShotA)
void setSpeedA (int newSpeedA)
void setBlockA (int newBlockA)
void setStealA (int newStealA)
void setName (String newName)
void setTeam (String newTeam)
void setBall (boolean newBall)
void draw (Graphics2D g2)
void drawBall (Graphics2D g2)
void drawTurn (Graphics2D g2)
void drawType (Graphics2D g2)
Protected Attributes
int[] position = new int[2]
int shotA
int speedA
int blockA
int stealA
Player player
String name
String team
boolean ball
Additional Inherited Members
Static Public Member Functions inherited from game.Player
static Player makeStriker (String team)
static Player makeDefender (String team)
Detailed Description
Definition at line 6 of file AbstractPlayer.java.
Member Function Documentation
draw()
void game.AbstractPlayer.draw (Graphics2D g2)
Implements game.Player.
Definition at line 140 of file AbstractPlayer.java.
{
        if (this.getTeam().equals("1")) {
            g2.setColor(Color.RED);
        } else {
            g2.setColor(Color.BLUE);
        }
        g2.fillRoundRect(getPosition()[0] * FieldPanel.tileSize, getPosition()[1] * FieldPanel.tileSize,
                FieldPanel.tileSize, FieldPanel.tileSize, FieldPanel.tileSize, FieldPanel.tileSize);
    }
References game.AbstractPlayer.getPosition(), game.AbstractPlayer.getTeam(), and game.FieldPanel.tileSize.
drawBall()
void game.AbstractPlayer.drawBall (Graphics2D g2)
Implements game.Player.
Definition at line 150 of file AbstractPlayer.java.
{
        g2.setColor(Color.WHITE);
        int size = (int) Math.round(FieldPanel.tileSize * 0.5);
        int adjustment = (int) size / 2;
        g2.fillRoundRect(getPosition()[0] * FieldPanel.tileSize + adjustment,
                getPosition()[1] * FieldPanel.tileSize + adjustment, size, size, size, size);
    }
References game.AbstractPlayer.getPosition(), and game.FieldPanel.tileSize.
drawTurn()
void game.AbstractPlayer.drawTurn (Graphics2D g2)
Implements game.Player.
Definition at line 159 of file AbstractPlayer.java.
{
        g2.setColor(Color.WHITE);
        int size = 48;
        g2.drawArc(getPosition()[0] * FieldPanel.tileSize, getPosition()[1] * FieldPanel.tileSize, size, size, 0, 360);
    }
References game.AbstractPlayer.getPosition(), and game.FieldPanel.tileSize.
drawType()
void game.AbstractPlayer.drawType (Graphics2D g2)
Implements game.Player.
Definition at line 165 of file AbstractPlayer.java.
{
        g2.setColor(Color.WHITE);
        if (getName().equals("A1") || getName().equals("A2")) {
            g2.drawString("S", getPosition()[0] * FieldPanel.tileSize, getPosition()[1] * FieldPanel.tileSize);
        } else {
            g2.drawString("D", getPosition()[0] * FieldPanel.tileSize, getPosition()[1] * FieldPanel.tileSize);
        }
    }
References game.AbstractPlayer.getName(), game.AbstractPlayer.getPosition(), and game.FieldPanel.tileSize.
getBall()
boolean game.AbstractPlayer.getBall ()
Implements game.Player.
Definition at line 100 of file AbstractPlayer.java.
{
        return ball;
    }
References game.AbstractPlayer.ball.
getBlockA()
int game.AbstractPlayer.getBlockA ()
Implements game.Player.
Definition at line 80 of file AbstractPlayer.java.
{
        return blockA;
    }
References game.AbstractPlayer.blockA.
getName()
String game.AbstractPlayer.getName ()
Implements game.Player.
Definition at line 90 of file AbstractPlayer.java.
{
        return name;
    }
References game.AbstractPlayer.name.
Referenced by game.AbstractPlayer.drawType(), and game.AbstractPlayer.shoot().
getPosition()
int[] game.AbstractPlayer.getPosition ()
Implements game.Player.
Definition at line 59 of file AbstractPlayer.java.
{
        return position;
    }
References game.AbstractPlayer.position.
Referenced by game.AbstractPlayer.draw(), game.AbstractPlayer.drawBall(), game.AbstractPlayer.drawTurn(), and game.AbstractPlayer.drawType().
getShotA()
int game.AbstractPlayer.getShotA ()
Implements game.Player.
Definition at line 70 of file AbstractPlayer.java.
{
        return shotA;
    }
References game.AbstractPlayer.shotA.
getSpeedA()
int game.AbstractPlayer.getSpeedA ()
Implements game.Player.
Definition at line 75 of file AbstractPlayer.java.
{
        return speedA;
    }
References game.AbstractPlayer.speedA.
getStealA()
int game.AbstractPlayer.getStealA ()
Implements game.Player.
Definition at line 85 of file AbstractPlayer.java.
{
        return stealA;
    }
References game.AbstractPlayer.stealA.
getTeam()
String game.AbstractPlayer.getTeam ()
Implements game.Player.
Definition at line 95 of file AbstractPlayer.java.
{
        return team;
    }
References game.AbstractPlayer.team.
Referenced by game.AbstractPlayer.draw().
move()
void game.AbstractPlayer.move (int dx, int dy)
Implements game.Player.
Definition at line 32 of file AbstractPlayer.java.
{
        position[0] += dx;
        position[1] += dy;
        if (new Field().outOfBounds(this) == true) {
            System.out.println("Out Of Bounds, Original Position Maintained and Turn Lost");
            position[0] -= dx;
            position[1] -= dy;
        } else {
            System.out.println(name + " moved " + dx + " units laterally and " + dy + " units vertically");
        }
        System.out.println(this);
    }
References game.AbstractPlayer.name, and game.AbstractPlayer.position.
pass()
void game.AbstractPlayer.pass (Field field)
Implements game.Player.
Definition at line 13 of file AbstractPlayer.java.
{
        if (field.getOnesTurn()) {
            if (field.getisStriker()) {
                field.givePossession("D1");
            } else {
                field.givePossession("A1");
            }
        } else {
            if (field.getisStriker()) {
                field.givePossession("D2");
            } else {
                field.givePossession("A2");
            }
        }
    }
References game.Field.getisStriker(), game.Field.getOnesTurn(), and game.Field.givePossession().
setBall()
void game.AbstractPlayer.setBall (boolean newBall)
Implements game.Player.
Definition at line 135 of file AbstractPlayer.java.
{
        ball = newBall;
    }
References game.AbstractPlayer.ball.
setBlockA()
void game.AbstractPlayer.setBlockA (int newBlockA)
Implements game.Player.
Definition at line 115 of file AbstractPlayer.java.
{
        blockA = newBlockA;
    }
References game.AbstractPlayer.blockA.
setName()
void game.AbstractPlayer.setName (String newName)
Implements game.Player.
Definition at line 125 of file AbstractPlayer.java.
{
        name = newName;
    }
References game.AbstractPlayer.name.
setPosition()
void game.AbstractPlayer.setPosition (int x, int y)
Implements game.Player.
Definition at line 64 of file AbstractPlayer.java.
{
        position[0] = x;
        position[1] = y;
    }
References game.AbstractPlayer.position.
setShotA()
void game.AbstractPlayer.setShotA (int newShotA)
Implements game.Player.
Definition at line 105 of file AbstractPlayer.java.
{
        shotA = newShotA;
    }
References game.AbstractPlayer.shotA.
setSpeedA()
void game.AbstractPlayer.setSpeedA (int newSpeedA)
Implements game.Player.
Definition at line 110 of file AbstractPlayer.java.
{
        speedA = newSpeedA;
    }
References game.AbstractPlayer.speedA.
setStealA()
void game.AbstractPlayer.setStealA (int newStealA)
Implements game.Player.
Definition at line 120 of file AbstractPlayer.java.
{
        stealA = newStealA;
    }
References game.AbstractPlayer.stealA.
setTeam()
void game.AbstractPlayer.setTeam (String newTeam)
Implements game.Player.
Definition at line 130 of file AbstractPlayer.java.
{
        team = newTeam;
    }
References game.AbstractPlayer.team.
shoot()
boolean game.AbstractPlayer.shoot (Field field)
Implements game.Player.
Definition at line 46 of file AbstractPlayer.java.
{
        System.out.println(getName() + " Shoots");
        if (Probability.getShotProbability(field)) {
            System.out.println("GOAL!!!");
            return true;
        } else {
            System.out.println("Shot Failed. What a Save!");
            return false;
        }
    }
References game.AbstractPlayer.getName(), and game.Probability.getShotProbability().
toString()
String game.AbstractPlayer.toString ()
Definition at line 8 of file AbstractPlayer.java.
{
        return name + " is located at (" + position[0] + "," + position[1] + ")";
    }
References game.AbstractPlayer.name, and game.AbstractPlayer.position.
Member Data Documentation
ball
boolean game.AbstractPlayer.ball protected
Definition at line 184 of file AbstractPlayer.java.
Referenced by game.AbstractPlayer.getBall(), game.AbstractPlayer.setBall(), and game.Striker.Striker().
blockA
int game.AbstractPlayer.blockA protected
Definition at line 179 of file AbstractPlayer.java.
Referenced by game.Defender.Defender(), game.AbstractPlayer.getBlockA(), game.AbstractPlayer.setBlockA(), and game.Striker.Striker().
name
String game.AbstractPlayer.name protected
Definition at line 182 of file AbstractPlayer.java.
Referenced by game.Defender.Defender(), game.AbstractPlayer.getName(), game.AbstractPlayer.move(), game.AbstractPlayer.setName(), game.Striker.Striker(), and game.AbstractPlayer.toString().
player
Player game.AbstractPlayer.player protected
Definition at line 181 of file AbstractPlayer.java.
position
int [] game.AbstractPlayer.position = new int[2] protected
Definition at line 176 of file AbstractPlayer.java.
Referenced by game.Defender.Defender(), game.AbstractPlayer.getPosition(), game.AbstractPlayer.move(), game.AbstractPlayer.setPosition(), game.Striker.Striker(), and game.AbstractPlayer.toString().
shotA
int game.AbstractPlayer.shotA protected
Definition at line 177 of file AbstractPlayer.java.
Referenced by game.Defender.Defender(), game.AbstractPlayer.getShotA(), game.AbstractPlayer.setShotA(), and game.Striker.Striker().
speedA
int game.AbstractPlayer.speedA protected
Definition at line 178 of file AbstractPlayer.java.
Referenced by game.Defender.Defender(), game.AbstractPlayer.getSpeedA(), game.AbstractPlayer.setSpeedA(), and game.Striker.Striker().
stealA
int game.AbstractPlayer.stealA protected
Definition at line 180 of file AbstractPlayer.java.
Referenced by game.Defender.Defender(), game.AbstractPlayer.getStealA(), game.AbstractPlayer.setStealA(), and game.Striker.Striker().
team
String game.AbstractPlayer.team protected
Definition at line 183 of file AbstractPlayer.java.
Referenced by game.Defender.Defender(), game.AbstractPlayer.getTeam(), game.AbstractPlayer.setTeam(), and game.Striker.Striker().
The documentation for this class was generated from the following file:
src/game/AbstractPlayer.java