A4-Soccer: game.Player Interface Reference
game.Player Interface Reference
Public Member Functions
void pass (Field field)
void move (int x, int y)
boolean shoot (Field field)
int[] getPosition ()
void setPosition (int x, int y)
int getShotA ()
int getSpeedA ()
int getBlockA ()
int getStealA ()
String getName ()
String getTeam ()
boolean getBall ()
void setShotA (int newShotA)
void setSpeedA (int newSpeedA)
void setBlockA (int newBlockA)
void setStealA (int newStealA)
void setName (String newName)
void setTeam (String newTeam)
void setBall (boolean newBall)
void draw (Graphics2D g2)
void drawBall (Graphics2D g2)
void drawTurn (Graphics2D g2)
void drawType (Graphics2D g2)
Static Public Member Functions
static Player makeStriker (String team)
static Player makeDefender (String team)
Detailed Description
Definition at line 5 of file Player.java.
Member Function Documentation
draw()
void game.Player.draw (Graphics2D g2)
Implemented in game.AbstractPlayer.
drawBall()
void game.Player.drawBall (Graphics2D g2)
Implemented in game.AbstractPlayer.
Referenced by game.FieldPanel.paintComponent().
drawTurn()
void game.Player.drawTurn (Graphics2D g2)
Implemented in game.AbstractPlayer.
Referenced by game.FieldPanel.paintComponent().
drawType()
void game.Player.drawType (Graphics2D g2)
Implemented in game.AbstractPlayer.
getBall()
boolean game.Player.getBall ()
Implemented in game.AbstractPlayer.
Referenced by game.Field.getPlayerWithBall().
getBlockA()
int game.Player.getBlockA ()
Implemented in game.AbstractPlayer.
Referenced by game.Probability.getShotProbability().
getName()
String game.Player.getName ()
Implemented in game.AbstractPlayer.
getPosition()
int[] game.Player.getPosition ()
Implemented in game.AbstractPlayer.
Referenced by game.Probability.getShotProbability(), game.Probability.getSlopeToGoal(), game.Probability.getSlopeToPlayer(), and game.Field.outOfBounds().
getShotA()
int game.Player.getShotA ()
Implemented in game.AbstractPlayer.
Referenced by game.Probability.getShotProbability().
getSpeedA()
int game.Player.getSpeedA ()
Implemented in game.AbstractPlayer.
getStealA()
int game.Player.getStealA ()
Implemented in game.AbstractPlayer.
getTeam()
String game.Player.getTeam ()
Implemented in game.AbstractPlayer.
Referenced by game.Probability.getShotProbability(), and game.Probability.getSlopeToGoal().
makeDefender()
static Player game.Player.makeDefender (String team) static
Definition at line 11 of file Player.java.
{
        return new Defender(team);
    }
Referenced by game.Field.Field().
makeStriker()
static Player game.Player.makeStriker (String team) static
Definition at line 7 of file Player.java.
{
        return new Striker(team);
    }
Referenced by game.Field.Field().
move()
void game.Player.move (int x, int y)
Implemented in game.AbstractPlayer.
pass()
void game.Player.pass (Field field)
Implemented in game.AbstractPlayer.
setBall()
void game.Player.setBall (boolean newBall)
Implemented in game.AbstractPlayer.
Referenced by game.Field.givePossession().
setBlockA()
void game.Player.setBlockA (int newBlockA)
Implemented in game.AbstractPlayer.
setName()
void game.Player.setName (String newName)
Implemented in game.AbstractPlayer.
setPosition()
void game.Player.setPosition (int x, int y)
Implemented in game.AbstractPlayer.
Referenced by game.Field.resetField().
setShotA()
void game.Player.setShotA (int newShotA)
Implemented in game.AbstractPlayer.
setSpeedA()
void game.Player.setSpeedA (int newSpeedA)
Implemented in game.AbstractPlayer.
setStealA()
void game.Player.setStealA (int newStealA)
Implemented in game.AbstractPlayer.
setTeam()
void game.Player.setTeam (String newTeam)
Implemented in game.AbstractPlayer.
shoot()
boolean game.Player.shoot (Field field)
Implemented in game.AbstractPlayer.
The documentation for this interface was generated from the following file:
src/game/Player.java