A2-Poker: Card Class Reference
Card Class Reference
Public Member Functions
Card (CardUtils.Rank rank, String suit)
CardUtils.Rank getRank ()
String getSuit ()
int getRankValue ()
int getSuitValue ()
int compareTo (Card otherCard)
Private Attributes
final CardUtils.Rank rank
final String suit
Static Private Attributes
static final Map< CardUtils.Rank, Integer > RANK_MAP = new HashMap<>()
static final Map< String, Integer > SUIT_MAP = new HashMap<>()
Detailed Description
The Card class represents a playing card with a rank and a suit. Each card has an integer rank value and a string suit value.
Definition at line 15 of file Card.java.
Constructor & Destructor Documentation
Card()
Card.Card (CardUtils.Rank rank, String suit)
Constructs a card with the specified rank and suit.
Parameters
rank the rank of the card
suit the suit of the card
Definition at line 44 of file Card.java.
{
        this.rank = rank;
        this.suit = suit;
    }
References rank, and suit.
Member Function Documentation
compareTo()
int Card.compareTo (Card otherCard)
Compares this card with another card based on rank.
Parameters
otherCard the other card to compare
Returns
a negative integer, zero, or a positive integer as this card is less than, equal to, or greater than the specified card
Definition at line 103 of file Card.java.
{
        return Integer.compare(this.getRankValue(), otherCard.getRankValue());
    }
References getRankValue().
getRank()
CardUtils.Rank Card.getRank ()
Returns the rank of the card.
Returns
the rank of the card
Definition at line 54 of file Card.java.
{
        return rank;
    }
References rank.
getRankValue()
int Card.getRankValue ()
Returns the integer value of the rank.
Returns
the integer value of the rank
Exceptions
IllegalArgumentException if the rank is invalid
Definition at line 73 of file Card.java.
{
        Integer rankValue = RANK_MAP.get(rank);
        if (rankValue == null) {
            throw new IllegalArgumentException("Invalid Rank card: " + rank);
        }
        return rankValue;
    }
References rank, and RANK_MAP.
Referenced by compareTo(), Hand.isFourOfAKind(), Hand.isFullHouse(), and Hand.isStraightFlush().
getSuit()
String Card.getSuit ()
Returns the suit of the card.
Returns
the suit of the card
Definition at line 63 of file Card.java.
{
        return suit;
    }
References suit.
Referenced by Hand.isFlush().
getSuitValue()
int Card.getSuitValue ()
Returns the integer value of the suit.
Returns
the integer value of the suit
Exceptions
IllegalArgumentException if the suit is invalid
Definition at line 87 of file Card.java.
{
        Integer suitValue = SUIT_MAP.get(suit);
        if (suitValue == null) {
            throw new IllegalArgumentException("Invalid Suit card: " + suit);
        }
        return suitValue;
    }
References suit, and SUIT_MAP.
Member Data Documentation
rank
final CardUtils.Rank Card.rank private
Definition at line 16 of file Card.java.
Referenced by Card(), getRank(), and getRankValue().
RANK_MAP
final Map<CardUtils.Rank, Integer> Card.RANK_MAP = new HashMap<>() static private
Definition at line 20 of file Card.java.
Referenced by getRankValue().
suit
final String Card.suit private
Definition at line 17 of file Card.java.
Referenced by Card(), getSuit(), and getSuitValue().
SUIT_MAP
final Map<String, Integer> Card.SUIT_MAP = new HashMap<>() static private
Definition at line 29 of file Card.java.
Referenced by getSuitValue().
The documentation for this class was generated from the following file:
src/Card.java