A2-Poker: OnlinePokerGame Class Reference
OnlinePokerGame Class Reference
Public Member Functions
OnlinePokerGame ()
void addPlayer (Player player)
void removePlayer (Player player)
void startGame (int numberOfPlayers)
void dealHands ()
void placeBet (String playerUsername, boolean willWin)
Player determineWinner ()
boolean isPlayerInGame (String playerUsername)
Private Attributes
Player player
List< Player > players
int currentPlayerIndex
Map< Player, Boolean > bets
Detailed Description
The OnlinePokerGame class represents an online poker game where multiple players can participate. It implements the PokerGameInterface.
Definition at line 18 of file OnlinePokerGame.java.
Constructor & Destructor Documentation
OnlinePokerGame()
OnlinePokerGame.OnlinePokerGame ()
Constructs an OnlinePokerGame object with an empty list of players and an empty map of bets.
Definition at line 28 of file OnlinePokerGame.java.
{
        this.players = new ArrayList<>();
        this.currentPlayerIndex = 0;
        this.bets = new HashMap<>();
    }
Member Function Documentation
addPlayer()
void OnlinePokerGame.addPlayer (Player player)
Adds a player to the game and logs them in.
Parameters
player The player to add to the game
Implements PokerGameInterface.
Definition at line 39 of file OnlinePokerGame.java.
{
        if (players == null) {
            players = new ArrayList<>();
        }
        players.add(player);
        player.logIn();
    }
References Player.logIn(), player, and players.
dealHands()
void OnlinePokerGame.dealHands ()
Deals hands to all players in the game.
Implements PokerGameInterface.
Definition at line 89 of file OnlinePokerGame.java.
{
        Deck deck = new Deck();
        deck.shuffle();
        for (Player player : players) {
            Card[] privateCards = new Card[5];
            for (int i = 0; i < 5; i++) {
                privateCards[i] = deck.deal();
            }
            player.setPrivateCards(privateCards);
            player.setHand(Arrays.asList(privateCards));
        }
    }
References player, players, Player.setHand(), and Player.setPrivateCards().
Referenced by startGame().
determineWinner()
Player OnlinePokerGame.determineWinner ()
Determines the winner of the game based on the players' hands.
Returns
The player with the winning hand
Implements PokerGameInterface.
Definition at line 122 of file OnlinePokerGame.java.
{
        Hand bestHand = null;
        Player winner = null;
        if (!players.isEmpty()) {
            bestHand = new Hand(players.get(0).getPrivateCards());
            winner = players.get(0);
        } else {
            throw new IllegalArgumentException("No players in the game. Cannot determine a winner.");
        }
        for (int i = 1; i < players.size(); i++) {
            Hand currentHand = new Hand(players.get(i).getPrivateCards());
            if (currentHand.compareTo(bestHand) > 0) {
                bestHand = currentHand;
                winner = players.get(i);
            }
        }
        System.out.println("Winner: " + winner.getUsername() + " with hand: " + bestHand.evaluate());
        return winner;
    }
References players.
Referenced by startGame().
isPlayerInGame()
boolean OnlinePokerGame.isPlayerInGame (String playerUsername)
Checks if a player is in the game.
Parameters
playerUsername The username of the player to check
Returns
True if the player is in the game, false otherwise
Definition at line 151 of file OnlinePokerGame.java.
{
        for (Player player : players) {
            if (player.getUsername().equals(playerUsername)) {
                return true;
            }
        }
        return false;
    }
References Player.getUsername(), player, and players.
Referenced by placeBet().
placeBet()
void OnlinePokerGame.placeBet (String playerUsername, boolean willWin)
Places a bet for the specified player.
Parameters
playerUsername The username of the player placing the bet
willWin True if the player will win, false otherwise
Implements PokerGameInterface.
Definition at line 108 of file OnlinePokerGame.java.
{
        if (!isPlayerInGame(playerUsername)) {
            System.out.println(playerUsername + " is not part of the game.");
            return;
        }
        bets.put(players.get(currentPlayerIndex), willWin);
        System.out.println(playerUsername + " has placed a bet on " + (willWin ? "winning" : "losing"));
    }
References bets, currentPlayerIndex, isPlayerInGame(), and players.
Referenced by startGame().
removePlayer()
void OnlinePokerGame.removePlayer (Player player)
Removes a player from the game.
Parameters
player The player to remove from the game
Implements PokerGameInterface.
Definition at line 52 of file OnlinePokerGame.java.
{
        boolean removed = players.remove(player);
        if (removed) {
            bets.remove(player);
            for (Map.Entry<Player, Boolean> entry : bets.entrySet()) {
                Player currentPlayer = entry.getKey();
                Boolean betStatus = entry.getValue();
                System.out.println(currentPlayer.getUsername() + " has been removed from the game.");
            }
        } else {
            System.out.println("Could not find " + player.getUsername() + " in the game.");
        }
    }
References bets, Player.getUsername(), player, and players.
startGame()
void OnlinePokerGame.startGame (int numberOfPlayers)
Starts the game with the specified number of players.
Parameters
numberOfPlayers The number of players required to start the game
Implements PokerGameInterface.
Definition at line 71 of file OnlinePokerGame.java.
{
        if (players.size() != numberOfPlayers) {
            System.out.println("Not enough players to start the game.");
            return;
        }
        dealHands();
        for (Player player : players) {
            placeBet(player.getUsername(), true);
        }
        determineWinner();
    }
References dealHands(), determineWinner(), Player.getUsername(), placeBet(), player, and players.
Member Data Documentation
bets
Map<Player, Boolean> OnlinePokerGame.bets private
Definition at line 22 of file OnlinePokerGame.java.
Referenced by placeBet(), and removePlayer().
currentPlayerIndex
int OnlinePokerGame.currentPlayerIndex private
Definition at line 21 of file OnlinePokerGame.java.
Referenced by placeBet().
player
Player OnlinePokerGame.player private
Definition at line 19 of file OnlinePokerGame.java.
Referenced by addPlayer(), dealHands(), isPlayerInGame(), removePlayer(), and startGame().
players
List<Player> OnlinePokerGame.players private
Definition at line 20 of file OnlinePokerGame.java.
Referenced by addPlayer(), dealHands(), determineWinner(), isPlayerInGame(), placeBet(), removePlayer(), and startGame().
The documentation for this class was generated from the following file:
src/OnlinePokerGame.java