A2-Poker: Deck Class Reference
Deck Class Reference
Classes
enum Suit
Public Member Functions
Deck ()
void initializeDeck ()
void shuffle ()
Card deal ()
Protected Attributes
final List< Card > cards
Detailed Description
The Deck class represents a deck of playing cards. It provides methods for initializing the deck, shuffling the cards, and dealing cards. This class utilizes the Card class to represent individual playing cards.
Definition at line 17 of file Deck.java.
Constructor & Destructor Documentation
Deck()
Deck.Deck ()
Constructor for the Deck class. Initializes a new deck of playing cards.
Definition at line 24 of file Deck.java.
                  {
        this.cards = new ArrayList<>();
        initializeDeck();
    }
References initializeDeck().
Member Function Documentation
deal()
Card Deck.deal ()
Deals a card from the top of the deck. If the deck is empty, prints an error message and returns null.
Returns
The top card from the deck, or null if the deck is empty.
Definition at line 62 of file Deck.java.
                       {
        if (cards.isEmpty()) {
            System.out.println("Deck is empty. Unable to deal a card.");
            return null;
        }
        return cards.remove(0);
    }
References cards.
initializeDeck()
void Deck.initializeDeck ()
Initializes the deck with a standard set of 52 playing cards, one for each combination of suit and rank.
Definition at line 40 of file Deck.java.
{
        for (Suit suit : Suit.values()) {
            for (CardUtils.Rank rank : CardUtils.Rank.values()) {
                cards.add(new Card(rank, suit.toString()));
            }
        }
        shuffle();
    }
References cards, and shuffle().
Referenced by Deck().
shuffle()
void Deck.shuffle ()
Shuffles the deck by rearranging the order of cards randomly.
Reimplemented in ShortDeck.
Definition at line 52 of file Deck.java.
{
        Collections.shuffle(cards);
    }
References cards.
Referenced by initializeDeck().
Member Data Documentation
cards
final List<Card> Deck.cards protected
Definition at line 19 of file Deck.java.
Referenced by deal(), initializeDeck(), ShortDeck.removeLowCards(), shuffle(), and ShortDeck.shuffle().
The documentation for this class was generated from the following file:
src/Deck.java