A2-Poker: Hand Class Reference
Hand Class Reference
Public Member Functions
Hand (Card[] cards)
String evaluate ()
int compareTo (Hand otherHand)
Private Member Functions
boolean isFourOfAKind ()
boolean isStraightFlush ()
boolean isFlush ()
boolean isFullHouse ()
Private Attributes
Card[] cards
Detailed Description
The Hand class represents a hand of cards in a card game. It provides methods to evaluate the hand and compare hands. Hands must contain exactly 5 cards.
Definition at line 14 of file Hand.java.
Constructor & Destructor Documentation
Hand()
Hand.Hand (Card[] cards)
Constructs a hand with the given array of cards.
Parameters
cards the array of cards representing the hand
Exceptions
IllegalArgumentException if the number of cards is not exactly 5
Definition at line 23 of file Hand.java.
{
        if (cards.length != 5) {
            throw new IllegalArgumentException("Hand must contain 5 cards");
        }
        this.cards = cards;
        Arrays.sort(this.cards); // sort to make it easier for running
    }
References cards.
Member Function Documentation
compareTo()
int Hand.compareTo (Hand otherHand)
Compares this hand with another hand based on their ranks.
Parameters
otherHand the other hand to compare with
Returns
a negative integer, zero, or a positive integer as this hand is less than, equal to, or greater than the specified hand
Definition at line 143 of file Hand.java.
{
        // Compare hands based on their ranks
        return Integer.compare(this.evaluate().compareTo(otherHand.evaluate()), 0);
    }
References compareTo(), and evaluate().
Referenced by compareTo().
evaluate()
String Hand.evaluate ()
Evaluates the hand and returns a string representing its rank.
Returns
a string representing the rank of the hand
Definition at line 36 of file Hand.java.
{
        // Code to evaluate the hand
        if (isFourOfAKind()) {
            return "Four of A Kind";
        }
        if (isStraightFlush()) {
            return "Straight Flush";
        }
        // Add other hand evaluations as needed
        return "High Card";
    }
References isFourOfAKind(), and isStraightFlush().
Referenced by compareTo().
isFlush()
boolean Hand.isFlush () private
Checks if the hand contains Flush.
Returns
true if all cards have the same suit, false otherwise
Definition at line 103 of file Hand.java.
{
        String suit = cards[0].getSuit();
        for (Card card : cards) {
            if (!card.getSuit().equals(suit)) {
                return false;
            }
        }
        return true;
    }
References cards, and Card.getSuit().
Referenced by isStraightFlush().
isFourOfAKind()
boolean Hand.isFourOfAKind () private
Checks if the hand contains four cards of the same rank.
Returns
true if the hand contains four of a kind, false otherwise
Definition at line 54 of file Hand.java.
{
        int rankCount = 0;
        int currentRank = cards[0].getRankValue();
        for (Card card : cards) {
            if (card.getRankValue() == currentRank) { // check if it is the same value
                rankCount++;
            } else {
                currentRank = card.getRankValue();
                rankCount = 1;
            }
            if (rankCount == 4) {
                return true;
            }
        }
        return false;
    }
References cards, and Card.getRankValue().
Referenced by evaluate().
isFullHouse()
boolean Hand.isFullHouse () private
Checks if the hand contains isFullHouse
Returns
true if the hand contains a full house, false otherwise
Definition at line 118 of file Hand.java.
{
        int rankCount1 = 0;
        int rankCount2 = 0;
        int currentRank = cards[0].getRankValue();
        for (Card card : cards) {
            if (card.getRankValue() == currentRank) {
                rankCount1++;
            } else {
                currentRank = card.getRankValue();
                rankCount2 = 1;
            }
        }
        return (rankCount1 == 3 && rankCount2 == 2) || (rankCount1 == 2 && rankCount2 == 3);
    }
References cards, and Card.getRankValue().
isStraightFlush()
boolean Hand.isStraightFlush () private
Checks if the hand contains Straight Flush.
Returns
true if the hand contains a straight flush, false otherwise
Definition at line 76 of file Hand.java.
{
        if (!isFlush()) {
            return false;
        }
        int currentRank = cards[0].getRankValue();
        int consecutive = 1;
        for (int i = 1; i < cards.length; i++) {
            if (cards[i].getRankValue() == currentRank + 1) {
                consecutive++;
                currentRank++;
            } else {
                consecutive = 1;
                currentRank = cards[i].getRankValue();
            }
            if (consecutive == 5) {
                return true;
            }
        }
        return false;
    }
References cards, Card.getRankValue(), and isFlush().
Referenced by evaluate().
Member Data Documentation
cards
Card [] Hand.cards private
Definition at line 15 of file Hand.java.
Referenced by Hand(), isFlush(), isFourOfAKind(), isFullHouse(), and isStraightFlush().
The documentation for this class was generated from the following file:
src/Hand.java