A2-Poker: CardUtils.Rank Enum Reference
CardUtils.Rank Enum Reference
Public Member Functions
Rank (int rankValue)
int getRankValue ()
Public Attributes
TWO =(2)
THREE =(3)
FOUR =(4)
FIVE =(5)
SIX =(6)
SEVEN =(7)
EIGHT =(8)
NINE =(9)
TEN =(10)
JACK =(11)
QUEEN =(12)
KING =(13)
ACE =(14)
Private Attributes
final int rankValue
Detailed Description
Definition at line 9 of file CardUtils.java.
Constructor & Destructor Documentation
Rank()
CardUtils.Rank.Rank (int rankValue)
Definition at line 15 of file CardUtils.java.
{
            this.rankValue = rankValue;
        }
Member Function Documentation
getRankValue()
int CardUtils.Rank.getRankValue ()
Definition at line 19 of file CardUtils.java.
{
            return rankValue;
        }
Member Data Documentation
ACE
CardUtils.Rank.ACE =(14)
Definition at line 11 of file CardUtils.java.
EIGHT
CardUtils.Rank.EIGHT =(8)
Definition at line 10 of file CardUtils.java.
Referenced by OnlinePokerGameTest.testDetermineWinner().
FIVE
CardUtils.Rank.FIVE =(5)
Definition at line 10 of file CardUtils.java.
FOUR
CardUtils.Rank.FOUR =(4)
Definition at line 10 of file CardUtils.java.
JACK
CardUtils.Rank.JACK =(11)
Definition at line 10 of file CardUtils.java.
KING
CardUtils.Rank.KING =(13)
Definition at line 10 of file CardUtils.java.
NINE
CardUtils.Rank.NINE =(9)
Definition at line 10 of file CardUtils.java.
Referenced by OnlinePokerGameTest.testDetermineWinner().
QUEEN
CardUtils.Rank.QUEEN =(12)
Definition at line 10 of file CardUtils.java.
rankValue
final int CardUtils.Rank.rankValue private
Definition at line 13 of file CardUtils.java.
SEVEN
CardUtils.Rank.SEVEN =(7)
Definition at line 10 of file CardUtils.java.
Referenced by OnlinePokerGameTest.testDetermineWinner().
SIX
CardUtils.Rank.SIX =(6)
Definition at line 10 of file CardUtils.java.
Referenced by ShortDeck.removeLowCards(), and OnlinePokerGameTest.testDetermineWinner().
TEN
CardUtils.Rank.TEN =(10)
Definition at line 10 of file CardUtils.java.
Referenced by OnlinePokerGameTest.testDetermineWinner().
THREE
CardUtils.Rank.THREE =(3)
Definition at line 10 of file CardUtils.java.
TWO
CardUtils.Rank.TWO =(2)
Definition at line 10 of file CardUtils.java.
The documentation for this enum was generated from the following file:
src/CardUtils.java