BTH-Accounts: csc232.Account Class Reference
csc232.Account Class Reference abstract
Public Member Functions
String name ()
int balance ()
void deposit (int amount)
boolean withdraw (int amount)
void transfer (int amount, Account other)
abstract void endOfMonth ()
Static Public Member Functions
static Account makeChecking (String name, int fee)
static Account makeSaving (String name, double rate)
Protected Member Functions
Account (String name)
Protected Attributes
int balance
Private Attributes
String name
Detailed Description
An Account object represents any kind of bank account that maintains a current balance and allows deposits, withdrawals, and transfers to other accounts. It is an abstract class, because any extending class needs to specify what happens at the end of the month (e.g., fees or interest payments).
For simplicity, the account balance is stored as an integer.
Definition at line 12 of file Account.java.
Constructor & Destructor Documentation
Account()
csc232.Account.Account (String name) protected
Construct an Account with the given name. Subclass constructors will need to call this via super(name).
Parameters
name
Definition at line 22 of file Account.java.
{
        this.name = name;
        this.balance = 0;
    }
References csc232.Account.name.
Member Function Documentation
balance()
int csc232.Account.balance ()
Returns
the current balance of this Account
Definition at line 61 of file Account.java.
{
        return balance;
    }
References csc232.Account.balance.
deposit()
void csc232.Account.deposit (int amount)
Deposit the given amount into this Account.
Parameters
amount
Definition at line 70 of file Account.java.
{
        balance += amount;
    }
References csc232.Account.balance.
Referenced by Main.main(), and csc232.Account.transfer().
endOfMonth()
abstract void csc232.Account.endOfMonth () abstract
Perform the appropriate end-of-month processing for this Account.
Reimplemented in csc232.CheckingAccount, and csc232.SavingAccount.
Referenced by Main.main().
makeChecking()
static Account csc232.Account.makeChecking (String name, int fee) static
Factory method to create a new CheckingAccount with the given name and monthly fee.
Parameters
name
fee
Returns
the created account
Definition at line 35 of file Account.java.
{
        return new CheckingAccount(name, fee);
    }
References csc232.Account.name.
Referenced by Main.main().
makeSaving()
static Account csc232.Account.makeSaving (String name, double rate) static
Factory method to create a new SavingAccount with the given name and interest rate.
Parameters
name
rate
Returns
the created account
Definition at line 47 of file Account.java.
{
        return new SavingAccount(name, rate);
    }
References csc232.Account.name.
Referenced by Main.main().
name()
String csc232.Account.name ()
Returns
the name of this Account
Definition at line 54 of file Account.java.
{
        return name;
    }
References csc232.Account.name.
transfer()
void csc232.Account.transfer (int amount, Account other)
Attempt to withdraw the given amount from this Account, and deposit it into another specified Account. No action is taken if this Account does not allow the withdrawal.
Parameters
amount
other
Definition at line 98 of file Account.java.
{
        if (withdraw(amount)) {
            other.deposit(amount);
        }
    }
References csc232.Account.deposit(), and csc232.Account.withdraw().
Referenced by Main.main().
withdraw()
boolean csc232.Account.withdraw (int amount)
Attempt to withdraw the given amount from this Account. If the withdrawal is not allowed, returns false.
Parameters
amount
Returns
true if successful
Definition at line 81 of file Account.java.
{
        if (amount >= 0 && amount <= balance) {
            balance -= amount;
            return true;
        } else {
            return false;
        }
    }
References csc232.Account.balance.
Referenced by Main.main(), and csc232.Account.transfer().
Member Data Documentation
balance
int csc232.Account.balance protected
Definition at line 14 of file Account.java.
Referenced by csc232.Account.balance(), csc232.Account.deposit(), csc232.CheckingAccount.endOfMonth(), csc232.SavingAccount.endOfMonth(), and csc232.Account.withdraw().
name
String csc232.Account.name private
Definition at line 13 of file Account.java.
Referenced by csc232.Account.Account(), csc232.CheckingAccount.CheckingAccount(), csc232.Account.makeChecking(), csc232.Account.makeSaving(), csc232.Account.name(), and csc232.SavingAccount.SavingAccount().
The documentation for this class was generated from the following file:
src/csc232/Account.java