A5-Battleship: Location Class Reference
Location Class Reference
Public Member Functions
Location ()
boolean checkHit ()
boolean checkMiss ()
boolean isUnguessed ()
void markHit ()
void markMiss ()
boolean hasShip ()
void setShip (boolean val)
void setStatus (int status)
int getStatus ()
Static Public Attributes
static final int UNGUESSED = 0
static final int HIT = 1
static final int MISSED = 2
Private Attributes
boolean hasShip
int status
Detailed Description
Definition at line 1 of file Location.java.
Constructor & Destructor Documentation
Location()
Location.Location ()
Definition at line 10 of file Location.java.
                      {
        status = 0;
    }
References status.
Member Function Documentation
checkHit()
boolean Location.checkHit ()
Definition at line 15 of file Location.java.
{
        if (status == 1) {
            return true;
        }
        return false;
    }
References status.
checkMiss()
boolean Location.checkMiss ()
Definition at line 23 of file Location.java.
{
        if (status == 2) {
            return true;
        }
        return false;
    }
References status.
getStatus()
int Location.getStatus ()
Definition at line 67 of file Location.java.
{
        return status;
    }
References status.
Referenced by Grid.getStatus().
hasShip()
boolean Location.hasShip ()
Definition at line 49 of file Location.java.
{
        if (hasShip == true) {
            return true;
        }
        return false;
    }
References hasShip.
isUnguessed()
boolean Location.isUnguessed ()
Definition at line 31 of file Location.java.
{
        if (status == 0) {
            return true;
        } else
            return false;
    }
References status.
Referenced by Grid.alreadyGuessed().
markHit()
void Location.markHit ()
Definition at line 39 of file Location.java.
{
        status = 1;
    }
References status.
Referenced by Grid.markHit().
markMiss()
void Location.markMiss ()
Definition at line 44 of file Location.java.
{
        status = 2;
    }
References status.
Referenced by Grid.markMiss().
setShip()
void Location.setShip (boolean val)
Definition at line 57 of file Location.java.
{
        hasShip = true;
    }
References hasShip.
Referenced by Grid.setShip().
setStatus()
void Location.setStatus (int status)
Definition at line 62 of file Location.java.
{
        this.status = status;
    }
References status.
Referenced by Grid.setStatus().
Member Data Documentation
hasShip
boolean Location.hasShip private
Definition at line 6 of file Location.java.
Referenced by hasShip(), Grid.hasShip(), and setShip().
HIT
final int Location.HIT = 1 static
Definition at line 3 of file Location.java.
MISSED
final int Location.MISSED = 2 static
Definition at line 4 of file Location.java.
status
int Location.status private
Definition at line 7 of file Location.java.
Referenced by checkHit(), checkMiss(), getStatus(), isUnguessed(), Location(), markHit(), markMiss(), and setStatus().
UNGUESSED
final int Location.UNGUESSED = 0 static
Definition at line 2 of file Location.java.
The documentation for this class was generated from the following file:
src/Location.java