A5-Battleship: Ship Class Reference
Ship Class Reference
Public Member Functions
Ship (int l)
void setLocation (int r, int c)
void setDirection (int d)
int getRow ()
int getCol ()
int getLength ()
int getDirection ()
String toString ()
boolean isLocationSet ()
boolean isSunk ()
boolean isDirectionSet ()
Static Public Attributes
static final int UNSET = -1
static final int HORIZONTAL = 0
static final int VERTICAL = 1
Private Member Functions
String directionToString ()
String locationToString ()
Private Attributes
int row
int col
int length
String direction
Detailed Description
Definition at line 1 of file Ship.java.
Constructor & Destructor Documentation
Ship()
Ship.Ship (int l)
Definition at line 11 of file Ship.java.
                       {
        length = l;
        row = UNSET;
        col = UNSET;
    }
References col, length, row, and UNSET.
Member Function Documentation
directionToString()
String Ship.directionToString () private
Definition at line 57 of file Ship.java.
{
        if (direction == null) {
            return "unset direction";
        }
        return direction;
    }
References direction.
Referenced by toString().
getCol()
int Ship.getCol ()
Definition at line 39 of file Ship.java.
{
        return col;
    }
References col.
Referenced by Grid.addShip().
getDirection()
int Ship.getDirection ()
Definition at line 47 of file Ship.java.
{
        if (direction == "horizontal") {
            return HORIZONTAL;
        }
        if (direction == "vertical") {
            return VERTICAL;
        }
        return UNSET;
    }
References direction, HORIZONTAL, UNSET, and VERTICAL.
Referenced by Grid.addShip().
getLength()
int Ship.getLength ()
Definition at line 43 of file Ship.java.
{
        return length;
    }
References length.
Referenced by Grid.addShip().
getRow()
int Ship.getRow ()
Definition at line 35 of file Ship.java.
{
        return row;
    }
References row.
Referenced by Grid.addShip().
isDirectionSet()
boolean Ship.isDirectionSet ()
Definition at line 86 of file Ship.java.
{
        if (direction == null) {
            return false;
        }
        return true;
    }
References direction.
isLocationSet()
boolean Ship.isLocationSet ()
Definition at line 75 of file Ship.java.
{
        if (row == -1 || col == -1) {
            return false;
        }
        return true;
    }
References col, and row.
Referenced by locationToString().
isSunk()
boolean Ship.isSunk ()
Reimplemented in largeShip, and smallShip.
Definition at line 82 of file Ship.java.
{
        return false;
    }
locationToString()
String Ship.locationToString () private
Definition at line 64 of file Ship.java.
{
        if (this.isLocationSet() == false) {
            return "unset location";
        }
        return row + ", " + col;
    }
References col, and isLocationSet().
Referenced by toString().
setDirection()
void Ship.setDirection (int d)
Definition at line 22 of file Ship.java.
{
        if (d == HORIZONTAL) {
            direction = "horizontal";
        }
        if (d == VERTICAL) {
            direction = "vertical";
        }
        if (d == UNSET) {
            direction = "unset";
        }
    }
References direction, HORIZONTAL, UNSET, and VERTICAL.
Referenced by Player.chooseShipLocation().
setLocation()
void Ship.setLocation (int r, int c)
Definition at line 17 of file Ship.java.
{
        row = r;
        col = c;
    }
References col, and row.
Referenced by Player.chooseShipLocation().
toString()
String Ship.toString ()
Definition at line 71 of file Ship.java.
{
        return directionToString() + " ship of length " + length + " at " + "(" + locationToString() + ")";
    }
References directionToString(), length, and locationToString().
Member Data Documentation
col
int Ship.col private
Definition at line 3 of file Ship.java.
Referenced by getCol(), isLocationSet(), locationToString(), setLocation(), and Ship().
direction
String Ship.direction private
Definition at line 5 of file Ship.java.
Referenced by directionToString(), getDirection(), isDirectionSet(), and setDirection().
HORIZONTAL
final int Ship.HORIZONTAL = 0 static
Definition at line 8 of file Ship.java.
Referenced by getDirection(), and setDirection().
length
int Ship.length private
Definition at line 4 of file Ship.java.
Referenced by getLength(), Ship(), and toString().
row
int Ship.row private
Definition at line 2 of file Ship.java.
Referenced by getRow(), isLocationSet(), setLocation(), and Ship().
UNSET
final int Ship.UNSET = -1 static
Definition at line 7 of file Ship.java.
Referenced by getDirection(), setDirection(), and Ship().
VERTICAL
final int Ship.VERTICAL = 1 static
Definition at line 9 of file Ship.java.
Referenced by getDirection(), and setDirection().
The documentation for this class was generated from the following file:
src/Ship.java