A5-Battleship: Player Class Reference
Player Class Reference
Public Member Functions
Player ()
Ship[] getShips ()
Grid getOwn ()
Grid getOpp ()
boolean allShipsSunk ()
void printMyShips ()
void printOpponentGuesses ()
void printMyGuesses ()
void chooseShipLocation (Ship s, int row, int col, int direction)
void recordOpponentGuess (int row, int col)
Private Attributes
Ship[] ships
Grid own = new Grid()
Grid opp = new Grid()
Static Private Attributes
static final int[] SHIP_LENGTHS = { 2, 5 }
Detailed Description
Definition at line 6 of file Player.java.
Constructor & Destructor Documentation
Player()
Player.Player ()
Definition at line 12 of file Player.java.
                    {
        ships = new Ship[SHIP_LENGTHS.length];
        ships[0] = new smallShip(); // Initialize small ship
        ships[1] = new largeShip(); // Initialize large ship
    }
References SHIP_LENGTHS, and ships.
Member Function Documentation
allShipsSunk()
boolean Player.allShipsSunk ()
Definition at line 30 of file Player.java.
{
        for (Ship ship : ships) {
            if (!ship.isSunk()) {
                return false;
            }
        }
        return true;
    }
References ships.
Referenced by Main.gameOver().
chooseShipLocation()
void Player.chooseShipLocation (Ship s, int row, int col, int direction)
Definition at line 51 of file Player.java.
{
        s.setLocation(row, col);
        s.setDirection(direction);
        own.addShip(s);
    }
References Grid.addShip(), own, Ship.setDirection(), and Ship.setLocation().
Referenced by Main.placeShips().
getOpp()
Grid Player.getOpp ()
Definition at line 26 of file Player.java.
{
        return opp;
    }
References opp.
Referenced by Main.makeGuess().
getOwn()
Grid Player.getOwn ()
Definition at line 22 of file Player.java.
{
        return own;
    }
References own.
Referenced by Main.makeGuess().
getShips()
Ship[] Player.getShips ()
Definition at line 18 of file Player.java.
{
        return ships;
    }
References ships.
Referenced by Main.placeShips().
printMyGuesses()
void Player.printMyGuesses ()
Definition at line 47 of file Player.java.
{
        own.printStatus();
    }
References own, and Grid.printStatus().
printMyShips()
void Player.printMyShips ()
Definition at line 39 of file Player.java.
{
        own.printShips();
    }
References own, and Grid.printShips().
printOpponentGuesses()
void Player.printOpponentGuesses ()
Definition at line 43 of file Player.java.
{
        opp.printStatus();
    }
References opp, and Grid.printStatus().
recordOpponentGuess()
void Player.recordOpponentGuess (int row, int col)
Definition at line 57 of file Player.java.
{
        if (own.hasShip(row, col)) {
            opp.markHit(row, col);
        } else {
            opp.markMiss(row, col);
        }
    }
References Grid.hasShip(), Grid.markHit(), Grid.markMiss(), opp, and own.
Referenced by Main.makeGuess().
Member Data Documentation
opp
Grid Player.opp = new Grid() private
Definition at line 10 of file Player.java.
Referenced by getOpp(), printOpponentGuesses(), and recordOpponentGuess().
own
Grid Player.own = new Grid() private
Definition at line 9 of file Player.java.
Referenced by chooseShipLocation(), getOwn(), printMyGuesses(), printMyShips(), and recordOpponentGuess().
SHIP_LENGTHS
final int [] Player.SHIP_LENGTHS = { 2, 5 } static private
Definition at line 7 of file Player.java.
{ 2, 5 }; // Define SHIP_LENGTHS
Referenced by Player().
ships
Ship [] Player.ships private
Definition at line 8 of file Player.java.
Referenced by allShipsSunk(), getShips(), and Player().
The documentation for this class was generated from the following file:
src/Player.java