A5-Battleship: Grid Class Reference
Grid Class Reference
Public Member Functions
Grid ()
void printMyShips ()
void markHit (int row, int col)
void markMiss (int row, int col)
void setStatus (int row, int col, int status)
int getStatus (int row, int col)
boolean alreadyGuessed (int row, int col)
void setShip (int row, int col, boolean val)
boolean hasShip (int row, int col)
Location get (int row, int col)
int numRows ()
int numCols ()
void printStatus ()
void printShips ()
void addShip (Ship s)
Static Public Attributes
static final int NUM_ROWS = 10
static final int NUM_COLS = 10
Private Attributes
Location[][] grid
Detailed Description
Definition at line 1 of file Grid.java.
Constructor & Destructor Documentation
Grid()
Grid.Grid ()
Definition at line 10 of file Grid.java.
                  {
        grid = new Location[NUM_COLS][NUM_ROWS];
        for (int y = 0; y < NUM_ROWS; y++) {
            for (int x = 0; x < NUM_COLS; x++) {
                grid[x][y] = new Location();
            }
        }
    }
References grid, NUM_COLS, and NUM_ROWS.
Member Function Documentation
addShip()
void Grid.addShip (Ship s)
Definition at line 157 of file Grid.java.
{
        int length = s.getLength();
        int dir = s.getDirection();
        int row = s.getRow();
        int col = s.getCol();
        if (dir == 1) {
            for (int y = row; y < (s.getLength() + row); y++) {
                setShip(y, col, true);
            }
        } else {
            for (int x = col; x < (s.getLength() + col); x++) {
                setShip(row, x, true);
            }
        }
    }
References Ship.getCol(), Ship.getDirection(), Ship.getLength(), Ship.getRow(), and setShip().
Referenced by Player.chooseShipLocation().
alreadyGuessed()
boolean Grid.alreadyGuessed (int row, int col)
Definition at line 45 of file Grid.java.
{
        return !grid[col][row].isUnguessed();
    }
References grid, and Location.isUnguessed().
get()
Location Grid.get (int row, int col)
Definition at line 60 of file Grid.java.
{
        return grid[col][row];
    }
References grid.
getStatus()
int Grid.getStatus (int row, int col)
Definition at line 40 of file Grid.java.
{
        return grid[col][row].getStatus();
    }
References Location.getStatus(), and grid.
hasShip()
boolean Grid.hasShip (int row, int col)
Definition at line 55 of file Grid.java.
{
        return grid[col][row].hasShip();
    }
References grid, and Location.hasShip.
Referenced by printShips(), and Player.recordOpponentGuess().
markHit()
void Grid.markHit (int row, int col)
Definition at line 25 of file Grid.java.
{
        grid[col][row].markHit();
    }
References grid, and Location.markHit().
Referenced by Player.recordOpponentGuess().
markMiss()
void Grid.markMiss (int row, int col)
Definition at line 30 of file Grid.java.
{
        grid[col][row].markMiss();
    }
References grid, and Location.markMiss().
Referenced by Player.recordOpponentGuess().
numCols()
int Grid.numCols ()
Definition at line 70 of file Grid.java.
{
        return NUM_COLS;
    }
References NUM_COLS.
numRows()
int Grid.numRows ()
Definition at line 65 of file Grid.java.
{
        return NUM_ROWS;
    }
References NUM_ROWS.
printMyShips()
void Grid.printMyShips ()
Definition at line 19 of file Grid.java.
{
        printShips();
    }
References printShips().
Referenced by Main.makeGuess().
printShips()
void Grid.printShips ()
Definition at line 134 of file Grid.java.
{
        String[] alpha = { "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N" };
        System.out.print("");
        for (int i = 0; i < NUM_COLS; i++) {
            if (i != 9) {
                System.out.print((i + 1) + " ");
            } else
                System.out.print(i + 1);
        }
        System.out.println("");
        for (int y = 0; y < NUM_ROWS; y++) {
            System.out.print(alpha[y] + " ");
            for (int x = 0; x < NUM_COLS; x++) {
                if (grid[x][y].hasShip()) {
                    System.out.print("X ");
                } else
                    System.out.print("- ");
            }
            System.out.println("");
        }
    }
References grid, hasShip(), NUM_COLS, and NUM_ROWS.
Referenced by printMyShips(), and Player.printMyShips().
printStatus()
void Grid.printStatus ()
Definition at line 93 of file Grid.java.
{
        String[] alpha = { "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N" };
        System.out.print("");
        for (int i = 0; i < NUM_COLS; i++) {
            if (i != 9) {
                System.out.print((i + 1) + " ");
            } else
                System.out.print(i + 1);
        }
        System.out.println("");
        for (int y = 0; y < NUM_ROWS; y++) {
            System.out.print(alpha[y] + " ");
            for (int x = 0; x < NUM_COLS; x++) {
                if (grid[x][y].checkHit()) {
                    System.out.print("X ");
                } else if (grid[x][y].checkMiss()) {
                    System.out.print("O ");
                } else
                    System.out.print("- ");
            }
            System.out.println("");
        }
    }
References grid, NUM_COLS, and NUM_ROWS.
Referenced by Main.makeGuess(), Player.printMyGuesses(), and Player.printOpponentGuesses().
setShip()
void Grid.setShip (int row, int col, boolean val)
Definition at line 50 of file Grid.java.
{
        grid[col][row].setShip(val);
    }
References grid, and Location.setShip().
Referenced by addShip().
setStatus()
void Grid.setStatus (int row, int col, int status)
Definition at line 35 of file Grid.java.
{
        grid[col][row].setStatus(status);
    }
References grid, and Location.setStatus().
Member Data Documentation
grid
Location [][] Grid.grid private
Definition at line 3 of file Grid.java.
Referenced by alreadyGuessed(), get(), getStatus(), Grid(), hasShip(), markHit(), markMiss(), printShips(), printStatus(), setShip(), and setStatus().
NUM_COLS
final int Grid.NUM_COLS = 10 static
Definition at line 6 of file Grid.java.
Referenced by Grid(), numCols(), printShips(), and printStatus().
NUM_ROWS
final int Grid.NUM_ROWS = 10 static
Definition at line 5 of file Grid.java.
Referenced by Grid(), numRows(), printShips(), and printStatus().
The documentation for this class was generated from the following file:
src/Grid.java