B1-Baseball: Main Class Reference
Main Class Reference
Static Public Member Functions
static void main (String[] args)
Detailed Description
Definition at line 8 of file Main.java.
Member Function Documentation
main()
static void Main.main (String[] args) static
Definition at line 9 of file Main.java.
{
        // create the batters and pitcher for each team
        Batter homeBat1 = new Batter("Hal Jordan");
        Batter homeBat2 = new Batter("John Stewart");
        Batter homeBat3 = new Batter("Guy Gardener");
        Batter homeBat4 = new Batter("Kyle Rainer");
        Batter homeBat5 = new Batter("Simon Baz");
        Batter homeBat6 = new Batter("Jessica Cruz");
        Batter homeBat7 = new Batter("Ch'p");
        Batter homeBat8 = new Batter("Killowog");
        Batter homeBat9 = new Batter("Mogo");
        Batter awayBat1 = new Batter("Bruce Wayne");
        Batter awayBat2 = new Batter("Richard Grayson");
        Batter awayBat3 = new Batter("Jayson Todd");
        Batter awayBat4 = new Batter("Damien Wayne");
        Batter awayBat5 = new Batter("Alfred Pennyworth");
        Batter awayBat6 = new Batter("Bette Kane");
        Batter awayBat7 = new Batter("Barbara Gordon");
        Batter awayBat8 = new Batter("Katherine Kane");
        Batter awayBat9 = new Batter("Selina Kyle");
        Pitcher homePitch = new Pitcher("Mogo");
        Pitcher awayPitch = new Pitcher("Alfred Pennyworth");
        // set up the team objects
        Team homeGang = new Team(homeBat1, homeBat2, homeBat3, homeBat4, homeBat5, homeBat6, homeBat7, homeBat8,
                homeBat9, homePitch, "The Coast City Angels");
        Team awayGang = new Team(awayBat1, awayBat2, awayBat3, awayBat4, awayBat5, awayBat6, awayBat7, awayBat8,
                awayBat9, awayPitch, "The Gotham Goliaths");
        Gamestate game = new Gamestate(homeGang, awayGang);
        homeGang.test();
        awayGang.test();
        // and finally declare our random number friend and random number holders
        Random rand = new Random();
        int pitchVal;
        int basesHit;
        int randFieldEventGenerator;
        // now we simulate a baseball game
        System.out.println("\n------------------\nPlay Ball!");
        // while loop will break only when the endTheGame method occurs
        while (true) {
            System.out.println("------------------");
            // top vs bottom of the inning
            if (game.getInning() % 1 == 0) {
                System.out.println("It is the top of inning " + (int) game.getInning() + ".");
            } else {
                System.out.println("It is the bottom of inning " + (int) game.getInning() + ".");
            }
            // display the current score
            if (game.getHomeScore() > game.getAwayScore()) {
                // if home team is winning
                System.out.println(game.getHomeName() + " are winning " + game.getHomeScore() + " to "
                        + game.getAwayScore() + ".");
            } else if (game.getHomeScore() == game.getAwayScore()) {
                // if game is tied
                System.out.println("The game is tied at " + game.getHomeScore() + ".");
            } else {
                // if away team is winning
                System.out.println(game.getAwayName() + " are winning " + game.getAwayScore() + " to "
                        + game.getHomeScore() + ".");
            }
            // continue with the number of outs
            if (game.getOuts() != 1) {
                System.out.print("There are " + game.getOuts() + " outs");
            } else {
                System.out.print("There is " + game.getOuts() + " out");
            }
            // as well as which bases have runners
            if (!game.isRunnerOnFirst() && !game.isRunnerOnSecond() && !game.isRunnerOnThird()) {
                System.out.println(", and the bases are empty.");
            } else if (game.isRunnerOnFirst() && !game.isRunnerOnSecond() && !game.isRunnerOnThird()) {
                System.out.println(", and there is a runner on first.");
            } else if (!game.isRunnerOnFirst() && game.isRunnerOnSecond() && !game.isRunnerOnThird()) {
                System.out.println(", and there is a runner on second.");
            } else if (!game.isRunnerOnFirst() && !game.isRunnerOnSecond() && game.isRunnerOnThird()) {
                System.out.println(", and there is a runner on third.");
            } else if (game.isRunnerOnFirst() && game.isRunnerOnSecond() && !game.isRunnerOnThird()) {
                System.out.println(", and there are runners on first and second.");
            } else if (!game.isRunnerOnFirst() && game.isRunnerOnSecond() && game.isRunnerOnThird()) {
                System.out.println(", and there are runners on second and third.");
            } else if (game.isRunnerOnFirst() && !game.isRunnerOnSecond() && game.isRunnerOnThird()) {
                System.out.println(", and there are runners on first and third.");
            } else if (game.isRunnerOnFirst() && game.isRunnerOnSecond() && game.isRunnerOnThird()) {
                System.out.println(", and the bases are loaded.");
            } else {
                System.out.println("\nDEBUG: Error with Baserunner Assignments (somehow)");
                break;
            }
            // announce the batter
            System.out.print(game.getBatter().getName() + " is up to bat: ");
            // generate a random number for the pitcher between 1 and 1000, inclusive
            // I ignored the pitcher's "getRandomValue()" method bc the value currently
            // never changes
            // & thus every pitch will (currently) be identical
            pitchVal = rand.nextInt(1001);
            // DEBUG: System.out.println("PitchVal: " + pitchVal);
            // compare to batter's batting average -- if the batting average is higher, it's
            // a hit!
            // DEBUG: System.out.println("BattingAvg: " +
            // game.getBatter().getRandomValue());
            if (game.getBatter().getRandomValue() >= pitchVal) {
                // the batter hits a single, double, triple, or home run (randomly)
                basesHit = rand.nextInt(3) + 1;
                // System.out.println("\n\nDEBUG: basesHit = " + basesHit + "\n");
                if (basesHit == 1) {
                    System.out.println("and it's a single!");
                } else if (basesHit == 2) {
                    System.out.println("and it's a double!");
                } else if (basesHit == 3) {
                    System.out.println("and it's a triple!");
                } else if (basesHit == 4) {
                    System.out.println("and it's a home run!");
                } else {
                    System.out.println("\nDEBUG: Generated invalid number of bases hit (somehow)");
                    break;
                }
                game.batterHitOrWalk(basesHit);
                // if this is ended the game (bottom of 9th and home team now winning), break
                // the big while loop
                if ((game.getInning() == 9.5) && (game.getHomeScore() > game.getAwayScore())) {
                    System.out.println("------------------");
                    break;
                }
            } else {
                // describe how the batter was caught out / struck out (it's random for variety)
                randFieldEventGenerator = rand.nextInt(9);
                if (randFieldEventGenerator == 0) {
                    System.out.println("And he swings for the changeup - strike three, he's out!");
                } else if (randFieldEventGenerator == 1) {
                    System.out.println("Pop fly to the infield... aaaaaand they're out!");
                } else if (randFieldEventGenerator == 2) {
                    System.out.println("Fastball inside catches him looking, that's strike three!");
                } else if (randFieldEventGenerator == 3) {
                    System.out.println("Line drive to deep center field, what a catch! He's out!");
                } else if (randFieldEventGenerator == 4) {
                    System.out.println("Grounder to third, there's the throw, and there's the out.");
                } else if (randFieldEventGenerator == 5) {
                    System.out.println("Fouled back off the catcher, batter goes... and he's out!");
                } else if (randFieldEventGenerator == 6) {
                    System.out.println("The pitcher gets him with the changeup, he's out!");
                } else if (randFieldEventGenerator == 7) {
                    System.out.println("Big hit, it's going, it's going... incredible catch at the wall!");
                } else if (randFieldEventGenerator == 8) {
                    System.out.println("Low and outside, but he doesn't look happy with the strike three call.");
                } else {
                    System.out.println("\nDEBUG: Random field event generated out of range");
                    break;
                }
                // System.out.println("and they're out!");
                game.callAnOut();
                // if this ended the game, break the big while loop
                if ((game.getInning() == 10.0)
                        || (game.getInning() == 9.5 && game.getHomeScore() > game.getAwayScore())) {
                    System.out.println("------------------");
                    break;
                }
                // otherwise, if this caused a change in innings
                else if (game.getOuts() == 0) {
                    // announce the change in sides
                    System.out.println("This causes a change in sides...");
                }
            }
        }
    }
References baseballsimulator.Gamestate.batterHitOrWalk(), baseballsimulator.Gamestate.callAnOut(), baseballsimulator.Gamestate.getAwayName(), baseballsimulator.Gamestate.getAwayScore(), baseballsimulator.Gamestate.getBatter(), baseballsimulator.Gamestate.getHomeName(), baseballsimulator.Gamestate.getHomeScore(), baseballsimulator.Gamestate.getInning(), baseballsimulator.Batter.getName(), baseballsimulator.Gamestate.getOuts(), baseballsimulator.Batter.getRandomValue(), baseballsimulator.Gamestate.isRunnerOnFirst(), baseballsimulator.Gamestate.isRunnerOnSecond(), baseballsimulator.Gamestate.isRunnerOnThird(), and baseballsimulator.Team.test().
The documentation for this class was generated from the following file:
src/Main.java