B1-Baseball: baseballsimulator.Team Class Reference
baseballsimulator.Team Class Reference
Public Member Functions
Team (Batter b1, Batter b2, Batter b3, Batter b4, Batter b5, Batter b6, Batter b7, Batter b8, Batter b9, Pitcher p1, String name)
Batter getCurrentBatter ()
Batter peakNextBatter ()
Batter updateBatter ()
Pitcher getPitcher ()
String getName ()
void test ()
Private Attributes
Batter[] batterList
Pitcher pitcher
String teamName
int currentPosition
Detailed Description
Definition at line 5 of file Team.java.
Constructor & Destructor Documentation
Team()
baseballsimulator.Team.Team (Batter b1, Batter b2, Batter b3, Batter b4, Batter b5, Batter b6, Batter b7, Batter b8, Batter b9, Pitcher p1, String name)
Definition at line 16 of file Team.java.
{
        batterList = new Batter[9];
        batterList[0] = b1;
        batterList[1] = b2;
        batterList[2] = b3;
        batterList[3] = b4;
        batterList[4] = b5;
        batterList[5] = b6;
        batterList[6] = b7;
        batterList[7] = b8;
        batterList[8] = b9;
        pitcher = p1;
        teamName = name;
        currentPosition = 0;
    }
References baseballsimulator.Team.batterList, baseballsimulator.Team.currentPosition, baseballsimulator.Team.pitcher, and baseballsimulator.Team.teamName.
Member Function Documentation
getCurrentBatter()
Batter baseballsimulator.Team.getCurrentBatter ()
Definition at line 35 of file Team.java.
{
        return batterList[currentPosition];
    }
References baseballsimulator.Team.batterList, and baseballsimulator.Team.currentPosition.
Referenced by baseballsimulator.Gamestate.getBatter().
getName()
String baseballsimulator.Team.getName ()
Definition at line 66 of file Team.java.
{
        return teamName;
    }
References baseballsimulator.Team.teamName.
Referenced by baseballsimulator.Gamestate.getAwayName(), baseballsimulator.Gamestate.getHomeName(), and baseballsimulator.Team.test().
getPitcher()
Pitcher baseballsimulator.Team.getPitcher ()
Definition at line 60 of file Team.java.
{
        return pitcher;
    }
References baseballsimulator.Team.pitcher.
Referenced by baseballsimulator.Gamestate.getPitcher().
peakNextBatter()
Batter baseballsimulator.Team.peakNextBatter ()
Definition at line 41 of file Team.java.
{
        return batterList[currentPosition + 1];
    }
References baseballsimulator.Team.batterList, and baseballsimulator.Team.currentPosition.
test()
void baseballsimulator.Team.test ()
Definition at line 72 of file Team.java.
                       {
        System.out.println("Team name: " + teamName);
        System.out.println("Pitcher: " + pitcher.getName());
        System.out.println("Team roster: ");
        for (int i = 0; i < batterList.length; i++) {
            System.out.print(batterList[i].getName() + " ");
        }
        System.out.println("");
    }
References baseballsimulator.Team.batterList, baseballsimulator.Pitcher.getName(), baseballsimulator.Team.getName(), baseballsimulator.Team.pitcher, and baseballsimulator.Team.teamName.
Referenced by Main.main().
updateBatter()
Batter baseballsimulator.Team.updateBatter ()
Definition at line 49 of file Team.java.
{
        if (currentPosition + 1 > 8) {
            currentPosition = 0;
        } else {
            currentPosition++;
        }
        return batterList[currentPosition];
    }
References baseballsimulator.Team.batterList, and baseballsimulator.Team.currentPosition.
Referenced by baseballsimulator.Gamestate.batterHitOrWalk(), and baseballsimulator.Gamestate.callAnOut().
Member Data Documentation
batterList
Batter [] baseballsimulator.Team.batterList private
Definition at line 6 of file Team.java.
Referenced by baseballsimulator.Team.getCurrentBatter(), baseballsimulator.Team.peakNextBatter(), baseballsimulator.Team.Team(), baseballsimulator.Team.test(), and baseballsimulator.Team.updateBatter().
currentPosition
int baseballsimulator.Team.currentPosition private
Definition at line 9 of file Team.java.
Referenced by baseballsimulator.Team.getCurrentBatter(), baseballsimulator.Team.peakNextBatter(), baseballsimulator.Team.Team(), and baseballsimulator.Team.updateBatter().
pitcher
Pitcher baseballsimulator.Team.pitcher private
Definition at line 7 of file Team.java.
Referenced by baseballsimulator.Team.getPitcher(), baseballsimulator.Team.Team(), and baseballsimulator.Team.test().
teamName
String baseballsimulator.Team.teamName private
Definition at line 8 of file Team.java.
Referenced by baseballsimulator.Team.getName(), baseballsimulator.Team.Team(), and baseballsimulator.Team.test().
The documentation for this class was generated from the following file:
src/baseballsimulator/Team.java