A1-Blackjack: TipDisplay Class Reference
TipDisplay Class Reference
Static Public Member Functions
static void displayRandomStrategy ()
Static Private Attributes
static final BlackjackStrategy[] blackjackStrategies = { new Hit21Strategy(), }
static final RandomStrategy randomStrategy = new RandomStrategy(blackjackStrategies)
Detailed Description
Definition at line 3 of file TipDisplay.java.
Member Function Documentation
displayRandomStrategy()
static void TipDisplay.displayRandomStrategy () static
Definition at line 9 of file TipDisplay.java.
{
        if (BlackJackSimu.simpleOutcomes()) {
            return;
        }
        int totalValue = BlackJackSimu.playerCards.getTotalValue();
        String strategy = randomStrategy.getStrategy(totalValue);
        JOptionPane.showMessageDialog(BlackJackSimu.frame, strategy, "Blackjack Strategy",
                JOptionPane.INFORMATION_MESSAGE);
    }
References BlackJackSimu.frame, BlackJackSimu.playerCards, randomStrategy, and BlackJackSimu.simpleOutcomes().
Referenced by BlackJackSimu.initGuiObjects().
Member Data Documentation
blackjackStrategies
final BlackjackStrategy [] TipDisplay.blackjackStrategies = { new Hit21Strategy(), } static private
Definition at line 5 of file TipDisplay.java.
{ new Hit21Strategy(), };
randomStrategy
final RandomStrategy TipDisplay.randomStrategy = new RandomStrategy(blackjackStrategies) static private
Definition at line 7 of file TipDisplay.java.
Referenced by displayRandomStrategy().
The documentation for this class was generated from the following file:
src/TipDisplay.java