A1-Blackjack: BlackJackSimu Class Reference
BlackJackSimu Class Reference
Static Public Member Functions
static boolean isValidAmount (String s)
static void initGuiObjects ()
static void showBetGui ()
static void deal ()
static void hit ()
static boolean simpleOutcomes ()
static void stand ()
static void outcomeHappened ()
static void acceptOutcome ()
static void newGame ()
static void updateCardPanels ()
static void main (String[] args)
Static Public Member Functions inherited from TipDisplay
static void displayRandomStrategy ()
Static Public Attributes
static final JFrame frame = new MainFrame()
static StandardDeck deck
static StandardDeck playerCards
Static Private Attributes
static JTextField tfBalance
static JButton btnNewGame
static JButton btnEndGame
static JTextField tfBetAmount
static JButton btnDeal
static JLabel lblBalanceAmount
static JLabel lblDealer
static JLabel lblPlayer
static JButton btnHit
static JButton btnStand
static JLabel lblBetAmount
static JLabel lblBetAmountDesc
static JLabel lblInfo
static JButton btnContinue
static JLabel lblShuffleInfo = null
static StandardDeck dealerCards
static DeckPanel dealerCardPanel = null
static DeckPanel playerCardPanel = null
static Card dealerHiddenCard
static double balance = 0.0
static int betAmount = 0
static int roundCount = 0
Detailed Description
Definition at line 7 of file BlackJackSimu.java.
Member Function Documentation
acceptOutcome()
static void BlackJackSimu.acceptOutcome () static
Definition at line 309 of file BlackJackSimu.java.
{
        lblInfo.setOpaque(false);
        lblInfo.setForeground(Color.ORANGE);
        frame.getContentPane().remove(lblDealer);
        frame.getContentPane().remove(lblPlayer);
        frame.getContentPane().remove(btnHit);
        frame.getContentPane().remove(btnStand);
        frame.getContentPane().remove(lblBetAmount);
        frame.getContentPane().remove(lblBetAmountDesc);
        frame.getContentPane().remove(btnContinue);
        frame.getContentPane().remove(dealerCardPanel);
        frame.getContentPane().remove(playerCardPanel);
        lblInfo.setText("Please enter a bet and click Deal");
        tfBetAmount.setEnabled(true);
        btnDeal.setEnabled(true);
        btnDeal.requestFocus();
        frame.repaint();
        if (balance <= 0) {
            int choice = JOptionPane.showOptionDialog(null,
                    "You have run out of funds. Press Yes to add $100, or No to end the current game.", "Out of funds",
                    JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);
            if (choice == JOptionPane.YES_OPTION) {
                balance += 100;
                lblBalanceAmount.setText(String.format("$%.2f", balance));
            } else {
                frame.getContentPane().removeAll();
                frame.repaint();
                initGuiObjects();
                return;
            }
        }
        roundCount++;
        if (roundCount >= 5) {
            deck.initFullDeck();
            deck.shuffle();
            lblShuffleInfo = new JLabel("Deck has been replenished and reshuffled!");
            lblShuffleInfo.setForeground(Color.ORANGE);
            lblShuffleInfo.setFont(new Font("Arial", Font.BOLD, 20));
            lblShuffleInfo.setHorizontalAlignment(SwingConstants.CENTER);
            lblShuffleInfo.setBounds(235, 307, 430, 42);
            frame.getContentPane().add(lblShuffleInfo);
            roundCount = 0;
        }
    }
References balance, btnContinue, btnDeal, btnHit, btnStand, dealerCardPanel, deck, frame, initGuiObjects(), lblBalanceAmount, lblBetAmount, lblBetAmountDesc, lblDealer, lblInfo, lblPlayer, lblShuffleInfo, playerCardPanel, roundCount, and tfBetAmount.
Referenced by deal().
deal()
static void BlackJackSimu.deal () static
Definition at line 129 of file BlackJackSimu.java.
{
        if (lblShuffleInfo != null)
            frame.getContentPane().remove(lblShuffleInfo);
        dealerCards = new StandardDeck();
        playerCards = new StandardDeck();
        if (isValidAmount(tfBetAmount.getText())) {
            betAmount = Integer.parseInt(tfBetAmount.getText());
        } else {
            lblInfo.setText("Error:Must be a Valid Bet!");
            tfBetAmount.requestFocus();
            return;
        }
        if (betAmount > balance) {
            lblInfo.setText("Error: Not Enough in Balance!");
            tfBetAmount.requestFocus();
            return;
        }
        balance -= betAmount;
        lblBalanceAmount.setText(String.format("$%.2f", balance));
        tfBetAmount.setEnabled(false);
        btnDeal.setEnabled(false);
        lblInfo.setText("Please Hit or Stand");
        lblDealer = new JLabel("Dealer");
        lblDealer.setForeground(Color.BLACK);
        lblDealer.setFont(new Font("Arial Black", Font.BOLD, 20));
        lblDealer.setBounds(415, 158, 82, 28);
        frame.getContentPane().add(lblDealer);
        lblPlayer = new JLabel("Player");
        lblPlayer.setForeground(Color.BLACK);
        lblPlayer.setFont(new Font("Arial Black", Font.BOLD, 20));
        lblPlayer.setBounds(415, 266, 82, 28);
        frame.getContentPane().add(lblPlayer);
        btnHit = new JButton("Hit");
        btnHit.setBounds(290, 515, 140, 35);
        btnHit.addActionListener(e -> hit());
        frame.getContentPane().add(btnHit);
        btnHit.requestFocus();
        btnStand = new JButton("Stand");
        btnStand.setBounds(470, 515, 140, 35);
        btnStand.addActionListener(e -> stand());
        frame.getContentPane().add(btnStand);
        btnContinue = new JButton("Continue");
        btnContinue.setEnabled(false);
        btnContinue.setVisible(false);
        btnContinue.setBounds(290, 444, 320, 35);
        btnContinue.addActionListener(e -> acceptOutcome());
        frame.getContentPane().add(btnContinue);
        lblBetAmount = new JLabel();
        lblBetAmount.setText("$" + betAmount);
        lblBetAmount.setHorizontalAlignment(SwingConstants.CENTER);
        lblBetAmount.setForeground(Color.green);
        lblBetAmount.setFont(new Font("Arial", Font.BOLD, 40));
        lblBetAmount.setBounds(679, 488, 200, 50);
        frame.getContentPane().add(lblBetAmount);
        lblBetAmountDesc = new JLabel("Bet Amount:");
        lblBetAmountDesc.setHorizontalAlignment(SwingConstants.CENTER);
        lblBetAmountDesc.setForeground(Color.WHITE);
        lblBetAmountDesc.setFont(new Font("Arial", Font.BOLD, 16));
        lblBetAmountDesc.setBounds(689, 465, 190, 22);
        frame.getContentPane().add(lblBetAmountDesc);
        frame.repaint();
        dealerHiddenCard = deck.takeCard();
        dealerCards.cards.add(new Card("", "", 0));
        dealerCards.cards.add(deck.takeCard());
        playerCards.cards.add(deck.takeCard());
        playerCards.cards.add(deck.takeCard());
        updateCardPanels();
        simpleOutcomes();
    }
References acceptOutcome(), balance, betAmount, btnContinue, btnDeal, btnHit, btnStand, Deck.cards, dealerCards, dealerHiddenCard, deck, frame, hit(), isValidAmount(), lblBalanceAmount, lblBetAmount, lblBetAmountDesc, lblDealer, lblInfo, lblPlayer, lblShuffleInfo, playerCards, simpleOutcomes(), stand(), tfBetAmount, and updateCardPanels().
Referenced by showBetGui().
hit()
static void BlackJackSimu.hit () static
Definition at line 217 of file BlackJackSimu.java.
{
        playerCards.cards.add(deck.takeCard());
        updateCardPanels();
        simpleOutcomes();
    }
References Deck.cards, deck, playerCards, simpleOutcomes(), and updateCardPanels().
Referenced by deal().
initGuiObjects()
static void BlackJackSimu.initGuiObjects () static
Definition at line 47 of file BlackJackSimu.java.
{
        btnNewGame = new JButton("Start");
        btnNewGame.addActionListener(e -> newGame());
        btnNewGame.setBounds(20, 610, 99, 50);
        frame.getContentPane().add(btnNewGame);
        btnEndGame = new JButton("Stop");
        btnEndGame.setEnabled(false);
        btnEndGame.setBounds(121, 610, 99, 50);
        btnEndGame.addActionListener(e -> {
            frame.getContentPane().removeAll();
            frame.repaint();
            initGuiObjects();
        });
        frame.getContentPane().add(btnEndGame);
        tfBalance = new JTextField();
        tfBalance.setText("100");
        tfBalance.setBounds(131, 580, 89, 28);
        frame.getContentPane().add(tfBalance);
        tfBalance.setColumns(10);
        JLabel lblInitialBalance = new JLabel("Bankroll:");
        lblInitialBalance.setFont(new Font("Helvetica", Font.BOLD, 13));
        lblInitialBalance.setForeground(Color.WHITE);
        lblInitialBalance.setBounds(30, 586, 100, 16);
        frame.getContentPane().add(lblInitialBalance);
        // Help Button
        JButton btnHelp = new JButton("Help");
        btnHelp.setBounds(230, 610, 99, 50);
        btnHelp.addActionListener(e -> displayRandomStrategy());
        frame.getContentPane().add(btnHelp);
    }
References btnEndGame, btnNewGame, TipDisplay.displayRandomStrategy(), frame, initGuiObjects(), newGame(), and tfBalance.
Referenced by acceptOutcome(), initGuiObjects(), and main().
isValidAmount()
static boolean BlackJackSimu.isValidAmount (String s) static
Definition at line 35 of file BlackJackSimu.java.
{
        try {
            // Ensure amount entered is > 0
            return Integer.parseInt(s) > 0;
        } catch (NumberFormatException e) {
            // If not a valid integer
            return false;
        }
    }
Referenced by deal(), and newGame().
main()
static void BlackJackSimu.main (String[] args) static
Definition at line 395 of file BlackJackSimu.java.
{
        initGuiObjects();
        frame.setVisible(true);
    }
References frame, and initGuiObjects().
newGame()
static void BlackJackSimu.newGame () static
Definition at line 360 of file BlackJackSimu.java.
{
        if (isValidAmount(tfBalance.getText())) {
            balance = Integer.parseInt(tfBalance.getText());
        } else {
            JOptionPane.showMessageDialog(frame, "Invalid balance! Please ensure it is a natural number.", "Error",
                    JOptionPane.ERROR_MESSAGE);
            tfBalance.requestFocus();
            return;
        }
        btnNewGame.setEnabled(false);
        tfBalance.setEnabled(false);
        showBetGui();
        roundCount = 0;
        deck = new StandardDeck();
        deck.initFullDeck();
        deck.shuffle();
    }
References balance, btnNewGame, deck, frame, isValidAmount(), roundCount, showBetGui(), and tfBalance.
Referenced by initGuiObjects().
outcomeHappened()
static void BlackJackSimu.outcomeHappened () static
Definition at line 293 of file BlackJackSimu.java.
{
        btnHit.setEnabled(false);
        btnStand.setEnabled(false);
        lblInfo.setOpaque(true);
        lblInfo.setForeground(Color.RED);
        new Timer().schedule(new TimerTask() {
            @Override
            public void run() {
                btnContinue.setEnabled(true);
                btnContinue.setVisible(true);
                btnContinue.requestFocus();
            }
        }, 500);
    }
References btnContinue, btnHit, btnStand, and lblInfo.
Referenced by simpleOutcomes(), and stand().
showBetGui()
static void BlackJackSimu.showBetGui () static
Definition at line 82 of file BlackJackSimu.java.
{
        btnEndGame.setEnabled(true);
        JLabel lblCurrentBalance = new JLabel("Current Balance:");
        lblCurrentBalance.setHorizontalAlignment(SwingConstants.CENTER);
        lblCurrentBalance.setFont(new Font("Helvetica", Font.BOLD, 16));
        lblCurrentBalance.setForeground(Color.WHITE);
        lblCurrentBalance.setBounds(315, 578, 272, 22);
        frame.getContentPane().add(lblCurrentBalance);
        lblBalanceAmount = new JLabel();
        lblBalanceAmount.setText(String.format("$%.2f", balance));
        lblBalanceAmount.setForeground(Color.ORANGE);
        lblBalanceAmount.setFont(new Font("Arial", Font.BOLD, 40));
        lblBalanceAmount.setHorizontalAlignment(SwingConstants.CENTER);
        lblBalanceAmount.setBounds(315, 600, 272, 50);
        frame.getContentPane().add(lblBalanceAmount);
        lblInfo = new JLabel("Enter a bet and click Deal");
        lblInfo.setBackground(Color.ORANGE);
        lblInfo.setOpaque(false);
        lblInfo.setForeground(Color.ORANGE);
        lblInfo.setFont(new Font("Arial", Font.BOLD, 16));
        lblInfo.setHorizontalAlignment(SwingConstants.CENTER);
        lblInfo.setBounds(290, 482, 320, 28);
        frame.getContentPane().add(lblInfo);
        tfBetAmount = new JTextField();
        tfBetAmount.setText("10");
        tfBetAmount.setBounds(790, 580, 89, 28);
        frame.getContentPane().add(tfBetAmount);
        JLabel lblEnterBet = new JLabel("Enter Bet:");
        lblEnterBet.setFont(new Font("Arial", Font.BOLD, 14));
        lblEnterBet.setForeground(Color.WHITE);
        lblEnterBet.setBounds(689, 586, 100, 16);
        frame.getContentPane().add(lblEnterBet);
        btnDeal = new JButton("Deal");
        btnDeal.setBounds(679, 610, 200, 50);
        btnDeal.addActionListener(e -> deal());
        frame.getContentPane().add(btnDeal);
        btnDeal.requestFocus();
        frame.repaint();
    }
References balance, btnDeal, btnEndGame, deal(), frame, lblBalanceAmount, lblInfo, and tfBetAmount.
Referenced by newGame().
simpleOutcomes()
static boolean BlackJackSimu.simpleOutcomes () static
Definition at line 224 of file BlackJackSimu.java.
{
        boolean outcomeHasHappened = false;
        int playerScore = playerCards.getTotalValue();
        if (playerScore > 21 && playerCards.getNumAces() > 0)
            playerScore -= 10;
        if (playerScore == 21) {
            dealerCards.cards.set(0, dealerHiddenCard);
            updateCardPanels();
            if (dealerCards.getTotalValue() == 21) {
                lblInfo.setText("Push!");
                balance += betAmount;
            } else {
                lblInfo.setText(String.format("Player gets Blackjack! Profit: $%.2f", 1.5f * betAmount));
                balance += 2.5f * betAmount;
            }
            lblBalanceAmount.setText(String.format("$%.2f", balance));
            outcomeHasHappened = true;
            outcomeHappened();
        } else if (playerScore > 21) {
            lblInfo.setText("Player goes Bust! Loss: $" + betAmount);
            dealerCards.cards.set(0, dealerHiddenCard);
            updateCardPanels();
            outcomeHasHappened = true;
            outcomeHappened();
        }
        return outcomeHasHappened;
    }
References balance, betAmount, Deck.cards, dealerCards, dealerHiddenCard, lblBalanceAmount, lblInfo, outcomeHappened(), playerCards, and updateCardPanels().
Referenced by deal(), TipDisplay.displayRandomStrategy(), hit(), and stand().
stand()
static void BlackJackSimu.stand () static
Definition at line 253 of file BlackJackSimu.java.
{
        if (simpleOutcomes())
            return;
        int playerScore = playerCards.getTotalValue();
        if (playerScore > 21 && playerCards.getNumAces() > 0)
            playerScore -= 10;
        dealerCards.cards.set(0, dealerHiddenCard);
        int dealerScore = dealerCards.getTotalValue();
        while (dealerScore < 16) {
            dealerCards.cards.add(deck.takeCard());
            dealerScore = dealerCards.getTotalValue();
            if (dealerScore > 21 && dealerCards.getNumAces() > 0)
                dealerScore -= 10;
        }
        updateCardPanels();
        if (playerScore > dealerScore) {
            lblInfo.setText("Player wins! Profit: $" + betAmount);
            balance += betAmount * 2;
            lblBalanceAmount.setText(String.format("$%.2f", balance));
        } else if (dealerScore == 21) {
            lblInfo.setText("Dealer gets Blackjack! Loss: $" + betAmount);
        } else if (dealerScore > 21) {
            lblInfo.setText("Dealer goes Bust! Profit: $" + betAmount);
            balance += betAmount * 2;
            lblBalanceAmount.setText(String.format("$%.2f", balance));
        } else if (playerScore == dealerScore) {
            lblInfo.setText("Push!");
            balance += betAmount;
            lblBalanceAmount.setText(String.format("$%.2f", balance));
        } else {
            lblInfo.setText("Dealer Wins! Loss: $" + betAmount);
        }
        outcomeHappened();
    }
References balance, betAmount, Deck.cards, dealerCards, dealerHiddenCard, deck, lblBalanceAmount, lblInfo, outcomeHappened(), playerCards, simpleOutcomes(), and updateCardPanels().
Referenced by deal().
updateCardPanels()
static void BlackJackSimu.updateCardPanels () static
Definition at line 382 of file BlackJackSimu.java.
{
        if (dealerCardPanel != null) {
            frame.getContentPane().remove(dealerCardPanel);
            frame.getContentPane().remove(playerCardPanel);
        }
        dealerCardPanel = new DeckPanel(dealerCards, 420 - (dealerCards.getCount() * 40), 50, 70, 104, 10);
        frame.getContentPane().add(dealerCardPanel);
        playerCardPanel = new DeckPanel(playerCards, 420 - (playerCards.getCount() * 40), 300, 70, 104, 10);
        frame.getContentPane().add(playerCardPanel);
        frame.repaint();
    }
References dealerCardPanel, dealerCards, frame, playerCardPanel, and playerCards.
Referenced by deal(), hit(), simpleOutcomes(), and stand().
Member Data Documentation
balance
double BlackJackSimu.balance = 0.0 static private
Definition at line 32 of file BlackJackSimu.java.
Referenced by acceptOutcome(), deal(), newGame(), showBetGui(), simpleOutcomes(), and stand().
betAmount
int BlackJackSimu.betAmount = 0 static private
Definition at line 33 of file BlackJackSimu.java.
Referenced by deal(), simpleOutcomes(), and stand().
btnContinue
JButton BlackJackSimu.btnContinue static private
Definition at line 23 of file BlackJackSimu.java.
Referenced by acceptOutcome(), deal(), and outcomeHappened().
btnDeal
JButton BlackJackSimu.btnDeal static private
Definition at line 14 of file BlackJackSimu.java.
Referenced by acceptOutcome(), deal(), and showBetGui().
btnEndGame
JButton BlackJackSimu.btnEndGame static private
Definition at line 12 of file BlackJackSimu.java.
Referenced by initGuiObjects(), and showBetGui().
btnHit
JButton BlackJackSimu.btnHit static private
Definition at line 18 of file BlackJackSimu.java.
Referenced by acceptOutcome(), deal(), and outcomeHappened().
btnNewGame
JButton BlackJackSimu.btnNewGame static private
Definition at line 11 of file BlackJackSimu.java.
Referenced by initGuiObjects(), and newGame().
btnStand
JButton BlackJackSimu.btnStand static private
Definition at line 19 of file BlackJackSimu.java.
Referenced by acceptOutcome(), deal(), and outcomeHappened().
dealerCardPanel
DeckPanel BlackJackSimu.dealerCardPanel = null static private
Definition at line 30 of file BlackJackSimu.java.
Referenced by acceptOutcome(), and updateCardPanels().
dealerCards
StandardDeck BlackJackSimu.dealerCards static private
Definition at line 28 of file BlackJackSimu.java.
Referenced by deal(), simpleOutcomes(), stand(), and updateCardPanels().
dealerHiddenCard
Card BlackJackSimu.dealerHiddenCard static private
Definition at line 31 of file BlackJackSimu.java.
Referenced by deal(), simpleOutcomes(), and stand().
deck
StandardDeck BlackJackSimu.deck static
Definition at line 27 of file BlackJackSimu.java.
Referenced by acceptOutcome(), deal(), hit(), newGame(), and stand().
frame
final JFrame BlackJackSimu.frame = new MainFrame() static
Definition at line 9 of file BlackJackSimu.java.
Referenced by acceptOutcome(), deal(), TipDisplay.displayRandomStrategy(), initGuiObjects(), main(), newGame(), showBetGui(), and updateCardPanels().
lblBalanceAmount
JLabel BlackJackSimu.lblBalanceAmount static private
Definition at line 15 of file BlackJackSimu.java.
Referenced by acceptOutcome(), deal(), showBetGui(), simpleOutcomes(), and stand().
lblBetAmount
JLabel BlackJackSimu.lblBetAmount static private
Definition at line 20 of file BlackJackSimu.java.
Referenced by acceptOutcome(), and deal().
lblBetAmountDesc
JLabel BlackJackSimu.lblBetAmountDesc static private
Definition at line 21 of file BlackJackSimu.java.
Referenced by acceptOutcome(), and deal().
lblDealer
JLabel BlackJackSimu.lblDealer static private
Definition at line 16 of file BlackJackSimu.java.
Referenced by acceptOutcome(), and deal().
lblInfo
JLabel BlackJackSimu.lblInfo static private
Definition at line 22 of file BlackJackSimu.java.
Referenced by acceptOutcome(), deal(), outcomeHappened(), showBetGui(), simpleOutcomes(), and stand().
lblPlayer
JLabel BlackJackSimu.lblPlayer static private
Definition at line 17 of file BlackJackSimu.java.
Referenced by acceptOutcome(), and deal().
lblShuffleInfo
JLabel BlackJackSimu.lblShuffleInfo = null static private
Definition at line 24 of file BlackJackSimu.java.
Referenced by acceptOutcome(), and deal().
playerCardPanel
DeckPanel BlackJackSimu.playerCardPanel = null static private
Definition at line 30 of file BlackJackSimu.java.
Referenced by acceptOutcome(), and updateCardPanels().
playerCards
StandardDeck BlackJackSimu.playerCards static
Definition at line 29 of file BlackJackSimu.java.
Referenced by deal(), TipDisplay.displayRandomStrategy(), hit(), simpleOutcomes(), stand(), and updateCardPanels().
roundCount
int BlackJackSimu.roundCount = 0 static private
Definition at line 33 of file BlackJackSimu.java.
Referenced by acceptOutcome(), and newGame().
tfBalance
JTextField BlackJackSimu.tfBalance static private
Definition at line 10 of file BlackJackSimu.java.
Referenced by initGuiObjects(), and newGame().
tfBetAmount
JTextField BlackJackSimu.tfBetAmount static private
Definition at line 13 of file BlackJackSimu.java.
Referenced by acceptOutcome(), deal(), and showBetGui().
The documentation for this class was generated from the following file:
src/BlackJackSimu.java