A3-ConvenienceStore: src.classes.customers.HungryCustomer Class Reference
src.classes.customers.HungryCustomer Class Reference
Public Member Functions
void shop (Inventory inventory)
Private Member Functions
void buyFromShelf (Inventory inventory, Shelf shelf, int amount)
Private Attributes
ItemManager.ItemType itemPreference = ItemManager.ItemType.Food
ArrayList< Shelf > interestedShelves = new ArrayList<Shelf>()
Detailed Description
Definition at line 11 of file HungryCustomer.java.
Member Function Documentation
buyFromShelf()
void src.classes.customers.HungryCustomer.buyFromShelf (Inventory inventory, Shelf shelf, int amount) private
Definition at line 49 of file HungryCustomer.java.
{
        System.out.println(String.format("Hungry Customer bought %s %s for $%s", amount, shelf.getItem().getName(),
                shelf.getItem().getSellPrice() * amount));
        // Remove the stock from the shelf
        shelf.removeStock(amount);
        // Add the money to the Inventory's balance
        inventory.addBalance(shelf.getItem().getSellPrice() * amount);
    }
References src.classes.Inventory.addBalance().
Referenced by src.classes.customers.HungryCustomer.shop().
shop()
void src.classes.customers.HungryCustomer.shop (Inventory inventory)
Implements src.classes.interfaces.Customer.
Definition at line 16 of file HungryCustomer.java.
{
        for (Shelf shelf : inventory.getShelves()) {
            if (shelf.getItem().getItemType() == itemPreference) {
                interestedShelves.add(shelf);
            }
        }
        if (interestedShelves.isEmpty()) {
            System.out.println("Customer could not find what they were interested in.");
            return;
        } else {
            Random random = new Random();
            // Randomly choose a shelf with an item that they are interested in
            Shelf chosenShelf = interestedShelves.get(random.nextInt(interestedShelves.size()));
            if (chosenShelf.getStock() == 0) {
                System.out.println("The shelf the customer wanted to buy from was empty.");
                return;
            } else {
                // Randomly determine how many to buy
                int purchaseQuantity;
                if (chosenShelf.getStock() > 1) {
                    purchaseQuantity = random.nextInt(chosenShelf.getStock() / 2) + 1;
                } else {
                    purchaseQuantity = 1;
                }
                buyFromShelf(inventory, chosenShelf, purchaseQuantity);
            }
        }
    }
References src.classes.customers.HungryCustomer.buyFromShelf(), src.classes.Inventory.getShelves(), src.classes.customers.HungryCustomer.interestedShelves, and src.classes.customers.HungryCustomer.itemPreference.
Member Data Documentation
interestedShelves
ArrayList<Shelf> src.classes.customers.HungryCustomer.interestedShelves = new ArrayList<Shelf>() private
Definition at line 14 of file HungryCustomer.java.
Referenced by src.classes.customers.HungryCustomer.shop().
itemPreference
ItemManager.ItemType src.classes.customers.HungryCustomer.itemPreference = ItemManager.ItemType.Food private
Definition at line 13 of file HungryCustomer.java.
Referenced by src.classes.customers.HungryCustomer.shop().
The documentation for this class was generated from the following file:
src/src/classes/customers/HungryCustomer.java