A3-ConvenienceStore: src.classes.customers.StandardCustomer Class Reference
src.classes.customers.StandardCustomer Class Reference
Public Member Functions
void shop (Inventory inventory)
Private Member Functions
void buyFromShelf (Inventory inventory, Shelf shelf, int amount)
Detailed Description
Definition at line 9 of file StandardCustomer.java.
Member Function Documentation
buyFromShelf()
void src.classes.customers.StandardCustomer.buyFromShelf (Inventory inventory, Shelf shelf, int amount) private
Definition at line 39 of file StandardCustomer.java.
{
        System.out.println(String.format("Customer bought %s %s for $%s", amount, shelf.getItem().getName(),
                shelf.getItem().getSellPrice() * amount));
        // Remove the stock from the shelf
        shelf.removeStock(amount);
        // Add the money to the Inventory's balance
        inventory.addBalance(shelf.getItem().getSellPrice() * amount);
    }
References src.classes.Inventory.addBalance().
Referenced by src.classes.customers.StandardCustomer.shop().
shop()
void src.classes.customers.StandardCustomer.shop (Inventory inventory)
Implements src.classes.interfaces.Customer.
Definition at line 11 of file StandardCustomer.java.
{
        if (inventory.getShelves().isEmpty()) {
            System.out.println("Customer could not find what they were interested in.");
            return;
        } else {
            Random random = new Random();
            // Randomly choose a shelf with an item that they are interested in
            Shelf chosenShelf = inventory.getShelves().get(random.nextInt(inventory.getShelves().size()));
            if (chosenShelf.getStock() == 0) {
                System.out.println("The shelf the customer wanted to buy from was empty.");
                return;
            } else {
                // Randomly determine how many to buy
                int purchaseQuantity;
                if (chosenShelf.getStock() > 1) {
                    purchaseQuantity = random.nextInt(chosenShelf.getStock() / 2) + 1;
                } else {
                    purchaseQuantity = 1;
                }
                buyFromShelf(inventory, chosenShelf, purchaseQuantity);
            }
        }
    }
References src.classes.customers.StandardCustomer.buyFromShelf(), and src.classes.Inventory.getShelves().
The documentation for this class was generated from the following file:
src/src/classes/customers/StandardCustomer.java