A3-ConvenienceStore: src.classes.ItemManager Class Reference
src.classes.ItemManager Class Reference
Classes
enum ItemType
Public Member Functions
ItemManager (File jsonFile)
ArrayList< Item > getItems ()
ArrayList< Item > getFoodItems ()
ArrayList< Item > getDrinkItems ()
ArrayList< Item > getMiscellaneousItems ()
void printItems ()
Public Attributes
Dictionary< ItemType, ArrayList< Item > > itemArrays = new Hashtable<>()
Private Member Functions
ArrayList< Item > getJSONItems (File jsonFile)
Item getItemFromJSONObject (JSONObject object)
Private Attributes
ArrayList< Item > items = new ArrayList<Item>()
ArrayList< Item > foodItems = new ArrayList<Item>()
ArrayList< Item > drinkItems = new ArrayList<Item>()
ArrayList< Item > miscellaneousItems = new ArrayList<Item>()
Detailed Description
Definition at line 13 of file ItemManager.java.
Constructor & Destructor Documentation
ItemManager()
src.classes.ItemManager.ItemManager (File jsonFile)
Definition at line 25 of file ItemManager.java.
{
        items = getJSONItems(jsonFile);
        // Init hashtable
        itemArrays.put(ItemType.Food, foodItems);
        itemArrays.put(ItemType.Drink, drinkItems);
        itemArrays.put(ItemType.Miscellaneous, miscellaneousItems);
        // Init all specific item type arrays
        for (ItemType type : ItemType.values()) {
            for (Item item : items) {
                if (item.getItemType() == type) {
                    itemArrays.get(type).add(item);
                }
            }
        }
    }
References src.classes.ItemManager.ItemType.Drink, src.classes.ItemManager.drinkItems, src.classes.ItemManager.ItemType.Food, src.classes.ItemManager.foodItems, src.classes.ItemManager.getJSONItems(), src.classes.ItemManager.itemArrays, src.classes.ItemManager.items, src.classes.ItemManager.ItemType.Miscellaneous, and src.classes.ItemManager.miscellaneousItems.
Member Function Documentation
getDrinkItems()
ArrayList< Item > src.classes.ItemManager.getDrinkItems ()
Definition at line 51 of file ItemManager.java.
{
        return drinkItems;
    }
References src.classes.ItemManager.drinkItems.
getFoodItems()
ArrayList< Item > src.classes.ItemManager.getFoodItems ()
Definition at line 47 of file ItemManager.java.
{
        return foodItems;
    }
References src.classes.ItemManager.foodItems.
getItemFromJSONObject()
Item src.classes.ItemManager.getItemFromJSONObject (JSONObject object) private
Definition at line 82 of file ItemManager.java.
{
        ItemType itemType;
        switch (object.getString("itemType")) {
        case "Drink":
            itemType = ItemType.Drink;
            break;
        case "Food":
            itemType = ItemType.Food;
            break;
        case "Miscellaneous":
            itemType = ItemType.Miscellaneous;
            break;
        default:
            System.err.println("Error: Improper item type. Defaulting to Miscellaneous.");
            itemType = ItemType.Miscellaneous;
            break;
        }
        return new Item(object.getString("name"), object.getFloat("sellPrice"), itemType);
    }
References src.classes.ItemManager.ItemType.Drink, src.classes.ItemManager.ItemType.Food, and src.classes.ItemManager.ItemType.Miscellaneous.
Referenced by src.classes.ItemManager.getJSONItems().
getItems()
ArrayList< Item > src.classes.ItemManager.getItems ()
Definition at line 43 of file ItemManager.java.
{
        return items;
    }
References src.classes.ItemManager.items.
getJSONItems()
ArrayList< Item > src.classes.ItemManager.getJSONItems (File jsonFile) private
Definition at line 59 of file ItemManager.java.
{
        try {
            ArrayList<Item> donorList = new ArrayList<Item>();
            Reader reader = new FileReader(jsonFile);
            JSONArray jsonArray = new JSONArray(new JSONTokener(reader));
            for (int i = 0; i < jsonArray.length(); i++) {
                Item item = getItemFromJSONObject(jsonArray.getJSONObject(i));
                donorList.add(item);
            }
            return donorList;
        } catch (FileNotFoundException e) {
            System.err.println("Error: JSON file not found.");
        }
        return null;
    }
References src.classes.ItemManager.getItemFromJSONObject().
Referenced by src.classes.ItemManager.ItemManager().
getMiscellaneousItems()
ArrayList< Item > src.classes.ItemManager.getMiscellaneousItems ()
Definition at line 55 of file ItemManager.java.
{
        return miscellaneousItems;
    }
References src.classes.ItemManager.miscellaneousItems.
printItems()
void src.classes.ItemManager.printItems ()
Definition at line 109 of file ItemManager.java.
{
        for (int i = 0; i < items.size(); i++) {
            System.out.println(String.format("%s, %s, %s", items.get(i).getName(), items.get(i).getItemType(), i));
        }
    }
References src.classes.ItemManager.items.
Member Data Documentation
drinkItems
ArrayList<Item> src.classes.ItemManager.drinkItems = new ArrayList<Item>() private
Definition at line 16 of file ItemManager.java.
Referenced by src.classes.ItemManager.getDrinkItems(), and src.classes.ItemManager.ItemManager().
foodItems
ArrayList<Item> src.classes.ItemManager.foodItems = new ArrayList<Item>() private
Definition at line 15 of file ItemManager.java.
Referenced by src.classes.ItemManager.getFoodItems(), and src.classes.ItemManager.ItemManager().
itemArrays
Dictionary<ItemType, ArrayList<Item> > src.classes.ItemManager.itemArrays = new Hashtable<>()
Definition at line 23 of file ItemManager.java.
Referenced by src.classes.ItemManager.ItemManager().
items
ArrayList<Item> src.classes.ItemManager.items = new ArrayList<Item>() private
Definition at line 14 of file ItemManager.java.
Referenced by src.classes.ItemManager.getItems(), src.classes.ItemManager.ItemManager(), and src.classes.ItemManager.printItems().
miscellaneousItems
ArrayList<Item> src.classes.ItemManager.miscellaneousItems = new ArrayList<Item>() private
Definition at line 17 of file ItemManager.java.
Referenced by src.classes.ItemManager.getMiscellaneousItems(), and src.classes.ItemManager.ItemManager().
The documentation for this class was generated from the following file:
src/src/classes/ItemManager.java