A3-ConvenienceStore: src.Store Class Reference
src.Store Class Reference
Static Public Member Functions
static void main (String[] args)
Static Private Member Functions
static void initStore (Scanner input)
static void beginDay ()
static void endDay (Scanner input)
static ArrayList< Customer > generateCustomers ()
Static Private Attributes
static final File JSON_FILE = new File("json/items.json")
static final int DAY_LIMIT = 7
static final int STARTING_SHELF_CAPACITY = 10
static final int SHELF_DEFAULT_MAX_STOCK = 25
static final int SHELF_DEFAULT_INITIAL_STOCK = SHELF_DEFAULT_MAX_STOCK / 2
static final float STARTING_BALANCE = 100.00f
static Inventory inventory
static ItemManager itemManager
static ArrayList< Customer > customers = new ArrayList<Customer>()
static int customersPerDay
static int currentDay
Detailed Description
Definition at line 17 of file Store.java.
Member Function Documentation
beginDay()
static void src.Store.beginDay () static private
Definition at line 127 of file Store.java.
{
        // Increment current day
        currentDay++;
        System.out.println(String.format("Day %s Started - Balance $%s", currentDay, inventory.getBalance()));
        customersPerDay = inventory.getSize() * 2;
        customers.addAll(generateCustomers());
        for (Customer customer : customers) {
            customer.shop(inventory);
        }
        customers.clear();
    }
References src.Store.currentDay, src.Store.customers, src.Store.customersPerDay, src.Store.generateCustomers(), and src.Store.inventory.
Referenced by src.Store.main().
endDay()
static void src.Store.endDay (Scanner input) static private
Definition at line 143 of file Store.java.
{
        System.out.println(String.format("Day %s Ended - New Balance: $%s", currentDay, inventory.getBalance()));
        System.out.println("===============");
        System.out.print("Do you want to restock a shelf? (Y/N) ");
        String response = input.nextLine();
        if (response.equals("Y")) {
            // Loop through inventory and print all shelves
            for (int i = 0; i < inventory.getSize(); i++) {
                System.out.println(String.format("Shelf Index: %s", i));
                System.out.println(inventory.getShelves().get(i).toString());
                System.out.println("===========");
            }
            System.out.print("Which shelf do you want to restock? ");
            // Input handling
            int shelfIndex;
            try {
                shelfIndex = Integer.parseInt(input.nextLine());
                if (shelfIndex > inventory.getSize() - 1) {
                    System.out.println("Inputted number was out of bounds. Rounding back to nearest element.");
                    shelfIndex = inventory.getSize() - 1;
                } else if (shelfIndex < 0) {
                    shelfIndex = 0;
                }
            } catch (NumberFormatException e) {
                System.out.println("Input was not a number. Restocking shelf 0.");
                shelfIndex = 0;
            }
            // Get inputted shelf and the item in said shelf
            Shelf shelf = inventory.getShelf(shelfIndex);
            Item shelfItem = shelf.getItem();
            // Get the sell price product of all missing items and divide it by 2
            float cost = (shelfItem.getSellPrice() * (shelf.getMaxStock() - shelf.getStock())) / 2;
            System.out.print(String.format("Restocking shelf %s will cost $%s. Are you sure you want to restock? (Y/N)",
                    shelfIndex, cost));
            response = input.nextLine();
            if (response.equals("Y")) {
                inventory.subtractBalance(cost);
                shelf.restock();
            }
        }
    }
References src.Store.currentDay, and src.Store.inventory.
Referenced by src.Store.main().
generateCustomers()
static ArrayList< Customer > src.Store.generateCustomers () static private
Definition at line 196 of file Store.java.
{
        // Create new customers
        Random random = new Random();
        ArrayList<Customer> tmp = new ArrayList<Customer>();
        for (int i = 0; i < customersPerDay; i++) {
            int customerType = random.nextInt(3);
            switch (customerType) {
            case 0:
                tmp.add(new ThirstyCustomer());
                break;
            case 1:
                tmp.add(new HungryCustomer());
                break;
            case 2:
                tmp.add(new StandardCustomer());
                break;
            default:
                System.err.println("Unexpected value returned from random number method.");
                break;
            }
        }
        return tmp;
    }
References src.Store.customersPerDay.
Referenced by src.Store.beginDay().
initStore()
static void src.Store.initStore (Scanner input) static private
Definition at line 62 of file Store.java.
{
        // Init ItemManager
        itemManager = new ItemManager(JSON_FILE);
        // Init Inventory
        inventory = new Inventory(STARTING_SHELF_CAPACITY, STARTING_BALANCE);
        currentDay = 0;
        /*
         * Stock one shelf per ItemType defined in the ItemManager class. Loop through
         * the ItemType enum, and for each value, stock a new shelf. This is done to
         * ensure that the user has a diverse shelf stock to ensure that when new
         * customers come in, they will always have an item that they may prefer.
         */
        for (ItemManager.ItemType itemType : ItemManager.ItemType.values()) {
            /*
             * Get the ArrayList<Item> from the ItemManager class that holds all of the
             * items of the given type. For example, if we pass in the ItemType.Food type,
             * it will return an ArrayList<Item> that holds all of the items with the
             * ItemType.Food type.
             */
            ArrayList<Item> typedArray = itemManager.itemArrays.get(itemType);
            // Iterate through every Item in the retrieved ArrayList<Item> and print them.
            for (int i = 0; i < typedArray.size(); i++) {
                System.out.println(String.format("Item Index: %s", i));
                typedArray.get(i).printItem();
            }
            // Prompt the user to select one of the printed items via index.
            System.out.print(String.format("Choose a %s item to stock: ", itemType));
            // Input handling
            int itemIndex;
            try {
                itemIndex = Integer.parseInt(input.nextLine());
                if (itemIndex > typedArray.size() - 1) {
                    System.out.println("Inputted number surpassed upper bound. Rounding back to nearest element.");
                    itemIndex = typedArray.size() - 1;
                } else if (itemIndex < 0) {
                    System.out.println("Inputted number surpassed lower bound. Rounding back to nearest element.");
                    itemIndex = 0;
                }
            } catch (NumberFormatException e) {
                System.out.println("Input was not a number. Stocking item 0.");
                itemIndex = 0;
            }
            // Create a new shelf with the user's chosen item and add it to the store's
            // Inventory.
            Shelf newShelf = new Shelf(typedArray.get(itemIndex), SHELF_DEFAULT_MAX_STOCK, SHELF_DEFAULT_INITIAL_STOCK);
            inventory.addShelf(newShelf);
        }
        System.out.println("Game Started - Shelves:");
        inventory.printShelves();
        System.out.println("Day Starting...");
        System.out.println("==============");
    }
References src.Store.currentDay, src.Store.inventory, src.Store.itemManager, src.Store.JSON_FILE, src.Store.SHELF_DEFAULT_INITIAL_STOCK, src.Store.SHELF_DEFAULT_MAX_STOCK, src.Store.STARTING_BALANCE, and src.Store.STARTING_SHELF_CAPACITY.
Referenced by src.Store.main().
main()
static void src.Store.main (String[] args) static
Definition at line 39 of file Store.java.
{
        // Init scanner
        Scanner input = new Scanner(System.in);
        initStore(input);
        // Game loop
        while (currentDay < DAY_LIMIT) {
            beginDay();
            if (currentDay == DAY_LIMIT) {
                break;
            }
            endDay(input);
        }
        System.out.println(String.format("After %s days, you went from $%s, to $%s! Great Job!", currentDay,
                STARTING_BALANCE, inventory.getBalance()));
        input.close();
    }
References src.Store.beginDay(), src.Store.currentDay, src.Store.DAY_LIMIT, src.Store.endDay(), src.Store.initStore(), src.Store.inventory, and src.Store.STARTING_BALANCE.
Member Data Documentation
currentDay
int src.Store.currentDay static private
Definition at line 37 of file Store.java.
Referenced by src.Store.beginDay(), src.Store.endDay(), src.Store.initStore(), and src.Store.main().
customers
ArrayList<Customer> src.Store.customers = new ArrayList<Customer>() static private
Definition at line 34 of file Store.java.
Referenced by src.Store.beginDay().
customersPerDay
int src.Store.customersPerDay static private
Definition at line 36 of file Store.java.
Referenced by src.Store.beginDay(), and src.Store.generateCustomers().
DAY_LIMIT
final int src.Store.DAY_LIMIT = 7 static private
Definition at line 22 of file Store.java.
Referenced by src.Store.main().
inventory
Inventory src.Store.inventory static private
Definition at line 32 of file Store.java.
Referenced by src.Store.beginDay(), src.Store.endDay(), src.Store.initStore(), and src.Store.main().
itemManager
ItemManager src.Store.itemManager static private
Definition at line 33 of file Store.java.
Referenced by src.Store.initStore().
JSON_FILE
final File src.Store.JSON_FILE = new File("json/items.json") static private
Definition at line 20 of file Store.java.
Referenced by src.Store.initStore().
SHELF_DEFAULT_INITIAL_STOCK
final int src.Store.SHELF_DEFAULT_INITIAL_STOCK = SHELF_DEFAULT_MAX_STOCK / 2 static private
Definition at line 27 of file Store.java.
Referenced by src.Store.initStore().
SHELF_DEFAULT_MAX_STOCK
final int src.Store.SHELF_DEFAULT_MAX_STOCK = 25 static private
Definition at line 26 of file Store.java.
Referenced by src.Store.initStore().
STARTING_BALANCE
final float src.Store.STARTING_BALANCE = 100.00f static private
Definition at line 29 of file Store.java.
Referenced by src.Store.initStore(), and src.Store.main().
STARTING_SHELF_CAPACITY
final int src.Store.STARTING_SHELF_CAPACITY = 10 static private
Definition at line 24 of file Store.java.
Referenced by src.Store.initStore().
The documentation for this class was generated from the following file:
src/src/Store.java