A7-Fitness: Biometrics Class Reference
Biometrics Class Reference
Public Member Functions
Biometrics (double weight, double height, int age)
double getWeight ()
void setWeight (double weight)
double getHeight ()
void setHeight (double height)
int getAge ()
void setAge (int age)
double getBMI ()
double getBMR ()
Private Member Functions
double calculateBMI ()
double calculateBMR ()
Private Attributes
double weight
double height
int age
double bmi
double bmr
Detailed Description
Definition at line 1 of file Biometrics.java.
Constructor & Destructor Documentation
Biometrics()
Biometrics.Biometrics (double weight, double height, int age)
Definition at line 8 of file Biometrics.java.
{
        this.weight = weight;
        this.height = height;
        this.age = age;
        this.bmi = calculateBMI();
        this.bmr = calculateBMR();
    }
References age, calculateBMI(), calculateBMR(), height, and weight.
Member Function Documentation
calculateBMI()
double Biometrics.calculateBMI () private
Definition at line 52 of file Biometrics.java.
{
        return Math.round(weight / Math.pow(height, 2));
    }
References height, and weight.
Referenced by Biometrics(), setHeight(), and setWeight().
calculateBMR()
double Biometrics.calculateBMR () private
Definition at line 56 of file Biometrics.java.
{
        return (10 * weight) + (625 * height) - (5 * age) + 5;
    }
References age, height, and weight.
Referenced by Biometrics(), setHeight(), and setWeight().
getAge()
int Biometrics.getAge ()
Definition at line 36 of file Biometrics.java.
{
        return age;
    }
References age.
getBMI()
double Biometrics.getBMI ()
Definition at line 44 of file Biometrics.java.
{
        return bmi;
    }
References bmi.
getBMR()
double Biometrics.getBMR ()
Definition at line 48 of file Biometrics.java.
{
        return bmr;
    }
References bmr.
Referenced by Planner.calCalsToBurn(), and Planner.goalCalories().
getHeight()
double Biometrics.getHeight ()
Definition at line 26 of file Biometrics.java.
{
        return height;
    }
References height.
getWeight()
double Biometrics.getWeight ()
Definition at line 16 of file Biometrics.java.
{
        return weight;
    }
References weight.
setAge()
void Biometrics.setAge (int age)
Definition at line 40 of file Biometrics.java.
{
        this.age = age;
    }
References age.
setHeight()
void Biometrics.setHeight (double height)
Definition at line 30 of file Biometrics.java.
{
        this.height = height;
        this.bmi = calculateBMI();
        this.bmr = calculateBMR();
    }
References calculateBMI(), calculateBMR(), and height.
setWeight()
void Biometrics.setWeight (double weight)
Definition at line 20 of file Biometrics.java.
{
        this.weight = weight;
        this.bmi = calculateBMI();
        this.bmr = calculateBMR();
    }
References calculateBMI(), calculateBMR(), and weight.
Member Data Documentation
age
int Biometrics.age private
Definition at line 4 of file Biometrics.java.
Referenced by Biometrics(), calculateBMR(), getAge(), and setAge().
bmi
double Biometrics.bmi private
Definition at line 5 of file Biometrics.java.
Referenced by getBMI().
bmr
double Biometrics.bmr private
Definition at line 6 of file Biometrics.java.
Referenced by getBMR().
height
double Biometrics.height private
Definition at line 3 of file Biometrics.java.
Referenced by Biometrics(), calculateBMI(), calculateBMR(), getHeight(), and setHeight().
weight
double Biometrics.weight private
Definition at line 2 of file Biometrics.java.
Referenced by Biometrics(), calculateBMI(), calculateBMR(), getWeight(), and setWeight().
The documentation for this class was generated from the following file:
src/Biometrics.java