A7-Fitness: Planner Class Reference
Planner Class Reference
Public Member Functions
Planner (Biometrics biometrics, User user)
int calCalsToBurn ()
List< Exercise > pickExercises ()
void printPickedExercises ()
double goalCalories ()
void allExercises ()
Public Attributes
List< Exercise > allExercises
Private Attributes
Biometrics biometrics
int maxCalories
User user
List< Exercise > availableExercises
List< Exercise > pickedExercises
Detailed Description
Definition at line 5 of file Planner.java.
Constructor & Destructor Documentation
Planner()
Planner.Planner (Biometrics biometrics, User user)
Definition at line 13 of file Planner.java.
{
        this.biometrics = biometrics;
        this.user = user;
        this.maxCalories = calCalsToBurn();
        this.availableExercises = new ArrayList<Exercise>();
        if (user.getPlan().equals("WL")) {
            this.availableExercises.addAll(AerobicExercises.getExercises());
        } else if (user.getPlan().equals("WG")) {
            this.availableExercises.addAll(StrengthTrainingExercises.getExercises());
        }
        Collections.shuffle(this.availableExercises); // Randomize the order of exercises
        this.allExercises = new ArrayList<Exercise>();
        this.allExercises.addAll(AerobicExercises.getExercises());
        this.allExercises.addAll(StrengthTrainingExercises.getExercises());
        this.pickedExercises = new ArrayList<Exercise>();
        pickExercises();
    }
References biometrics, calCalsToBurn(), AerobicExercises.getExercises(), StrengthTrainingExercises.getExercises(), User.getPlan(), pickExercises(), and user.
Member Function Documentation
allExercises()
void Planner.allExercises ()
Definition at line 68 of file Planner.java.
{
        int index = 1;
        for (Exercise exercise : allExercises) {
            System.out.println(index + ". " + exercise.getName() + " - " + exercise.getCaloriesOut() + " calories");
            index++;
        }
    }
References allExercises.
calCalsToBurn()
int Planner.calCalsToBurn ()
Definition at line 32 of file Planner.java.
{
        return (int) (biometrics.getBMR() * 0.25); // will change it
    }
References biometrics, and Biometrics.getBMR().
Referenced by Planner().
goalCalories()
double Planner.goalCalories ()
Definition at line 59 of file Planner.java.
{
        if (user.getPlan().equals("WL")) {
            return biometrics.getBMR() - (biometrics.getBMR() * 0.15);
        } else if (user.getPlan().equals("WG")) {
            return biometrics.getBMR() + (biometrics.getBMR() * 0.15);
        }
        return 0.0;
    }
References biometrics, Biometrics.getBMR(), User.getPlan(), and user.
pickExercises()
List< Exercise > Planner.pickExercises ()
Definition at line 36 of file Planner.java.
{
        int currentCalories = 0;
        for (Exercise exercise : availableExercises) {
            if (currentCalories + exercise.getCaloriesOut() <= maxCalories) {
                pickedExercises.add(exercise);
                currentCalories += exercise.getCaloriesOut();
                if (currentCalories >= maxCalories) {
                    break;
                }
            }
        }
        return pickedExercises;
    }
References availableExercises, maxCalories, and pickedExercises.
Referenced by Planner().
printPickedExercises()
void Planner.printPickedExercises ()
Definition at line 52 of file Planner.java.
{
        for (Exercise exercise : pickedExercises) {
            System.out.println(exercise.getName() + " - " + exercise.getCaloriesOut() + " calories");
        }
    }
References pickedExercises.
Member Data Documentation
allExercises
List<Exercise> Planner.allExercises
Definition at line 10 of file Planner.java.
Referenced by allExercises().
availableExercises
List<Exercise> Planner.availableExercises private
Definition at line 9 of file Planner.java.
Referenced by pickExercises().
biometrics
Biometrics Planner.biometrics private
Definition at line 6 of file Planner.java.
Referenced by calCalsToBurn(), goalCalories(), and Planner().
maxCalories
int Planner.maxCalories private
Definition at line 7 of file Planner.java.
Referenced by pickExercises().
pickedExercises
List<Exercise> Planner.pickedExercises private
Definition at line 11 of file Planner.java.
Referenced by pickExercises(), and printPickedExercises().
user
User Planner.user private
Definition at line 8 of file Planner.java.
Referenced by goalCalories(), and Planner().
The documentation for this class was generated from the following file:
src/Planner.java