B3-Epidemic: Civilian Class Reference
Civilian Class Reference
Public Member Functions
Civilian ()
Civilian (double x, double y)
double getX ()
double getY ()
void infect ()
void cure ()
void setPos (double x, double y)
void printInfo ()
Private Attributes
boolean infected
boolean immunity
double hor
double ver
Detailed Description
Definition at line 2 of file Civilian.java.
Constructor & Destructor Documentation
Civilian() [1/2]
Civilian.Civilian ()
Definition at line 8 of file Civilian.java.
                      {
        this.infected = false;
        this.immunity = false;
        this.hor = Math.random();
        this.ver = Math.random();
    }
Civilian() [2/2]
Civilian.Civilian (double x, double y)
Definition at line 15 of file Civilian.java.
{
        this.infected = false;
        this.immunity = false;
        this.hor = x;
        this.ver = y;
    }
Member Function Documentation
cure()
void Civilian.cure ()
Definition at line 34 of file Civilian.java.
                       {
        this.infected = false;
        this.immunity = true;
    }
getX()
double Civilian.getX ()
Definition at line 22 of file Civilian.java.
{
        return this.hor;
    }
References hor.
Referenced by Hospital.attract(), Restaurant.attract(), and Area.update().
getY()
double Civilian.getY ()
Definition at line 26 of file Civilian.java.
{
        return this.ver;
    }
References ver.
Referenced by Hospital.attract(), Restaurant.attract(), and Area.update().
infect()
void Civilian.infect ()
Definition at line 30 of file Civilian.java.
{
        this.infected = true;
    }
printInfo()
void Civilian.printInfo ()
Definition at line 44 of file Civilian.java.
{
        System.out.println("Position: X: " + this.hor + " | Y: " + this.ver);
        System.out.println("Infected: " + infected + " | Immunity: " + immunity);
    }
References immunity, and infected.
setPos()
void Civilian.setPos (double x, double y)
Definition at line 39 of file Civilian.java.
{
        this.hor = x;
        this.ver = y;
    }
Referenced by Hospital.attract(), and Restaurant.attract().
Member Data Documentation
hor
double Civilian.hor private
Definition at line 5 of file Civilian.java.
Referenced by getX().
immunity
boolean Civilian.immunity private
Definition at line 4 of file Civilian.java.
Referenced by printInfo().
infected
boolean Civilian.infected private
Definition at line 3 of file Civilian.java.
Referenced by printInfo().
ver
double Civilian.ver private
Definition at line 6 of file Civilian.java.
Referenced by getY().
The documentation for this class was generated from the following file:
src/Civilian.java