B3-Epidemic: Area Class Reference
Area Class Reference
Public Member Functions
Area ()
double getInfectionRate ()
double getInfectRadius ()
double getRecoveryRate ()
int getPopulation ()
ArrayList< Building > getBuildings ()
ArrayList< Civilian > getCiv ()
ArrayList< Civilian > getRecovered ()
ArrayList< Civilian > getInfected ()
void setInfectionRate (double i)
void setInfectRadius (double i)
void setRecoveryRate (double i)
void setPopulation (int i)
void addBuilding (Building b)
void fillCiv ()
void addInfected (int i)
void cureInfected (int i)
void fillBuilding ()
void fillBuilding (int numRes, int numHos)
void update ()
void printStatus ()
void setup ()
void printInfo ()
Private Attributes
final int sizeY
final int sizeX
int population
ArrayList< Civilian > infected
ArrayList< Civilian > recovered
ArrayList< Building > buildings
ArrayList< Civilian > civ
double infectionRate
double recoveryRate
double infectRadius
Detailed Description
Definition at line 3 of file Area.java.
Constructor & Destructor Documentation
Area()
Area.Area ()
Definition at line 16 of file Area.java.
                  {
        this.sizeY = 1;
        this.sizeX = 1;
        this.population = 100;
        this.infected = new ArrayList<Civilian>();
        this.buildings = new ArrayList<Building>();
        this.recovered = new ArrayList<Civilian>();
        this.civ = new ArrayList<Civilian>();
        this.infectionRate = 0.7;
        this.recoveryRate = 0.3;
        this.infectRadius = 0.05;
        // this.deathChance = 0.1;
    }
Member Function Documentation
addBuilding()
void Area.addBuilding (Building b)
Definition at line 92 of file Area.java.
{
        buildings.add(b);
    }
References buildings.
addInfected()
void Area.addInfected (int i)
Definition at line 103 of file Area.java.
{
        this.civ.get(i).infect();
        this.infected.add(this.civ.get(i));
        this.civ.remove(i);
    }
Referenced by setup(), and update().
cureInfected()
void Area.cureInfected (int i)
Definition at line 109 of file Area.java.
{
        this.infected.get(i).cure();
        this.recovered.add(this.infected.get(i));
        this.infected.remove(i);
    }
Referenced by update().
fillBuilding() [1/2]
void Area.fillBuilding ()
Definition at line 115 of file Area.java.
{
        Building h1 = new Hospital();
        this.buildings.add(h1);
        Building h2 = new Hospital();
        this.buildings.add(h2);
        Building r1 = new Restaurant();
        this.buildings.add(r1);
        Building r2 = new Restaurant();
        this.buildings.add(r2);
    }
Referenced by InputHelper.getInput().
fillBuilding() [2/2]
void Area.fillBuilding (int numRes, int numHos)
Definition at line 126 of file Area.java.
{
        for (int i = 0; i < numRes; i++) {
            Building r1 = new Restaurant();
            this.buildings.add(r1);
        }
        for (int i = 0; i < numHos; i++) {
            Building h1 = new Hospital();
            this.buildings.add(h1);
        }
    }
fillCiv()
void Area.fillCiv ()
Definition at line 96 of file Area.java.
{
        for (int i = 0; i < this.population; i++) {
            Civilian c = new Civilian();
            this.civ.add(c);
        }
    }
References population.
Referenced by InputHelper.getInput().
getBuildings()
ArrayList< Building > Area.getBuildings ()
Definition at line 59 of file Area.java.
{
        return this.buildings;
    }
References buildings.
getCiv()
ArrayList< Civilian > Area.getCiv ()
Definition at line 63 of file Area.java.
{
        return this.civ;
    }
References civ.
getInfected()
ArrayList< Civilian > Area.getInfected ()
Definition at line 71 of file Area.java.
{
        return this.infected;
    }
References infected.
Referenced by SimulationHelper.simulate().
getInfectionRate()
double Area.getInfectionRate ()
Definition at line 43 of file Area.java.
{
        return this.infectionRate;
    }
References infectionRate.
getInfectRadius()
double Area.getInfectRadius ()
Definition at line 47 of file Area.java.
{
        return this.infectRadius;
    }
References infectRadius.
getPopulation()
int Area.getPopulation ()
Definition at line 55 of file Area.java.
{
        return this.population;
    }
References population.
getRecovered()
ArrayList< Civilian > Area.getRecovered ()
Definition at line 67 of file Area.java.
{
        return this.recovered;
    }
References recovered.
getRecoveryRate()
double Area.getRecoveryRate ()
Definition at line 51 of file Area.java.
{
        return this.recoveryRate;
    }
References recoveryRate.
printInfo()
void Area.printInfo ()
Definition at line 183 of file Area.java.
{
        System.out.println("Size: " + "X = " + this.sizeX + " | Y = " + this.sizeY);
        System.out.println("Population: " + this.population);
        System.out.println("Infected: " + this.infected);
        System.out.println("Virus Info: Infection Rate: " + this.infectionRate + " | Recovery Rate: "
                + this.recoveryRate + " | Infect Radius: ");
        System.out.println("Number of Buildings: " + buildings.size());
        // + this.infectRadius + " | Death Chance: " + this.deathChance);
    }
References buildings.
Referenced by Main.main().
printStatus()
void Area.printStatus ()
Definition at line 165 of file Area.java.
{
        System.out.println(": Susceptible = " + civ.size() + ", Infected = " + infected.size() + ", Recovered = "
                + recovered.size());
    }
References civ, infected, and recovered.
Referenced by SimulationHelper.simulate().
setInfectionRate()
void Area.setInfectionRate (double i)
Definition at line 76 of file Area.java.
{
        this.infectionRate = i;
    }
Referenced by InputHelper.getInput().
setInfectRadius()
void Area.setInfectRadius (double i)
Definition at line 80 of file Area.java.
{
        this.infectRadius = i;
    }
setPopulation()
void Area.setPopulation (int i)
Definition at line 88 of file Area.java.
{
        this.population = i;
    }
Referenced by InputHelper.getInput().
setRecoveryRate()
void Area.setRecoveryRate (double i)
Definition at line 84 of file Area.java.
{
        this.recoveryRate = i;
    }
Referenced by InputHelper.getInput().
setup()
void Area.setup ()
Definition at line 170 of file Area.java.
{
        for (int i = 0; i < this.buildings.size(); i++) {
            Building b = this.buildings.get(i);
            for (int j = 0; j < this.civ.size(); j++) {
                b.attract(civ.get(j));
            }
        }
        int ran = (int) (Math.random() * this.civ.size());
        this.civ.get(ran).infect();
        addInfected(ran);
    }
References addInfected(), Building.attract(), and civ.
Referenced by Main.main().
update()
void Area.update ()
Definition at line 137 of file Area.java.
{
        for (int i = 0; i < this.infected.size(); i++) {
            Civilian c1 = this.infected.get(i);
            double chance = Math.random();
            if (chance <= recoveryRate) {
                cureInfected(i);
                i--;
            } else {
                for (int j = 0; j < this.civ.size(); j++) {
                    Civilian c2 = this.civ.get(j);
                    double distant = Math.sqrt(Math.pow(c1.getX() - c2.getX(), 2) + Math.pow(c1.getY() - c2.getY(), 2));
                    double rand = Math.random();
                    double imod = 0;
                    for (int k = 0; k < buildings.size(); k++) {
                        Building b = buildings.get(k);
                        if (b.getLocX() == c2.getX() && b.getLocY() == c2.getY()) {
                            imod = b.getInfect();
                        }
                    }
                    if (distant <= this.infectRadius || rand <= (this.infectionRate + imod)) {
                        addInfected(j);
                        j--;
                    }
                }
            }
        }
    }
References addInfected(), buildings, cureInfected(), Building.getInfect(), Building.getLocX(), Building.getLocY(), Civilian.getX(), Civilian.getY(), and recoveryRate.
Referenced by SimulationHelper.simulate().
Member Data Documentation
buildings
ArrayList<Building> Area.buildings private
Definition at line 9 of file Area.java.
Referenced by addBuilding(), getBuildings(), printInfo(), and update().
civ
ArrayList<Civilian> Area.civ private
Definition at line 10 of file Area.java.
Referenced by getCiv(), printStatus(), and setup().
infected
ArrayList<Civilian> Area.infected private
Definition at line 7 of file Area.java.
Referenced by getInfected(), and printStatus().
infectionRate
double Area.infectionRate private
Definition at line 11 of file Area.java.
Referenced by getInfectionRate().
infectRadius
double Area.infectRadius private
Definition at line 13 of file Area.java.
Referenced by getInfectRadius().
population
int Area.population private
Definition at line 6 of file Area.java.
Referenced by fillCiv(), and getPopulation().
recovered
ArrayList<Civilian> Area.recovered private
Definition at line 8 of file Area.java.
Referenced by getRecovered(), and printStatus().
recoveryRate
double Area.recoveryRate private
Definition at line 12 of file Area.java.
Referenced by getRecoveryRate(), and update().
sizeX
final int Area.sizeX private
Definition at line 5 of file Area.java.
sizeY
final int Area.sizeY private
Definition at line 4 of file Area.java.
The documentation for this class was generated from the following file:
src/Area.java