B3-Epidemic: SimulationHelper Class Reference
SimulationHelper Class Reference
Static Public Member Functions
static void simulate (Area area)
Detailed Description
Definition at line 4 of file SimulationHelper.java.
Member Function Documentation
simulate()
static void SimulationHelper.simulate (Area area) static
Definition at line 6 of file SimulationHelper.java.
{
        int days = 0;
        while (area.getInfected().size() > 0) {
            days++;
            System.out.println("Day " + days + ":");
            area.printStatus();
            area.update();
        }
        System.out.println("Epidemic ended after " + days + " days.");
    }
References Area.getInfected(), Area.printStatus(), and Area.update().
Referenced by Main.main().
The documentation for this class was generated from the following file:
src/SimulationHelper.java