B3-Epidemic: InputHelper Class Reference
InputHelper Class Reference
Static Public Member Functions
static void getInput (Area area)
Detailed Description
Definition at line 4 of file InputHelper.java.
Member Function Documentation
getInput()
static void InputHelper.getInput (Area area) static
Definition at line 6 of file InputHelper.java.
{
        Scanner scanner = new Scanner(System.in);
        try {
            System.out.print("Enter the population size: ");
            int populationSize = scanner.nextInt();
            System.out.println("Enter number of Restaurant");
            int restaurantNumber = scanner.nextInt();
            System.out.println("Enter number of Hospital");
            int hospitaltNumber = scanner.nextInt();
            double infectionRate, recoveryRate;
            while (true) {
                System.out.print("Enter the infection rate (0 to 1): ");
                infectionRate = scanner.nextDouble();
                if (infectionRate >= 0 && infectionRate <= 1)
                    break;
                System.out.println("Invalid infection rate. Please enter a value between 0 and 1.");
            }
            while (true) {
                System.out.print("Enter the recovery rate (0 to 1): ");
                recoveryRate = scanner.nextDouble();
                if (recoveryRate >= 0 && recoveryRate <= 1)
                    break;
                System.out.println("Invalid recovery rate. Please enter a value between 0 and 1.");
            }
            area.setPopulation(populationSize);
            area.setInfectionRate(infectionRate);
            area.setRecoveryRate(recoveryRate);
            area.fillBuilding(restaurantNumber, hospitaltNumber);
            area.fillCiv();
        } finally {
            scanner.close();
        }
    }
References Area.fillBuilding(), Area.fillCiv(), Area.setInfectionRate(), Area.setPopulation(), and Area.setRecoveryRate().
Referenced by Main.main().
The documentation for this class was generated from the following file:
src/InputHelper.java