B3-Epidemic: Building Interface Reference
Building Interface Reference
Public Member Functions
void attract (Civilian c)
void printInfo ()
double getLocX ()
double getLocY ()
double getHealth ()
double getInfect ()
Detailed Description
Definition at line 1 of file Building.java.
Member Function Documentation
attract()
void Building.attract (Civilian c)
Implemented in Hospital, and Restaurant.
Referenced by Area.setup().
getHealth()
double Building.getHealth ()
Implemented in Hospital, and Restaurant.
getInfect()
double Building.getInfect ()
Implemented in Hospital, and Restaurant.
Referenced by Area.update().
getLocX()
double Building.getLocX ()
Implemented in Hospital, and Restaurant.
Referenced by Area.update().
getLocY()
double Building.getLocY ()
Implemented in Hospital, and Restaurant.
Referenced by Area.update().
printInfo()
void Building.printInfo ()
Implemented in Hospital, and Restaurant.
The documentation for this interface was generated from the following file:
src/Building.java