A6-Pyramid: PyramidGame Class Reference
PyramidGame Class Reference
Public Member Functions
PyramidGame (Player p1, Player p2)
PyramidGame ()
void initializeGame (int height)
boolean chooseSegment (int level, int square, int segment, int player)
void displayPyramid ()
int[] getScores ()
int totalSquare (int level)
boolean endGame ()
void winner ()
int getHeight ()
Static Public Attributes
static int height
Private Member Functions
boolean isSquareComplete (int level, int square)
Private Attributes
boolean[][][] segments
int[] scores
int squareCompleted = 0
Player[] players
Detailed Description
Definition at line 1 of file PyramidGame.java.
Constructor & Destructor Documentation
PyramidGame() [1/2]
PyramidGame.PyramidGame (Player p1, Player p2)
Definition at line 8 of file PyramidGame.java.
{
        this.players = new Player[] { p1, p2 };
        this.scores = new int[2]; // Score for two players
    }
PyramidGame() [2/2]
PyramidGame.PyramidGame ()
Definition at line 13 of file PyramidGame.java.
{
        this.scores = new int[2];
    }
Member Function Documentation
chooseSegment()
boolean PyramidGame.chooseSegment (int level, int square, int segment, int player)
Definition at line 25 of file PyramidGame.java.
                                                                                 { // Segment class
        if (level < height && square <= level && segment < 4 && !segments[level][square][segment]) // that segment has
                                                                                                    // not been filled,
                                                                                                    // still false
        {
            segments[level][square][segment] = true; // Mark the line as chosen
            // Check if this choice completes a square
            if (isSquareComplete(level, square)) {
                scores[player]++;
                return true; // Square completed
            }
            return false; // Square not completed
        }
        System.out.println("Wrong move.");
        return false; // Invalid move
    }
References height, isSquareComplete(), scores, and segments.
Referenced by Main.main().
displayPyramid()
void PyramidGame.displayPyramid ()
Definition at line 42 of file PyramidGame.java.
                                 { // pyramidGame class
        int count = 0;
        System.out.println("\n");
        for (int i = 0; i < height; i++) {
            System.out.print(count);
            count++;
            for (int j = 0; j < height - i - 1; j++) {
                System.out.print("    "); // Spaces for alignment
            }
            for (int k = 0; k <= i; k++) {
                System.out.print("[");
                System.out.print(segments[i][k][0] ? "X" : " "); // Top line
                System.out.print(segments[i][k][1] ? "|X|" : "| |"); // left lines with middle space or X
                System.out.print(segments[i][k][3] ? "X|" : " |");// right side
                System.out.print(segments[i][k][2] ? "X" : " "); // Bottom line
                System.out.print("] ");
            }
            System.out.println();
        }
        System.out.println("\n");
    }
References height, and segments.
Referenced by Main.main().
endGame()
boolean PyramidGame.endGame ()
Definition at line 86 of file PyramidGame.java.
{
        return (squareCompleted == totalSquare(height));
        // System.out.println (" Game over");
    }
References height, squareCompleted, and totalSquare().
Referenced by Main.main().
getHeight()
int PyramidGame.getHeight ()
Definition at line 103 of file PyramidGame.java.
{
        return height;
    }
References height.
getScores()
int[] PyramidGame.getScores ()
Definition at line 64 of file PyramidGame.java.
                             { // gameController class
        return scores;
    }
References scores.
Referenced by Main.main().
initializeGame()
void PyramidGame.initializeGame (int height)
Definition at line 17 of file PyramidGame.java.
                                           { // gameController class
        this.height = height;
        this.segments = new boolean[height][][];
        for (int i = 0; i < height; i++) {
            segments[i] = new boolean[i + 1][4]; // Each square can have 4 segments
        }
    }
References height, and segments.
Referenced by Main.main().
isSquareComplete()
boolean PyramidGame.isSquareComplete (int level, int square) private
Definition at line 68 of file PyramidGame.java.
                                                            { //
        for (boolean segment1 : segments[level][square]) {
            if (!segment1)
                return false; // If any line is not selected, square is not complete
        }
        squareCompleted++;
        return true; // All lines are selected, square is complete
    }
References segments, and squareCompleted.
Referenced by chooseSegment().
totalSquare()
int PyramidGame.totalSquare (int level)
Definition at line 77 of file PyramidGame.java.
{
        if (level == 0)
            return 0;
        else {
            return level + totalSquare(level - 1);
        }
    }
References totalSquare().
Referenced by endGame(), and totalSquare().
winner()
void PyramidGame.winner ()
Definition at line 91 of file PyramidGame.java.
{
        // Logic to determine and announce the winner.
        System.out.println(" Game over! ");
        if (scores[0] > scores[1]) {
            System.out.println(players[0].getName() + " wins!");
        } else if (scores[1] > scores[0]) {
            System.out.println(players[1].getName() + " wins!");
        } else {
            System.out.println("It's a tie!");
        }
    }
References players, and scores.
Referenced by Main.main().
Member Data Documentation
height
int PyramidGame.height static
Definition at line 3 of file PyramidGame.java.
Referenced by ComputerGame.chooselss(), chooseSegment(), displayPyramid(), endGame(), getHeight(), and initializeGame().
players
Player [] PyramidGame.players private
Definition at line 6 of file PyramidGame.java.
Referenced by winner().
scores
int [] PyramidGame.scores private
Definition at line 4 of file PyramidGame.java.
Referenced by chooseSegment(), getScores(), and winner().
segments
boolean [][][] PyramidGame.segments private
Definition at line 2 of file PyramidGame.java.
Referenced by chooseSegment(), displayPyramid(), initializeGame(), and isSquareComplete().
squareCompleted
int PyramidGame.squareCompleted = 0 private
Definition at line 5 of file PyramidGame.java.
Referenced by endGame(), and isSquareComplete().
The documentation for this class was generated from the following file:
src/PyramidGame.java