A6-Pyramid: PlayerModeInterface Interface Reference
PlayerModeInterface Interface Reference
Public Member Functions
void chooselss ()
int getLevel ()
int getSquare ()
int getSegment ()
int getIndex ()
Detailed Description
Definition at line 1 of file PlayerModeInterface.java.
Member Function Documentation
chooselss()
void PlayerModeInterface.chooselss ()
Implemented in ComputerGame, and PlayerGame.
Referenced by Main.main().
getIndex()
int PlayerModeInterface.getIndex ()
Implemented in ComputerGame, and PlayerGame.
Referenced by Main.main().
getLevel()
int PlayerModeInterface.getLevel ()
Implemented in ComputerGame, and PlayerGame.
Referenced by Main.main().
getSegment()
int PlayerModeInterface.getSegment ()
Implemented in ComputerGame, and PlayerGame.
Referenced by Main.main().
getSquare()
int PlayerModeInterface.getSquare ()
Implemented in ComputerGame, and PlayerGame.
Referenced by Main.main().
The documentation for this interface was generated from the following file:
src/PlayerModeInterface.java