B4-Minesweeper: Cell Class Reference
Cell Class Reference abstract
Public Member Functions
void rightClick ()
void leftClick ()
boolean getIsLeftClicked ()
Detailed Description
Definition at line 6 of file Cell.java.
Member Function Documentation
getIsLeftClicked()
boolean Cell.getIsLeftClicked ()
Definition at line 32 of file Cell.java.
{
        return isLeftClicked;
    }
Referenced by Board.isLoseByClick().
leftClick()
void Cell.leftClick ()
Definition at line 28 of file Cell.java.
{
        isLeftClicked = true;
    }
Referenced by Board.clickFirstCell(), Board.leftClick(), and Board.revealBoard().
rightClick()
void Cell.rightClick ()
Definition at line 14 of file Cell.java.
{
        switch (rightClick) {
        case FLAG:
            rightClick = RightClick.QUESTION;
            return;
        case QUESTION:
            rightClick = RightClick.NONE;
            return;
        case NONE:
            rightClick = RightClick.FLAG;
            return;
        }
    }
References RightClick.FLAG, RightClick.NONE, and RightClick.QUESTION.
The documentation for this class was generated from the following file:
src/Cell.java