B4-Minesweeper: Game Class Reference
Game Class Reference
Public Member Functions
Game ()
void play1Game () throws Exception
Private Member Functions
Mode inputMode () throws Exception
int inputDim () throws Exception
int[] inputCell (int dim) throws Exception
ClickType inputClickType () throws Exception
Detailed Description
Definition at line 7 of file Game.java.
Constructor & Destructor Documentation
Game()
Game.Game ()
Definition at line 11 of file Game.java.
                  {
        scanner = new Scanner(System.in);
    }
Member Function Documentation
inputCell()
int[] Game.inputCell (int dim) throws Exception private
Definition at line 44 of file Game.java.
{
        System.out.println("Please select your cell's location.");
        System.out.print("Row (a number between 0 and " + dim + " ): ");
        int i = scanner.nextInt();
        System.out.print("Col (a number between 0 and " + dim + " ): ");
        int j = scanner.nextInt();
        if (i < 0 || j < 0 || i >= dim || j >= dim) {
            throw new Exception("Invalid Cell Location, should be a number between 0 and " + dim + " ).");
        }
        return new int[] { i, j };
    }
Referenced by play1Game().
inputClickType()
ClickType Game.inputClickType () throws Exception private
Definition at line 56 of file Game.java.
{
        System.out.println("Please select your click type: 1 for left click and 2 for right click");
        int clickType = scanner.nextInt();
        if (clickType == 1) {
            return ClickType.LEFT;
        } else if (clickType == 2) {
            return ClickType.RIGHT;
        }
        throw new Exception("Invalid click type");
    }
References ClickType.LEFT, and ClickType.RIGHT.
Referenced by play1Game().
inputDim()
int Game.inputDim () throws Exception private
Definition at line 35 of file Game.java.
{
        System.out.println("Please select your board dimension");
        int dim = scanner.nextInt();
        if (dim <= 3) {
            throw new Exception("board dim should be a positive integer > 3");
        }
        return dim;
    }
Referenced by play1Game().
inputMode()
Mode Game.inputMode () throws Exception private
Definition at line 15 of file Game.java.
{
        System.out.println("Please select your difficulty: 1 for easy, 2 for medium, and 3 for hard");
        int intMode = scanner.nextInt();
        Mode mode;
        switch (intMode) {
        case 1:
            mode = Mode.EASY;
            break;
        case 2:
            mode = Mode.MEDIUM;
            break;
        case 3:
            mode = Mode.HARD;
            break;
        default:
            throw new Exception("Invalid mode, please try again");
        }
        return mode;
    }
References Mode.EASY, Mode.HARD, and Mode.MEDIUM.
Referenced by play1Game().
play1Game()
void Game.play1Game () throws Exception
Definition at line 67 of file Game.java.
{
        Mode mode = inputMode();
        int dim = inputDim();
        Board board = new Board(dim, mode);
        int[] firstCellLoc = inputCell(dim);
        board.initializeBoard(firstCellLoc[0], firstCellLoc[1]);
        if (board.isWin()) {
            System.out.println("Board dimension is too small that makes you win accidentally, please try again");
        }
        while (true) {
            System.out.println("------------------------------------------------------");
            System.out.println(board);
            ClickType clickType = inputClickType();
            int[] nextCellLoc = inputCell(dim);
            int i = nextCellLoc[0];
            int j = nextCellLoc[1];
            if (clickType == ClickType.LEFT) {
                board.leftClick(i, j);
            } else {
                board.rightClick(i, j);
            }
            if (board.isLoseByClick(i, j)) {
                System.out.println("------------------------------------------------------");
                System.out.println("You lost!");
                break;
            }
            if (board.isWin()) {
                System.out.println("------------------------------------------------------");
                System.out.println("Congratulation you win!");
                break;
            }
        }
        board.revealBoard();
        System.out.println(board);
    }
References Board.initializeBoard(), inputCell(), inputClickType(), inputDim(), inputMode(), Board.isLoseByClick(), Board.isWin(), ClickType.LEFT, Board.leftClick(), Board.revealBoard(), and Board.rightClick().
Referenced by Main.main().
The documentation for this class was generated from the following file:
src/Game.java