B4-Minesweeper: Board Class Reference
Board Class Reference
Public Member Functions
Board (int dim, Mode mode)
Board (Mode mode)
void initializeBoard (int initialRow, int initialCol)
boolean isWin ()
boolean isLose ()
boolean isLoseByClick (int i, int j)
void leftClick (int i, int j)
void rightClick (int i, int j)
String toString ()
void revealBoard ()
Private Member Functions
int bombCount (int i, int j)
void updateBombCount ()
void clickFirstCell (int i, int j)
Private Attributes
int dim
Cell[][] board
int bombProbability
Detailed Description
Definition at line 10 of file Board.java.
Constructor & Destructor Documentation
Board() [1/2]
Board.Board (int dim, Mode mode)
Definition at line 15 of file Board.java.
{
        this.dim = dim;
        board = new Cell[dim][dim];
        switch (mode) {
        case EASY:
            bombProbability = 40;
            break;
        case MEDIUM:
            bombProbability = 50;
            break;
        case HARD:
            bombProbability = 60;
            break;
        default:
            break;
        }
    }
References board, bombProbability, and dim.
Board() [2/2]
Board.Board (Mode mode)
Definition at line 33 of file Board.java.
{
        this(9, mode);
    }
Member Function Documentation
bombCount()
int Board.bombCount (int i, int j) private
Definition at line 102 of file Board.java.
{
        Cell cell = board[i][j];
        int bomb = 0;
        if (cell.isEmpty()) {
            for (int left = -1; left <= 1; left++) {
                for (int right = -1; right <= 1; right++) {
                    if (left == 0 && right == 0) {
                        continue;
                    }
                    int ni = i + left;
                    int nj = j + right;
                    if (ni >= 0 && ni < dim && nj >= 0 && nj < dim && board[ni][nj].isBomb()) {
                        bomb++;
                    }
                }
            }
        }
        return bomb;
    }
References board, and dim.
Referenced by updateBombCount().
clickFirstCell()
void Board.clickFirstCell (int i, int j) private
Definition at line 144 of file Board.java.
{
        leftClick(i, j);
        // Expand around the cell
        int expandLen = Math.max(dim / 4, 1);
        for (int di = -expandLen; di <= expandLen; di++) {
            for (int dj = -expandLen; dj <= expandLen; dj++) {
                int ni = i + di;
                int nj = j + dj;
                if (ni >= 0 && ni < dim && nj >= 0 && nj < dim && board[ni][nj].isEmpty()) {
                    board[ni][nj].leftClick();
                }
            }
        }
    }
References board, dim, Cell.leftClick(), and leftClick().
Referenced by initializeBoard().
initializeBoard()
void Board.initializeBoard (int initialRow, int initialCol)
Definition at line 37 of file Board.java.
{
        Random rand = new Random();
        for (int i = 0; i < dim; i++) {
            for (int j = 0; j < dim; j++) {
                if (rand.nextInt(100) < bombProbability && i != initialRow && j != initialCol) {
                    board[i][j] = new BombCell();
                } else {
                    board[i][j] = new EmptyCell();
                }
            }
        }
        updateBombCount();
        clickFirstCell(initialRow, initialCol);
    }
References board, bombProbability, clickFirstCell(), dim, and updateBombCount().
Referenced by Game.play1Game().
isLose()
boolean Board.isLose ()
Definition at line 63 of file Board.java.
{
        for (int i = 0; i < dim; i++) {
            for (int j = 0; j < dim; j++) {
                if (isLoseByClick(i, j)) {
                    return true;
                }
            }
        }
        return false;
    }
References dim, and isLoseByClick().
isLoseByClick()
boolean Board.isLoseByClick (int i, int j)
Definition at line 74 of file Board.java.
{
        return board[i][j].isBomb() && board[i][j].getIsLeftClicked();
    }
References board, and Cell.getIsLeftClicked().
Referenced by isLose(), and Game.play1Game().
isWin()
boolean Board.isWin ()
Definition at line 52 of file Board.java.
{
        for (int i = 0; i < dim; i++) {
            for (int j = 0; j < dim; j++) {
                if (board[i][j].isEmpty() && !board[i][j].isLeftClicked) {
                    return false;
                }
            }
        }
        return true;
    }
References board, and dim.
Referenced by Game.play1Game().
leftClick()
void Board.leftClick (int i, int j)
Definition at line 78 of file Board.java.
{
        board[i][j].leftClick();
    }
References board, and Cell.leftClick().
Referenced by clickFirstCell(), and Game.play1Game().
revealBoard()
void Board.revealBoard ()
Definition at line 122 of file Board.java.
{
        for (int i = 0; i < dim; i++) {
            for (int j = 0; j < dim; j++) {
                board[i][j].leftClick();
            }
        }
    }
References board, dim, and Cell.leftClick().
Referenced by Game.play1Game().
rightClick()
void Board.rightClick (int i, int j)
Definition at line 82 of file Board.java.
{
        board[i][j].rightClick();
    }
References board.
Referenced by Game.play1Game().
toString()
String Board.toString ()
Definition at line 87 of file Board.java.
{
        String ans = "";
        int[] colIndex = new int[dim];
        for (int i = 0; i < dim; i++) {
            colIndex[i] = i;
        }
        System.out.println(Arrays.toString(colIndex));
        for (int i = 0; i < dim; i++) {
            Cell[] b = board[i];
            ans += Arrays.toString(b) + " " + i + " " + "\n";
        }
        ans += "X represents bomb, F represents flag, ? represents question, number represents the number of bomb around that cell, and empty means the cell is not yet selected";
        return ans;
    }
References board, and dim.
updateBombCount()
void Board.updateBombCount () private
Definition at line 130 of file Board.java.
{
        for (int i = 0; i < dim; i++) {
            for (int j = 0; j < dim; j++) {
                Cell cell = board[i][j];
                if (cell.isEmpty()) {
                    EmptyCell emptyCell = (EmptyCell) cell;
                    int bomb = bombCount(i, j);
                    emptyCell.setBombCount(bomb);
                }
            }
        }
    }
References board, bombCount(), dim, and EmptyCell.setBombCount().
Referenced by initializeBoard().
Member Data Documentation
board
Cell [][] Board.board private
Definition at line 12 of file Board.java.
Referenced by Board(), bombCount(), clickFirstCell(), initializeBoard(), isLoseByClick(), isWin(), leftClick(), revealBoard(), rightClick(), toString(), and updateBombCount().
bombProbability
int Board.bombProbability private
Definition at line 13 of file Board.java.
Referenced by Board(), and initializeBoard().
dim
int Board.dim private
Definition at line 11 of file Board.java.
Referenced by Board(), bombCount(), clickFirstCell(), initializeBoard(), isLose(), isWin(), revealBoard(), toString(), and updateBombCount().
The documentation for this class was generated from the following file:
src/Board.java