B5-Bank: UI Class Reference
UI Class Reference
Public Member Functions
UI (Bank bank, User user)
void startSimulation ()
void home ()
Private Member Functions
void runSimPage ()
void runSim (int months)
void loanPage ()
void createAutoLoan ()
void createMortgage ()
void createPersonalLoan ()
void transferPage ()
void createAccount ()
void viewAccounts ()
void specificAccount (Accounts account)
void createCheckings ()
void createSavings ()
void createRetirement ()
void homeScreenPage ()
void createAccountPage ()
void viewAccountPage ()
void viewTransferPage ()
void viewTransfers ()
void viewLoans ()
Private Attributes
User user
Bank bank
Scanner scanner
DecimalFormat df
Detailed Description
Definition at line 17 of file UI.java.
Constructor & Destructor Documentation
UI()
UI.UI (Bank bank, User user)
UI takes a Bank bank and User user to create the interface that is shown to the user in the terminal
Parameters
bank Bank bank that is added to UI
user User user that is added to UI
Definition at line 30 of file UI.java.
{
        this.user = user;
        this.bank = bank;
        this.scanner = new Scanner(System.in);
        this.df = new DecimalFormat();
    }
References bank, and user.
Member Function Documentation
createAccount()
void UI.createAccount () private
Definition at line 255 of file UI.java.
{
        createAccountPage();
        boolean run = true;
        while (run) {
            int choice = this.scanner.nextInt();
            switch (choice) {
            case 1:
                createCheckings();
                createAccountPage();
                break;
            case 2:
                createSavings();
                createAccountPage();
                break;
            case 3:
                createRetirement();
                createAccountPage();
                break;
            case 4:
                run = false;
                break;
            }
        }
    }
References createAccountPage(), createCheckings(), createRetirement(), and createSavings().
Referenced by home().
createAccountPage()
void UI.createAccountPage () private
Definition at line 371 of file UI.java.
{
        System.out.println("\n" + "Create an Account:\n\n" + "---------------------------------------\n"
                + "| Choose the account:           |\n" + "---------------------------------------\n"
                + "  1. Checking Account\n" + "  2. Savings Account\n" + "  3. Retirement Account\n\n"
                + "  4. Exit to Home\n" + "---------------------------------------\n"
                + "Enter the number corresponding to your choice:");
    }
Referenced by createAccount().
createAutoLoan()
void UI.createAutoLoan () private
Definition at line 148 of file UI.java.
{
        System.out.println("---------------------------------------\n" + "| AutoLoan :                         |\n"
                + "---------------------------------------\n" + "Enter the amount for this AutoLoan ");
        double amount = scanner.nextDouble();
        Loan loan = new AutoLoan(amount, 0.08, 72); // 5 years little short but eh
        boolean run = true;
        System.out.println("Auto Loan Request:\n" + "---------------------------------------\n"
                + "| Please provide the following details|\n" + "---------------------------------------\n"
                + "Loan Amount: " + loan.getAmount() + "\n" + "Loan Term: " + loan.getMonths() + "\n"
                + "Interest Rate: " + loan.getInterest() + "\n" + "Monthly Payment: " + df.format(loan.getMonthlyPay())
                + "\n" + "---------------------------------------\n" + "Do you accept?\n" + "1. Accept\n"
                + "2. Decline\n\n" + "Enter the number corresponding to your choice: ");
        while (run) {
            int choice = scanner.nextInt();
            switch (choice) {
            case 1:
                bank.addLoan(loan);
                run = false;
                break;
            case 2:
                System.out.println("Loan was not added");
                run = false;
                break;
            }
        }
    }
References Bank.addLoan(), bank, df, loans.Loan.getAmount(), loans.Loan.getInterest(), loans.Loan.getMonthlyPay(), loans.Loan.getMonths(), and scanner.
Referenced by loanPage().
createCheckings()
void UI.createCheckings () private
Definition at line 323 of file UI.java.
{
        System.out.println("---------------------------------------\n" + "|          Checking Account:       |\n"
                + "---------------------------------------\n" + "Enter the double amount you would like to deposit");
        double amount = this.scanner.nextDouble();
        Accounts checking = new CheckingAccount(user, amount);
        this.bank.addAccount(checking, "CheckingAccount");
        System.out.println("Account successful created");
    }
References Bank.addAccount(), and user.
Referenced by createAccount().
createMortgage()
void UI.createMortgage () private
Definition at line 178 of file UI.java.
{
        System.out.println("---------------------------------------\n" + "| Mortgage:                         |\n"
                + "---------------------------------------\n" + "Enter the amount for this AutoLoan ");
        double amount = scanner.nextDouble();
        Loan loan = new Mortgage(amount, 0.03, 360); // 5 years little short but eh
        boolean run = true;
        System.out.println("Auto Loan Request:\n" + "---------------------------------------\n"
                + "| Please provide the following details|\n" + "---------------------------------------\n"
                + "Loan Amount: " + loan.getAmount() + "\n" + "Loan Term: " + loan.getMonths() + "\n"
                + "Interest Rate: " + loan.getInterest() + "\n" + "Monthly Payment: " + loan.getMonthlyPay() + "\n"
                + "---------------------------------------\n" + "Do you accept?\n" + "1. Accept\n" + "2. Decline\n\n"
                + "Enter the number corresponding to your choice: ");
        while (run) {
            int choice = scanner.nextInt();
            switch (choice) {
            case 1:
                bank.addLoan(loan);
                run = false;
                break;
            case 2:
                System.out.println("Loan was not added");
                run = false;
                break;
            }
        }
    }
References Bank.addLoan(), bank, loans.Loan.getAmount(), loans.Loan.getInterest(), loans.Loan.getMonthlyPay(), loans.Loan.getMonths(), and scanner.
Referenced by loanPage().
createPersonalLoan()
void UI.createPersonalLoan () private
Definition at line 209 of file UI.java.
{
        System.out.println("---------------------------------------\n" + "| Personal Loan :                         |\n"
                + "---------------------------------------\n" + "Enter the amount for this AutoLoan ");
        double amount = scanner.nextDouble();
        Loan loan = new PersonalLoan(amount, 0.20, 180); // 5 years little short but eh
        boolean run = true;
        System.out.println("Auto Loan Request:\n" + "---------------------------------------\n"
                + "| Please provide the following details|\n" + "---------------------------------------\n"
                + "Loan Amount: " + loan.getAmount() + "\n" + "Loan Term: " + loan.getMonths() + "\n"
                + "Interest Rate: " + loan.getInterest() + "\n" + "Monthly Payment: " + df.format(loan.getMonthlyPay())
                + "\n" + "---------------------------------------\n" + "Do you accept?\n" + "1. Accept\n"
                + "2. Decline\n\n" + "Enter the number corresponding to your choice: ");
        while (run) {
            int choice = scanner.nextInt();
            switch (choice) {
            case 1:
                bank.addLoan(loan);
                run = false;
                break;
            case 2:
                System.out.println("Loan was not added");
                run = false;
                break;
            }
        }
    }
References Bank.addLoan(), bank, df, loans.Loan.getAmount(), loans.Loan.getInterest(), loans.Loan.getMonthlyPay(), loans.Loan.getMonths(), and scanner.
Referenced by loanPage().
createRetirement()
void UI.createRetirement () private
Definition at line 347 of file UI.java.
{
        System.out.println("---------------------------------------\n" + "|          Retirement Account:       |\n"
                + "---------------------------------------\n" + "Enter the double amount you would like to deposit");
        double amount = this.scanner.nextDouble();
        Accounts retirement = new RetirementAccount(user, amount, 0.08);
        this.bank.addAccount(retirement, "RetirementAccount");
        System.out.println("Account successful created");
    }
References Bank.addAccount(), and user.
Referenced by createAccount().
createSavings()
void UI.createSavings () private
Definition at line 335 of file UI.java.
{
        System.out.println("---------------------------------------\n" + "|          Savings Account:       |\n"
                + "---------------------------------------\n" + "Enter the double amount you would like to deposit");
        double amount = this.scanner.nextDouble();
        Accounts savings = new SavingAccount(user, amount, 0.06);
        this.bank.addAccount(savings, "SavingAccount");
        System.out.println("Account successful created");
    }
References Bank.addAccount(), and user.
Referenced by createAccount().
home()
void UI.home ()
home prints the interface and holds the user in a switch case while loop until the make a correct decision
Definition at line 48 of file UI.java.
                       {
        homeScreenPage();
        boolean run = true;
        while (run) {
            int choice = this.scanner.nextInt();
            switch (choice) {
            case 1:
                createAccount();
                homeScreenPage();
                break;
            case 2:
                viewAccounts();
                homeScreenPage();
                break;
            case 3:
                transferPage();
                homeScreenPage();
                break;
            case 4:
                loanPage();
                homeScreenPage();
                break;
            case 5:
                viewTransfers();
                homeScreenPage();
                break;
            case 6:
                runSimPage();
                homeScreenPage();
                break;
            case 7:
                System.out.println("Exiting program...");
                run = false;
                break;
            }
        }
    } // check to make sure they have a checking account
References createAccount(), homeScreenPage(), loanPage(), runSimPage(), transferPage(), viewAccounts(), and viewTransfers().
Referenced by startSimulation().
homeScreenPage()
void UI.homeScreenPage () private
Definition at line 359 of file UI.java.
{
        System.out.println("\n" + "Welcome " + user.getUsername() + " to Our Bank!\n"
                + "---------------------------------------\n" + "| Please choose one of the following: |\n"
                + "---------------------------------------\n" + "  1. Create an account\n" + "  2. View an account\n"
                + "  3. Transfer money between accounts\n" + "  4. Get a loan\n" + "  5. View transactions\n"
                + "  6. Run Simulation\n" + "  7. Exit the program\n\n" + "---------------------------------------\n"
                + "Enter the number corresponding to your choice:");
    }
References accounts.User.getUsername(), and user.
Referenced by home().
loanPage()
void UI.loanPage () private
Definition at line 112 of file UI.java.
{
        viewLoans();
        boolean run = true;
        while (run) {
            try {
                bank.getAccount("CheckingAccount").getInterest(); // not the best way to check but it works
                int choice = this.scanner.nextInt();
                switch (choice) {
                case 1:
                    createAutoLoan();
                    viewLoans();
                    break;
                case 2:
                    createMortgage();
                    viewLoans();
                    break;
                case 3:
                    createPersonalLoan();
                    viewLoans();
                    break;
                case 4:
                    run = false;
                    break;
                }
            } catch (Exception e) {
                System.out.println("\n\n\n" + "You must have a Checking account with this bank to apply for a loan\n"
                        + "Please enter 1 to continue:  ");
                scanner.nextInt();
                run = false;
            }
        }
    }
References bank, createAutoLoan(), createMortgage(), createPersonalLoan(), Bank.getAccount(), accounts.Accounts.getInterest(), scanner, and viewLoans().
Referenced by home().
runSim()
void UI.runSim (int months) private
Definition at line 103 of file UI.java.
{
        for (int i = 0; i < months; i++) {
            bank.runSimulation();
        }
    }
References bank, and Bank.runSimulation().
Referenced by runSimPage().
runSimPage()
void UI.runSimPage () private
Definition at line 89 of file UI.java.
{
        System.out.println("-------------------------------\n" + "|          Run Simulation     |\n"
                + "-------------------------------\n" + "*Make sure you have a checkings Account*\n"
                + "Enter the number of months you want to run the simulation for:\n");
        int months = scanner.nextInt();
        runSim(months);
        viewAccounts();
        System.out.println("Enter 1 to Continue: ");
        scanner.nextInt();
    }
References runSim(), scanner, and viewAccounts().
Referenced by home().
specificAccount()
void UI.specificAccount (Accounts account) private
Definition at line 302 of file UI.java.
{
        System.out.println("View Account Details:\n\n" + "---------------------------------------------\n"
                + "| Account Balance: " + account.getBalance() + "                   |\n" + "| Interest Rate: "
                + account.getInterest() + "                    |\n" + "---------------------------------------------\n"
                + "Options:\n" + "  1. Go Back\n" + "---------------------------------------------\n"
                + "Enter the number corresponding to your choice:");
        boolean run = true;
        while (run) {
            int choice = this.scanner.nextInt();
            switch (choice) {
            case 1:
                run = false;
                break;
            }
        }
    }
References accounts.Accounts.getBalance(), and accounts.Accounts.getInterest().
Referenced by viewAccounts().
startSimulation()
void UI.startSimulation ()
calls this.home method
Definition at line 40 of file UI.java.
{
        this.home();
    }
References home().
Referenced by Main.main().
transferPage()
void UI.transferPage () private
Definition at line 240 of file UI.java.
{
        viewTransferPage();
        int with = this.scanner.nextInt();
        System.out.println("Enter the account you want to transfer money to");
        int dep = this.scanner.nextInt();
        String withdrawKey = bank.getAccPosistion(with);
        String depositKey = bank.getAccPosistion(dep);
        System.out.println("Enter the double amount you would like to transfer: ");
        double amount = this.scanner.nextDouble();
        bank.transfer(amount, withdrawKey, depositKey);
    }
References bank, Bank.getAccPosistion(), Bank.transfer(), and viewTransferPage().
Referenced by home().
viewAccountPage()
void UI.viewAccountPage () private
Definition at line 382 of file UI.java.
{
        // this can be improved
        System.out.println("---------------------------------------\n" + "| Choose the account to view:           |\n"
                + "---------------------------------------\n" + bank.printAccounts() + "\n\n" + "  4. Exit to Home\n"
                + "---------------------------------------\n" + "Enter the number corresponding to your choice:");
    }
References bank, and Bank.printAccounts().
Referenced by viewAccounts().
viewAccounts()
void UI.viewAccounts () private
Definition at line 284 of file UI.java.
                                { // this can improved but I might leave it
        viewAccountPage();
        boolean run = true;
        while (run) {
            int account = this.scanner.nextInt();
            if (account == 4) {
                run = false;
            } else {
                String accKey = bank.getAccPosistion(account);
                specificAccount(bank.getAccount(accKey));
                run = false;
            }
        }
    }
References bank, Bank.getAccount(), Bank.getAccPosistion(), specificAccount(), and viewAccountPage().
Referenced by home(), and runSimPage().
viewLoans()
void UI.viewLoans () private
Definition at line 413 of file UI.java.
{
        System.out.println("---------------------------------------\n" + "| Please choose a loan option:       |\n"
                + "---------------------------------------\n" + "  1. Auto Loan\n" + "  2. Mortgage Loan\n"
                + "  3. Personal Loan\n" + "  4. Return to main menu\n\n" + "---------------------------------------\n"
                + "Enter the number corresponding to your choice: ");
    }
Referenced by loanPage().
viewTransferPage()
void UI.viewTransferPage () private
Definition at line 392 of file UI.java.
{
        System.out.println("Transfer Money:\n\n" + "---------------------------------------------\n"
                + "| Select the accounts for the transfer:     |\n" + "---------------------------------------------\n"
                + bank.printAccounts() + "---------------------------------------------\n"
                + "Enter the number corresponding to the 'from' account:");
    }
References bank, and Bank.printAccounts().
Referenced by transferPage().
viewTransfers()
void UI.viewTransfers () private
Definition at line 402 of file UI.java.
{
        System.out.println("---------------------------------------------\n" + "| Recorded Transfers and Loans:     |\n"
                + "---------------------------------------------\n");
        System.out.println(bank.printTransactions());
        System.out.println("Enter 1 to Continue");
        this.scanner.nextInt();
    }
References bank, and Bank.printTransactions().
Referenced by home().
Member Data Documentation
bank
Bank UI.bank private
Definition at line 19 of file UI.java.
Referenced by createAutoLoan(), createMortgage(), createPersonalLoan(), loanPage(), runSim(), transferPage(), UI(), viewAccountPage(), viewAccounts(), viewTransferPage(), and viewTransfers().
df
DecimalFormat UI.df private
Definition at line 21 of file UI.java.
Referenced by createAutoLoan(), and createPersonalLoan().
scanner
Scanner UI.scanner private
Definition at line 20 of file UI.java.
Referenced by createAutoLoan(), createMortgage(), createPersonalLoan(), loanPage(), and runSimPage().
user
User UI.user private
Definition at line 18 of file UI.java.
Referenced by createCheckings(), createRetirement(), createSavings(), homeScreenPage(), and UI().
The documentation for this class was generated from the following file:
src/UI.java