B5-Bank: Bank Class Reference
Bank Class Reference
Public Member Functions
Bank ()
void addAccount (Accounts account, String accKey)
void addTransaction (Transactions trans)
void addLoan (Loan loan)
void transfer (double amount, String accKey1, String accKey2)
Accounts getAccount (String accKey)
String getAccPosistion (int x)
void runSimulation ()
String printAccounts ()
String printTransactions ()
Private Member Functions
boolean NoDupl (String accKey)
Private Attributes
Dictionary< String, Accounts > accounts
ArrayList< Transactions > transactions
ArrayList< Loan > loans
DecimalFormat df
Detailed Description
Definition at line 21 of file Bank.java.
Constructor & Destructor Documentation
Bank()
Bank.Bank ()
Definition at line 31 of file Bank.java.
                  {
        this.accounts = new Hashtable<>();
        this.transactions = new ArrayList<>();
        this.loans = new ArrayList<>();
        this.df = new DecimalFormat();
    }
Member Function Documentation
addAccount()
void Bank.addAccount (Accounts account, String accKey)
AddAccount method adds a account to the dictionary and maps it the given string accKey
Parameters
account Accounts account to be add to the bank's dicitonary
accKey String accKey that is mapped to the added Account
Definition at line 45 of file Bank.java.
{
        if (NoDupl(accKey)) {
            this.accounts.put(accKey, account);
        } else {
            System.out.println("You already have this type of account created");
        }
    }
References NoDupl().
Referenced by UI.createCheckings(), UI.createRetirement(), and UI.createSavings().
addLoan()
void Bank.addLoan (Loan loan)
AddLoan method adds a loan to the bank's ArrayList<Loan> It finds the Bank's CheckingAccount and adds the amount specified in the loan then Created a Transaction instance the is added to the Bank's Transaction ArrayList<Transactions>
Parameters
loan
Definition at line 70 of file Bank.java.
{
        this.loans.add(loan);
        this.accounts.get("CheckingAccount").deposit(loan.getAmount());
        Transactions newLoan = new LoanTransaction(loan);
        this.addTransaction(newLoan);
    }
References addTransaction(), and loans.Loan.getAmount().
Referenced by UI.createAutoLoan(), UI.createMortgage(), and UI.createPersonalLoan().
addTransaction()
void Bank.addTransaction (Transactions trans)
AddTransaction adds a Transaction to the bank's ArrayList
Parameters
trans Transaction trans to be added
Definition at line 58 of file Bank.java.
{
        this.transactions.add(trans);
    }
Referenced by addLoan(), and transfer().
getAccount()
Accounts Bank.getAccount (String accKey)
Parameters
accKey String Key mapped to the account in the banks dictionary
Returns
Account that is mapped to the String Key
Definition at line 124 of file Bank.java.
{
        try {
            return accounts.get(accKey);
        } catch (Exception e) {
            return null;
        }
    }
Referenced by UI.loanPage(), and UI.viewAccounts().
getAccPosistion()
String Bank.getAccPosistion (int x)
GetAccPosition is used to help the interface and find the String Key of the account based on the order that the accounts are printed out
Parameters
x int x refers to the Integer position of each account when the print method iterated through them
Returns
String key of account based on order that the Dictionary is in
Definition at line 140 of file Bank.java.
{
        int counter = 1;
        for (Enumeration<String> i = accounts.keys(); i.hasMoreElements();) {
            String key = i.nextElement();
            if (x == counter) {
                return key;
            } else {
                counter++;
            }
        }
        return null;
    }
Referenced by UI.transferPage(), and UI.viewAccounts().
NoDupl()
boolean Bank.NoDupl (String accKey) private
Checks if an account mapped to accKey already exist within the bank's Dictionary
Parameters
accKey String accKey is the account key of the new account
Returns
false if the account already exist within the Dicitonary, True if there is no instance
Definition at line 85 of file Bank.java.
{
        Enumeration<String> keys = accounts.keys();
        while (keys.hasMoreElements()) {
            String key = keys.nextElement();
            if (key == accKey) {
                return false;
            }
        }
        return true;
    }
Referenced by addAccount().
printAccounts()
String Bank.printAccounts ()
Definition at line 190 of file Bank.java.
{
        String acc = "";
        int counter = 1;
        for (Enumeration<String> i = accounts.keys(); i.hasMoreElements();) {
            String key = i.nextElement();
            Accounts test = accounts.get(key);
            acc = acc + "  " + counter + ". " + key + "| Balance: " + df.format(test.getBalance()) + "\n";
            counter++;
        }
        return acc;
    }
References df, and accounts.Accounts.getBalance().
Referenced by UI.viewAccountPage(), and UI.viewTransferPage().
printTransactions()
String Bank.printTransactions ()
Definition at line 205 of file Bank.java.
{
        String retStr = "";
        int counter = 1;
        for (Transactions i : this.transactions) {
            retStr = retStr + counter + ": " + i.retInfo() + "\n";
            counter++;
        }
        return retStr;
    }
References transactions.
Referenced by UI.viewTransfers().
runSimulation()
void Bank.runSimulation ()
RunSimulation runs a 1 month simulation of the bank accounts by iterating through the loans and accounts and add or withdraw the amounts calculated for a single month
catches if the user does not have a checkings account and prints a warning to the interface
Definition at line 161 of file Bank.java.
{
        try {
            for (Loan loan : this.loans) {
                if (loan.getMonths() > 0) {
                    accounts.get("CheckingAccount").loanPay(loan.getMonthlyPay());
                    loan.makePayment();
                } else {
                    continue; // bad practice however removing the loan instantly throws
                                // checkForComodification error
                }
            }
            Enumeration<String> keys = accounts.keys();
            while (keys.hasMoreElements()) {
                String key = keys.nextElement();
                Double earned = accounts.get(key).calcInterest(1.0); // calculate for one month
                accounts.get(key).deposit(earned);
            }
        } catch (NullPointerException e) {
            System.out.println("Must have CheckingAccount to run Simulation");
        }
    }
References loans.
Referenced by UI.runSim().
transfer()
void Bank.transfer (double amount, String accKey1, String accKey2)
transfer method using the dictionary keys to withdraw a double amount from accKey1 and deposit that money into accKey2; Throws exception if accounts do not exist
Parameters
amount Double amount to be transfered
accKey1 String acckey1 is the account that is being withdrawn from
accKey2 String acckey2 is the key of the account being transfered to
Definition at line 105 of file Bank.java.
{
        try {
            Accounts withAcc = accounts.get(accKey1);
            Accounts depAcc = accounts.get(accKey2);
            double actualAmounnt = withAcc.withdraw(amount);
            depAcc.deposit(actualAmounnt);
            Transactions trans = new Transfer(withAcc, depAcc, actualAmounnt);
            this.addTransaction(trans);
        } catch (Exception e) {
            System.out.println("Could not complete that transfer");
        }
    }
References addTransaction(), accounts.Accounts.deposit(), and accounts.Accounts.withdraw().
Referenced by UI.transferPage().
Member Data Documentation
accounts
Dictionary<String, Accounts> Bank.accounts private
Bank class hold a Dictionary<String, Accounts>, ArrayList<Transactions>, ArrayList<Loans>
Definition at line 26 of file Bank.java.
df
DecimalFormat Bank.df private
Definition at line 29 of file Bank.java.
Referenced by printAccounts().
loans
ArrayList<Loan> Bank.loans private
Definition at line 28 of file Bank.java.
Referenced by runSimulation().
transactions
ArrayList<Transactions> Bank.transactions private
Definition at line 27 of file Bank.java.
Referenced by printTransactions().
The documentation for this class was generated from the following file:
src/Bank.java