B5-Bank: loans.Loan Interface Reference
loans.Loan Interface Reference
Public Member Functions
double getInterest ()
String getInfo ()
int getMonths ()
double getAmount ()
double getMonthlyPay ()
void makePayment ()
Detailed Description
An Transaction represents
Definition at line 8 of file Loan.java.
Member Function Documentation
getAmount()
double loans.Loan.getAmount ()
Returns
Double amount that is loaned out
Implemented in loans.AbstractLoan.
Referenced by Bank.addLoan(), UI.createAutoLoan(), UI.createMortgage(), and UI.createPersonalLoan().
getInfo()
String loans.Loan.getInfo ()
Returns
String of the Loans Interest, Time in months, and Amount
Implemented in loans.AbstractLoan.
Referenced by transaction.LoanTransaction.retInfo().
getInterest()
double loans.Loan.getInterest ()
Returns
double Interest
Implemented in loans.AbstractLoan.
Referenced by UI.createAutoLoan(), UI.createMortgage(), and UI.createPersonalLoan().
getMonthlyPay()
double loans.Loan.getMonthlyPay ()
Calculate the amount that will be paid each month
Returns
double monthly payment amount
Implemented in loans.AbstractLoan.
Referenced by UI.createAutoLoan(), UI.createMortgage(), and UI.createPersonalLoan().
getMonths()
int loans.Loan.getMonths ()
Returns
Int Months of how long the contracted loan is
Implemented in loans.AbstractLoan.
Referenced by UI.createAutoLoan(), UI.createMortgage(), and UI.createPersonalLoan().
makePayment()
void loans.Loan.makePayment ()
deducts a single month from the loan
Implemented in loans.AbstractLoan.
The documentation for this interface was generated from the following file:
src/loans/Loan.java