B5-Bank: accounts.Accounts Interface Reference
accounts.Accounts Interface Reference
Public Member Functions
void deposit (double amount)
double withdraw (double amount)
double getBalance ()
double getInterest ()
String getAccountId ()
double calcInterest (double months)
User getUser ()
void printAcc ()
void loanPay (double amount)
Detailed Description
An Transaction represents anything that holds the fundamental methods associated with a bank account
Definition at line 8 of file Accounts.java.
Member Function Documentation
calcInterest()
double accounts.Accounts.calcInterest (double months)
Calculates the compound balance of the account based on the accounts interest and current balance
Parameters
Double Months: amount of months into the future you want to calculate for
Returns
double compound interest (current balance + calculated interest)
Implemented in accounts.AbstractAccount, accounts.CheckingAccount, accounts.RetirementAccount, and accounts.SavingAccount.
deposit()
void accounts.Accounts.deposit (double amount)
Adds money into the account given that value is positive double if amount is negative system prints out error message
Parameters
amount positive double amount that is added to the account
Implemented in accounts.AbstractAccount.
Referenced by Bank.transfer().
getAccountId()
String accounts.Accounts.getAccountId ()
Returns
String Id of the account
Implemented in accounts.AbstractAccount, accounts.CheckingAccount, accounts.RetirementAccount, and accounts.SavingAccount.
Referenced by transaction.Transfer.retInfo().
getBalance()
double accounts.Accounts.getBalance ()
Returns
double balance of the account
Implemented in accounts.AbstractAccount.
Referenced by Bank.printAccounts(), and UI.specificAccount().
getInterest()
double accounts.Accounts.getInterest ()
Returns
double interest of the account
Implemented in accounts.AbstractAccount.
Referenced by UI.loanPage(), and UI.specificAccount().
getUser()
User accounts.Accounts.getUser ()
Returns
User user associated with the account
Implemented in accounts.AbstractAccount.
loanPay()
void accounts.Accounts.loanPay (double amount)
LoanPay takes given double amount and takes it out of the accounts balance, this method will put your accounts balance into the negatives
Parameters
amount double amount to be subtracted from the accounts balance
Implemented in accounts.AbstractAccount.
printAcc()
void accounts.Accounts.printAcc ()
print the account balance
Implemented in accounts.AbstractAccount.
withdraw()
double accounts.Accounts.withdraw (double amount)
Withdraws double amount from the bank account
Parameters
amount positive double amount that will be withdrawn from account
Returns
returns double amount that is successful withdrawn. return 0.0 if double amount is negative or account lacks the funds to withdraw amount
Implemented in accounts.AbstractAccount.
Referenced by Bank.transfer().
The documentation for this interface was generated from the following file:
src/accounts/Accounts.java